'use strict';
// Nominal coordinates and DOM/resource integration only. No real pixel claim.
const {boot,settle}=require('../independent/v02/dom_harness.cjs'),assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{const h=await boot(),checks=[];await settle(h);const stage=h.$('#stage');Object.defineProperty(stage,'clientWidth',{value:1000,configurable:true});Object.defineProperty(stage,'clientHeight',{value:600,configurable:true});
 const check=(name,fn)=>{fn();checks.push({name,pass:true});};
 async function encounter(enemies,team=['amy','lynae','mornye','denia']){h.click('#setupBtn');for(const n of h.w.document.querySelectorAll('#teamChoices input[type=checkbox]'))n.checked=team.includes(n.value);h.change('#encounterSelect','custom');[...h.w.document.querySelectorAll('[data-enemy-slot]')].forEach((n,i)=>n.value=enemies[i]||'');h.click('#startBtn');await settle(h);await h.frame(250);return h.w.BattleLabDiagnostics.getStageLayout().positions;}
 for(const enemies of [['snip'],['snip','predator'],['snip','snip','predator'],['bracer','snip','predator'],['bracer','carapace'],['crownless']]){const pos=await encounter(enemies),e=pos.filter(x=>x.id.startsWith('enemy')),a=pos.filter(x=>x.id.startsWith('ally')),mean=x=>x.reduce((n,p)=>n+p.y,0)/x.length;check(enemies.join('+')+' advances the current actor ahead of every idle ally',()=>{const active=pos.find(p=>p.id===h.diag().current),rest=a.filter(p=>p.id!==h.diag().current);assert(rest.every(p=>active.x<p.x));});check(enemies.join('+')+' centers enemy row on ally midpoint',()=>assert.equal(mean(e),mean(a)));if(e.length===2)check(enemies.join('+')+' places two enemies above/below the midpoint',()=>assert(e[0].y<mean(a)&&e[1].y>mean(a)));if(enemies[0]==='bracer'&&enemies.length===3)check('Single elite is front/center; two common enemies behind symmetrically',()=>{assert(e[0].x>e[1].x&&e[0].x>e[2].x);assert.equal(e[0].y,mean(a));assert.equal(e[1].y+e[2].y,mean(a)*2);});}
 h.click('#setupBtn');check('Prism encounters exist in the setup menu',()=>{assert(h.$('#encounterSelect option[value=prism_trial]'));assert(h.$('#encounterSelect option[value=prism_havoc_trial]'));});check('Rover supports four elemental modes and four separate appearances',()=>{assert.equal(h.w.document.querySelectorAll('[data-mode=rover] option').length,4);assert.equal(h.w.document.querySelectorAll('[data-appearance=rover] option').length,4);});for(const n of h.w.document.querySelectorAll('#teamChoices input[type=checkbox]'))n.checked=n.value==='rover';h.change('[data-mode=rover]','electro');h.change('[data-appearance=rover]','female_school');h.change('#encounterSelect','prism_trial');h.click('#startBtn');await settle(h);await h.frame(500);
 check('Selected Rover mode uses dedicated electro resources and selected appearance persists',()=>{const s=h.w.BattleLabDiagnostics.getSnapshot().state;assert.equal(s.allies[0].key,'rover');assert.equal(s.allies[0].mode,'electro');assert.equal(s.allies[0].primary,'surge');assert.equal(h.w.BattleLabDiagnostics.getProject().appearance.rover,'female_school');});
 check('Rover pending art is explicit and cannot be an old character alias',()=>{const a=h.w.BattleLabDiagnostics.assets,form=a.forms.rover.female_school,slot=a.slots[form.idle];assert.equal(slot.entity,'rover');assert(form.pending||slot.src);if(form.pending){assert.equal(slot.src,null);assert(slot.pending);}});
 check('Five prism species have their own new art URLs and no mirror permission',()=>{const a=h.w.BattleLabDiagnostics.assets;for(const key of ['glacio_prism','fusion_prism','aero_prism','spectro_prism','havoc_prism']){const slot=a.slots[a.enemies[key].idle];assert(slot.src.includes(key));assert.equal(slot.mirrorAllowed,false);}});
 h.click('#assetsBtn');h.click('[data-tab=project]');h.input('#reduceMotion',true);h.$('#reduceMotion').checked=true;h.$('#reduceMotion').dispatchEvent(new h.w.Event('change',{bubbles:true}));check('Reduced motion setting is persisted in the real project model',()=>assert(h.w.BattleLabDiagnostics.getProject().settings.reducedMotion));h.click('[data-close=assetDialog]');await h.frame(250);
 check('No DOM runtime errors while testing six formations, Rover, prisms and reduced motion',()=>assert.deepStrictEqual(h.errors,[]));
 const result={kind:'Simulated DOM and coordinate audit; no pixel verification',createdAt:new Date().toISOString(),passed:checks.length,checks};fs.writeFileSync(path.join(__dirname,'ui_formation_rover_results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));h.close();})().catch(e=>{console.error(e);process.exitCode=1;});
