/* Offline battle lab. DOM UI only; engine owns all gameplay mutations. */
(function(){'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k), clone=o=>JSON.parse(JSON.stringify(o));
const P=window.BATTLE_PARAMETERS,D=window.DEFAULT_ASSETS||{slots:{},forms:{},enemies:{}};
const LABEL={glacio:'冷凝',dust:'尘微之声',umbra:'暗流',wind:'弦风息',surge:'电涌',energy:'共鸣能量',fusion:'热熔',spectro:'衍射',havoc:'湮灭',electro:'导电',aero:'气动',physical:'物理',sword:'迅刀',pistols:'佩枪',broadblade:'长刃',rectifier:'音感仪',sync:'同步率',resonance:'谐振',color:'流彩',calibration:'校准',expectation:'期待',thread:'丝线',primary:'主资源',human:'人形',mech:'机兵',normal:'常态',summer:'夏装',winter:'冬装',red:'布景',blue:'幻灭',tune:'震谐',strain:'震蚀',guard:'防御',brace:'岩架',charge:'蓄势',aim:'瞄准',cutline:'裁线',barrier:'护盾',taunt:'挑衅',outro:'延奏',outro_guard:'延奏减伤',status_outro:'异常增幅',encourage:'鼓舞',male_default:'男漂泊者 · 默认',male_school:'男漂泊者 · 校服',female_default:'女漂泊者 · 默认',female_school:'女漂泊者 · 校服'};
const ENC={normal:'普通遭遇',elite_humanoid:'人形精英遭遇',elite_nonhumanoid:'异形精英遭遇',boss:'头目遭遇',prism_trial:'四属性棱镜试炼',prism_havoc_trial:'湮灭棱镜试炼'};
const AUDIO={bgm:'战斗 BGM',select:'选中',confirm:'确认',attack:'攻击',hit:'受击',break:'共振击破',concerto:'协奏',transform:'变身',win:'胜利',loss:'失败'};
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const store=new LocalProjectStore(),imageCache=new Map(),renderCache=new Map(),audioCache=new Map();
let battle=null,project=freshProject(),selection=null,targetId=null,busy=false,auto=false,timer=null,epoch=0,assetTab='sprites',assetKey='',previewAction=null,visuals=new Map(),floats=[],lastAnim=0,lastSave=null,savedSnapshot=null,bgm=null;
let menuCategory='root',inspectedAction=null,menuOpen=false,menuActorId=null,confirmLockUntil=0,portraitDirty=false;
let muted=true,audioUnlocked=false,previewCanvas=null,stageBounds=[],stageEffects=[],lastFrame=0,saveTimer=null;
function freshProject(){return {schema:'resonant-project-v1',version:1,assetSet:'20261009-v1',overrides:{},calibration:{},appearance:{},background:{data:null,name:'',fit:'cover',opacity:1},audio:{},settings:{master:0.7,sfx:0.8,bgm:0.5,outline:1,showAnchors:false,reducedMotion:reduced},battleConfig:{difficulty:'standard',team:['amy','lynae','mornye','denia'],encounter:'normal',level:20,hp_fraction:1,mode:{amy:'tune',denia:'fusion'}}};}
function status(text,error=false){$('assetStatus').textContent=text;$('assetStatus').style.color=error?'#ffb19b':'';}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),3300);}
function modalOpen(id){pause();$(id).showModal();}
function modalClose(id){$(id).close();schedule();}
function pause(){clearTimeout(timer);timer=null;}
function anyModal(){return !!document.querySelector('dialog[open]');}
function safeAction(fn){try{const r=fn();if(r&&r.catch)r.catch(e=>toast('操作失败：'+e.message));return r;}catch(e){toast('操作失败：'+e.message);}}
async function persistProject(){try{const ok=await store.set('project',project);$('saveStatus').textContent=ok?'素材与设置已存本机 · 不上传':'临时会话 · 请导出项目以防丢失';}catch(e){$('saveStatus').textContent='本地保存失败，请导出项目';status('保存失败：'+e.message,true);}}
function queueProjectSave(){clearTimeout(saveTimer);saveTimer=setTimeout(persistProject,160);}
async function saveBattle(silent=false){if(!battle)return;try{savedSnapshot=battle.snapshot();const ok=await store.set('battle',savedSnapshot);lastSave=Date.now();$('saveStatus').textContent=ok?'战局已保存 · '+new Date().toLocaleTimeString('zh-CN',{hour12:false}):'临时保存 · 关闭后可能丢失，请导出项目';if(!silent)toast(ok?'战局已保存到本浏览器':'无法持久保存，请导出项目');}catch(e){toast('战局保存失败：'+e.message);}}
function startBattle(config=project.battleConfig,save=true){pause();epoch++;auto=false;$('autoBtn').textContent='自动演算：关';$('autoBtn').setAttribute('aria-pressed','false');const next=new BattleEngine(P,config);next.start();battle=next;project.battleConfig=clone(next.options);resetMenu();visuals.clear();floats=[];stageEffects=[];busy=false;render();queueProjectSave();if(save)saveBattle(true);playAudio('bgm');schedule();}
function schedule(){pause();if(!battle||battle.result||busy||anyModal())return;if(battle.current?.side==='enemy'||auto){const token=epoch;timer=setTimeout(()=>{if(token!==epoch||busy||anyModal())return;execute(battle.current.side==='enemy'?()=>battle.stepEnemy():()=>battle.autoAction());},(auto?160:650)/speed());}}
function speed(){return Number($('speedSelect').value)||1;}
function execute(fn){if(busy||!battle||battle.result)return;pause();const before=clone([...battle.allies,...battle.enemies]);let result;try{result=fn();}catch(e){toast('行动未完成：'+e.message);schedule();return;}if(!result.ok){toast(result.reason);render();return;}resetMenu();busy=true;const token=epoch;animateEvents(result.events,before);render();const duration=(project.settings.reducedMotion?100:680)/speed();setTimeout(()=>{if(token!==epoch)return;busy=false;render();saveBattle(true);schedule();},duration);}
function animateEvents(events,before){const now=performance.now(),duration=(project.settings.reducedMotion?100:650)/speed(),old=new Map(before.map(u=>[u.id,u]));lastAnim=now;
 for(const e of events){const u=battle.getUnit(e.actor||e.unit||e.target);if(e.event==='action'||e.event==='enemy_action'){const a=battle.getUnit(e.actor);if(a){const prev=old.get(a.id);visuals.set(a.id,{start:now,end:now+duration,action:e.skill||'basic',form:prev?.form||a.form,kind:'action',fromForm:prev?.form,target:e.target});$('actionBanner').textContent=a.name+' · '+(a.skills[e.skill]?.name||P.generic_skills[e.skill]?.name||e.skill);playAudio('attack');}}
  if(e.event==='damage'){const t=battle.getUnit(e.target);if(t){const prior=visuals.get(t.id)||{};visuals.set(t.id,{...prior,hitStart:now+duration*.22,hitEnd:now+duration*.75});floats.push({id:t.id,text:String(e.amount),kind:e.status_damage?'status':'damage',start:now+duration*.2,end:now+duration*1.3});playAudio('hit');}}
  if(e.event==='heal'){floats.push({id:e.target,text:'+'+e.amount,kind:'heal',start:now+duration*.15,end:now+duration*1.3});}
  if(e.event==='shield'){floats.push({id:e.target,text:'共振 −'+e.amount,kind:'shield',start:now+duration*.25,end:now+duration*1.5});}
  if(e.event==='break'){floats.push({id:e.target,text:'共振击破',kind:'break',start:now+duration*.4,end:now+duration*1.8});playAudio('break');}
  if(e.event==='incapacitated'){const t=battle.getUnit(e.unit||e.target);if(t){const prior=visuals.get(t.id)||{};visuals.set(t.id,{...prior,koStart:now+duration*.25,koEnd:now+duration,koForm:old.get(t.id)?.form||t.form});}}
  if(e.event==='concerto'){const a=battle.getUnit(e.actor);if(a)visuals.set(a.id,{start:now,end:now+duration,action:'concerto',form:a.form,kind:'support'});playAudio('concerto');}
  if(e.event==='form'||e.event==='form_change'){playAudio('transform');}if(e.event==='concerto_ready'){floats.push({id:e.actor,text:'协奏就绪 · 手动释放',kind:'break',start:now,end:now+duration*3});}
 }
 for(const u of [...battle.allies,...battle.enemies])if(old.get(u.id)?.form!==u.form){const v=visuals.get(u.id)||{};visuals.set(u.id,{...v,transform:true,formAfter:u.form});playAudio('transform');}
 if(battle.result){auto=false;$('autoBtn').textContent='自动演算：关';playAudio(battle.result.outcome==='win'?'win':'loss');if(bgm){bgm.pause();bgm=null;}}
}
function render(){if(!battle)return;renderQueue();renderCards();renderActions();renderLogs();renderResult();$('partyCount').textContent=battle.allies.length+' / 4';$('roundNumber').textContent=String(battle.round).padStart(2,'0');$('encounterLabel').textContent=ENC[project.battleConfig.encounter]||'自定义遭遇';$('difficultyBadge').textContent=P.difficulties?.[battle.options.difficulty]?.name||'标准';renderTacticalNotice();const field=P.characters.mornye?.skills?.field,active=battle.field_until>=battle.round; $('fieldBadge').textContent=active?(field?.name||'定标场')+' · 至第 '+battle.field_until+' 轮末':'';if(active){$('fieldBadge').dataset.tooltip=field?.effectSummary||field?.description||P.rules.field;$('fieldBadge').tabIndex=0;}else{$('fieldBadge').removeAttribute('data-tooltip');$('fieldBadge').removeAttribute('tabindex');}}
function statusDescription(u,key,v,base=''){let text=base||'当前生效。';if(key==='taunt'){const owner=battle.getUnit(v.owner);text='施放者：'+(owner?.name||'已离场角色')+'。1 AP，本窗口一次；只能在敌方尚未瞄准/蓄力锁定前施放。下一次实际造成伤害的单体攻击改向施放者，并增加15%伤害，随后消费。群攻不改目标、不增加这15%、不消费。最长至施放后第2轮末；施放者倒地或撤离时清除。';}if(key==='spectro_mark'){const owner=battle.getUnit(v.owner);if(owner&&battle.previewPacket)text+='；若由施放者'+owner.name+'触发，目前预计 '+battle.previewPacket(owner,u,.25,'spectro',true)+' 衍射伤害；换触发者按其面板重算。';}if(key==='critical'&&u.side==='ally'&&battle.previewPacket)text+='；当前雷陨预测：'+battle.living('enemy').map(t=>t.name+' '+battle.previewPacket(u,t,.25,'electro',true)+' 导电伤害').join('；')+'。';if(key==='cutline'){const atk=u.atk*(u.phase===2?(u.phase2_attack_multiplier||1):1);text+='；当前攻击 '+Number(atk.toFixed(2))+' → '+Number((atk*.85).toFixed(2))+'。';}if(key==='barrier')text+='；当前剩余吸收量 '+v.amount+'。';return text;}
function statusChips(u){
 const chips=Object.entries(u.status||{}).map(([k,v])=>{const d=battle.describeStatus?.(u.id,k)||{};d.description=statusDescription(u,k,v,d.description);return `<button class="status-chip ${['fusion','tune','cutline','charge','aim','rend','exposed'].includes(k)?'bad':''}" type="button" data-tooltip="${esc(d.description||'当前生效；数值由本场角色属性结算。')}" aria-label="${esc((d.name||LABEL[k]||k)+'：'+(d.description||''))}">${esc(d.name||LABEL[k]||k)}${v.n?' ×'+v.n:''}${v.amount?' '+v.amount:''}</button>`;}).join('');
 return chips+(u.broken_until>=battle.round&&u.broken_until?`<button class="status-chip bad" data-tooltip="取消准备动作，跳过第 ${u.skip_round||u.broken_until} 轮的一个敌方行动窗口；不附加易伤。第 ${(u.skip_round||u.broken_until)+1} 轮开始恢复共振。">共振击破</button>`:'')+(u.retreated?'<span class="status-chip">已撤离</span>':'');
}
function apMeter(u,compact=false){const ap=Number(u.ap??0),temp=Number(u.temp_ap??0);return `<div class="ap-meter ${compact?'compact':''}" aria-label="普通行动点 ${ap}/6，临时行动点 ${temp}/2"><span class="ap-caption">AP</span><span class="ap-normal">${Array.from({length:6},(_,i)=>`<i class="${i<ap?'filled':''}"></i>`).join('')}</span><span class="ap-temp" title="延奏临时 AP；只用于接收者的下一行动窗口">${Array.from({length:2},(_,i)=>`<i class="${i<temp?'filled':''}"></i>`).join('')}</span><strong>${ap}<em>+${temp}</em></strong></div>`;}
function renderCards(){const current=battle.current?.id;
 $('partyCards').innerHTML=battle.allies.map(u=>`<div class="unit-card ${current===u.id?'current':''} ${u.hp<=0||u.retreated?'ko':''}" data-card-unit="${esc(u.id)}"><div class="unit-heading"><span class="unit-name">${esc(u.name)}</span><small>${u.hp<=0?'无法战斗':esc(u.key==='rover'?LABEL[project.appearance.rover||'male_default']:LABEL[u.form]||u.form)}${u.overdrive?' · 星辉':''}</small></div><div class="unit-sub"><span>${esc(LABEL[u.element]||u.element)} / ${esc(LABEL[u.weapon]||u.weapon)}</span><span>HP ${u.hp} / ${u.maxhp}</span></div><div class="bar"><i style="width:${u.hp/u.maxhp*100}%"></i></div>${apMeter(u)}<div class="stat-line">${Object.entries(u.rsc).map(([k,v])=>`<span>${esc(LABEL[k]||k)} <b>${v}/${u.resources[k]}</b></span>`).join('')}</div><div class="bar resource"><i style="width:${(u.rsc[u.primary]||0)/(u.resources[u.primary]||1)*100}%"></i></div><div class="stat-line"><span>个人协奏</span><b>${u.concerto}/100${u.concerto===100?' · 可延奏':''}</b></div><div class="bar concerto"><i style="width:${u.concerto}%"></i></div><div class="status-chips">${statusChips(u)}</div></div>`).join('');
 $('enemyCards').innerHTML=battle.enemies.filter(u=>u.hp>0).map(u=>{const intent=battle.enemyIntent(u.id),danger=intent&&!intent.hidden;return `<div class="unit-card ${current===u.id?'current':''}"><div class="unit-heading"><span class="unit-name">${esc(u.name)}${u.rank==='boss'?' · 阶段'+u.phase:''}</span>${u.rank!=='common'?`<span class="shield-num" title="共振值">◇ ${u.shield} / ${u.maxshield}</span>`:''}</div><div class="unit-sub"><span>${({common:'普通',elite:'精英',boss:'头目'})[u.rank]||u.rank}</span><span>HP ${u.hp} / ${u.maxhp}</span></div><div class="bar enemy"><i style="width:${u.hp/u.maxhp*100}%"></i></div><div class="enemy-resistance"><button class="status-chip" data-tooltip="${esc(['glacio','fusion','electro','aero','spectro','havoc'].map(k=>(LABEL[k]||k)+'：'+((u.immune_elements||[]).includes(k)?'免疫':('承伤 ×'+Number(u.resist?.[k]??1).toFixed(2)))).join('；'))}">属性承伤${u.immune_elements?.length?' · '+u.immune_elements.map(k=>esc(LABEL[k]||k)).join('/')+'免疫':''}</button></div>${u.rank!=='common'?`<div class="bar resonance"><i style="width:${u.maxshield?u.shield/u.maxshield*100:0}%"></i></div>`:''}${u.part&&!u.part.destroyed?`<div class="enemy-part"><span>${esc(u.part.name)} · 暴露部件</span><b>${u.part.hp} / ${u.part.maxhp}</b><div class="bar part"><i style="width:${u.part.hp/u.part.maxhp*100}%"></i></div></div>`:u.part?.destroyed?'<div class="intent-quiet">部件已破坏</div>':''}${danger?`<div class="intent committed">危险预警：${esc(intent.name)}<br><span>${esc(intent.telegraphText||'')}</span><br><strong>对策：${esc(intent.counterplayText||'')}</strong></div>`:'<div class="intent-quiet">常规意图隐藏</div>'}<div class="status-chips">${statusChips(u)}</div></div>`;}).join('')||'<div class="unit-card muted">敌方已全部倒下</div>';
}

function renderLogs(){const box=$('battleLog'),near=box.scrollHeight-box.scrollTop-box.clientHeight<60;box.innerHTML=battle.log.slice(-150).map(l=>`<div class="log-entry ${esc(l.event)}"><span class="log-round">${String(l.round).padStart(2,'0')}</span>${esc(l.message||l.event)}</div>`).join('');if(near)box.scrollTop=box.scrollHeight;}
function renderResult(){const box=$('resultOverlay');if(!battle.result||busy){box.classList.add('hidden');return;}const r=battle.result;box.classList.remove('hidden');const name={win:'VICTORY',loss:'DEFEAT',escaped:'WITHDRAWN',escaped_partial:'WITHDRAWN'}[r.outcome]||'FINISHED';box.innerHTML=`<span class="eyebrow">ENCOUNTER COMPLETE</span><h2>${name}</h2><p>${({win:'战斗胜利',loss:'队伍失去战斗能力',escaped:'全队撤离',escaped_partial:'幸存队员已撤离'})[r.outcome]} · ${battle.round} 回合 · 共振击破 ${battle.count.breaks||0} 次</p><p>我方累计伤害 ${battle.count.damage_ally||0} / 治疗 ${battle.count.heal||0}</p><button id="resultRestart" class="primary">重开本场</button>`;$('resultRestart').onclick=()=>startBattle();}
function formEntry(entity,form){const fs=D.forms?.[entity]||{};if(entity==='amy'&&form==='mech')form='mecha';let f=project.appearance[entity]||(entity==='rover'?'male_default':form);if((entity==='amy'||entity==='denia'))f=form;if(entity==='rover')return fs[f]||null;return fs[f]||fs[form]||fs.normal||Object.values(fs)[0]||null;}
function slotFor(u,action='idle',form=u.form){if(u.side==='enemy'){const e=D.enemies?.[u.key];return e?.slot||e?.idle||Object.keys(D.slots).find(k=>D.slots[k].entity===u.key);}const f=formEntry(u.key,form);if(action.startsWith('item_'))return f?.actions?.support||f?.actions?.encourage||f?.idle;return f?.actions?.[u.mode+'_'+action]||f?.actions?.[action]||f?.[action]||f?.idle||Object.keys(D.slots).find(k=>D.slots[k].entity===u.key&&D.slots[k].form===form);}
function sourceFor(key){const s=D.slots[key];return own(project.overrides,key)?project.overrides[key].data:s?.src;}
function getImage(src){if(!src)return null;if(imageCache.has(src))return imageCache.get(src);const img=new Image();img.decoding='async';const rec={img,ready:false,error:false};imageCache.set(src,rec);img.onload=()=>{rec.ready=true;portraitDirty=true;};img.onerror=()=>{rec.error=true;portraitDirty=true;};img.src=src;return rec;}
function calibration(key){const s=D.slots[key]||{},a=s.anchors||{};const anchor=a.ground||a.foot||a.pivot;let ax=.5,ay=1;if(Array.isArray(anchor)){ax=anchor[0];ay=anchor[1];}else if(anchor&&typeof anchor==='object'){ax=anchor.x??.5;ay=anchor.y??1;}
 // Manifest coordinates may be normalized or native pixels; normalize once.
 if(ax>1)ax/=s.width||s.naturalWidth||1;if(ay>1)ay/=s.height||s.naturalHeight||1;
 const portrait=s.portraitRect||PORTRAIT_RECTS[s.entity+'.'+s.form]||PORTRAIT_RECTS[s.entity]||[0,0,s.width||1,s.height||1],head=a.head||s.headAnchor;let hx=ax,hy=(s.alphaBBox?.[1]??0)/(s.height||1);if(head){hx=Array.isArray(head)?head[0]:head.x;hy=Array.isArray(head)?head[1]:head.y;if(hx>1)hx/=s.width||1;if(hy>1)hy/=s.height||1;}return {headX:hx,headY:hy,portraitX:portrait[0]/(s.width||1),portraitY:portrait[1]/(s.height||1),portraitW:portrait[2]/(s.width||1),portraitH:portrait[3]/(s.height||1),scale:1,x:0,y:0,ground:0,anchorX:ax,anchorY:ay,weaponX:.5,weaponY:.5,bodyHeight:s.referenceBodyHeight||s.standingBodyHeight||s.bodyHeight||359,outline:project.settings.outline??1,...(project.calibration[key]||{})};}
function outlineCanvas(rec,w,h,outline){const k=rec.img.src+'|'+w+'x'+h+'|'+outline;if(renderCache.has(k))return renderCache.get(k);const c=document.createElement('canvas');c.width=w+outline*2;c.height=h+outline*2;const cx=c.getContext('2d');cx.imageSmoothingEnabled=false;const tint=document.createElement('canvas');tint.width=w;tint.height=h;const tx=tint.getContext('2d');tx.imageSmoothingEnabled=false;tx.drawImage(rec.img,0,0,w,h);tx.globalCompositeOperation='source-in';tx.fillStyle='#111b22';tx.fillRect(0,0,w,h);if(outline)for(let dx=-outline;dx<=outline;dx++)for(let dy=-outline;dy<=outline;dy++)if(dx||dy)cx.drawImage(tint,outline+dx,outline+dy);cx.drawImage(rec.img,outline,outline,w,h);if(renderCache.size>180)renderCache.clear();renderCache.set(k,c);return c;}
function scenePositions(W,H){
 const allies=battle.allies,liveEnemies=battle.enemies.filter(u=>u.hp>0||visuals.get(u.id)?.koEnd>performance.now()),center=H*.51;
 const allyStep=Math.min(H*.115,62),ally=allies.map((u,i)=>({id:u.id,x:u.id===battle.currentId&&u.side==='ally'&&!battle.result?W*.60:W*(.73+i*.035),y:center+(i-(allies.length-1)/2)*allyStep}));
 const elite=liveEnemies.filter(u=>u.rank==='elite'||u.rank==='boss'),common=liveEnemies.filter(u=>u.rank!=='elite'&&u.rank!=='boss');
 const enemy=[];function row(list,x,step){list.forEach((u,i)=>enemy.push({id:u.id,x:W*x,y:center+(i-(list.length-1)/2)*step}));}
 if(elite.length){row(elite,elite.some(u=>u.rank==='boss')?.27:.34,Math.min(H*.22,112));row(common,.18,Math.min(H*.27,140));}
 else row(common,.27,Math.min(H*.205,104));
 return [...enemy,...ally];
}

function drawUnit(ctx,u,p,W,H,now,preview=false,keyOverride=null){const v=visuals.get(u.id)||{},inAction=now<v.end,dead=u.hp<=0,enemyDead=dead&&u.side==='enemy';if(u.retreated)return;if(enemyDead&&(!v.koEnd||now>v.koEnd))return;let form=inAction?v.form:u.form,action=inAction?v.action:'idle';if(dead&&u.side==='ally'){action='down';form=v.koForm||u.form;}else if(!inAction&&battle.result?.outcome==='win')action='victory';else if(!inAction&&u.hp/u.maxhp<=.25)action='critical';if(!inAction&&u.status.guard)action='guard';if(!dead&&!inAction&&v.hitEnd>now&&now>v.hitStart){const f=formEntry(u.key,form),hurt=f?.actions?.hurt;if(hurt&&hurt!==f.idle&&!D.slots[hurt]?.pending)action='hurt';}if(v.transform&&inAction&&now>v.start+(v.end-v.start)*.5){form=v.formAfter;action='idle';}
 let sequenceKey=null;if(inAction){const entry=formEntry(u.key,v.form);let sequence=entry?.sequences?.[u.mode+'_'+v.action]||entry?.sequences?.[v.action];if(v.transform){const from=v.form==='mech'?'mecha':v.form,to=v.formAfter==='mech'?'mecha':v.formAfter;sequence=D.transitions?.[u.key+'.'+from+'_to_'+to]||sequence;}if(sequence?.length){const t=Math.min(.999,Math.max(0,(now-v.start)/(v.end-v.start)));sequenceKey=sequence[Math.floor(t*sequence.length)];}}const key=keyOverride||sequenceKey||slotFor(u,action,form),s=D.slots[key],cal=calibration(key),rec=getImage(sourceFor(key));let x=p.x+cal.x,y=p.y+cal.y-cal.ground;
 if(inAction&&!project.settings.reducedMotion&&!preview){const progress=(now-v.start)/(v.end-v.start);x+=(u.side==='ally'?-1:1)*Math.sin(Math.PI*progress)*20;}

 if(v.hitEnd>now&&now>v.hitStart&&!project.settings.reducedMotion){x+=Math.sin(now*.14)*3;}
 const baseBody=Math.max(24,Math.min(67,H*.11,W*.07)),reference=u.side==='enemy'?359:cal.bodyHeight;
 const ratio=preview?Math.min(280/(rec?.img.height||s?.height||400),330/(rec?.img.width||s?.width||400))*cal.scale:(baseBody/Math.max(1,reference))*cal.scale*(u.side==='ally'?(s?.bodyScale||1):1);
 const iw=rec?.img.naturalWidth||s?.width||s?.naturalWidth||200,ih=rec?.img.naturalHeight||s?.height||s?.naturalHeight||300;const w=Math.max(1,Math.round(iw*ratio)),h=Math.max(1,Math.round(ih*ratio)),left=Math.round(x-w*cal.anchorX),top=Math.round(y-h*cal.anchorY),ol=Math.max(0,Math.round(cal.outline));
 const headX=left+w*cal.headX,headY=top+h*cal.headY,cast=s?.anchors?.rightPalm||s?.anchors?.cast,castAX=Array.isArray(cast)?cast[0]:cast?.x,castAY=Array.isArray(cast)?cast[1]:cast?.y,castX=cast?left+w*(castAX>1?castAX/(s.width||iw):castAX):null,castY=cast?top+h*(castAY>1?castAY/(s.height||ih):castAY):null;if(!preview)stageBounds.push({id:u.id,slot:key,left,top,width:w,height:h,x,y,headX,headY,castX,castY});
 ctx.save();if(enemyDead){const t=Math.max(0,(now-v.koStart)/(v.koEnd-v.koStart));ctx.globalAlpha=1-t;x+=t*6;}
 if(!enemyDead&&!dead&&!preview){ctx.fillStyle=u.side==='ally'?'#0b151c6b':'#11151475';ctx.beginPath();ctx.ellipse(x,y+2,Math.max(12,w*.22),4,0,0,Math.PI*2);ctx.fill();}
 if(rec?.ready){const oc=outlineCanvas(rec,w,h,ol);if(targetId===u.id&&!preview){ctx.save();ctx.shadowColor='#f7d78d';ctx.shadowBlur=9;ctx.drawImage(oc,left-ol,top-ol);ctx.restore();}else ctx.drawImage(oc,left-ol,top-ol);if((v.hitEnd>now&&now>v.hitStart&&Math.floor(now/60)%2===0)||(v.transform&&inAction&&Math.abs(now-v.start-(v.end-v.start)*.5)<60)){ctx.globalCompositeOperation='source-atop';ctx.globalAlpha=.33;ctx.fillStyle='#fff4c9';ctx.fillRect(left,top,w,h);ctx.globalCompositeOperation='source-over';}}
 else{ctx.fillStyle=u.side==='ally'?'#7fa49a':'#ae8a74';ctx.fillRect(Math.round(x-12),Math.round(y-45),24,45);ctx.fillStyle='#d8e0d4';ctx.font='9px sans-serif';ctx.textAlign='center';ctx.fillText(!s||s.pending?'素材待绘':rec?.error?'图像载入失败':'载入…',x,y-51);}
 if(project.settings.showAnchors||preview){ctx.strokeStyle='#6dd9d4';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-8,y);ctx.lineTo(x+8,y);ctx.moveTo(x,y-8);ctx.lineTo(x,y+8);ctx.stroke();ctx.strokeStyle='#e3adcf';ctx.beginPath();ctx.moveTo(headX-5,headY);ctx.lineTo(headX+5,headY);ctx.moveTo(headX,headY-5);ctx.lineTo(headX,headY+5);ctx.stroke();ctx.strokeStyle='#ceab69';ctx.beginPath();ctx.moveTo(left+w*cal.weaponX-5,top+h*cal.weaponY);ctx.lineTo(left+w*cal.weaponX+5,top+h*cal.weaponY);ctx.moveTo(left+w*cal.weaponX,top+h*cal.weaponY-5);ctx.lineTo(left+w*cal.weaponX,top+h*cal.weaponY+5);ctx.stroke();}
 ctx.restore();
 if(!preview&&!enemyDead){ctx.textAlign='center';const active=u.id===battle.currentId&&u.side==='ally'&&!busy&&!battle.result,selected=targetId===u.id;
  if(selected||(!selection&&active)){const bob=project.settings.reducedMotion?0:Math.sin(now*.005)*4,yy=headY-14+bob;ctx.save();ctx.fillStyle=selected?'#98e5e1':'#f6d792';ctx.shadowColor='#071017';ctx.shadowBlur=5;ctx.beginPath();ctx.moveTo(headX-6,yy-6);ctx.lineTo(headX+6,yy-6);ctx.lineTo(headX,yy+3);ctx.closePath();ctx.fill();ctx.restore();}
  if(s?.needsRevision){ctx.font='9px sans-serif';ctx.fillStyle='#f0bd97';ctx.fillText('动作待修 · 用户退回',x,y+18);}if(u.key==='rover'&&action!=='idle'&&!(formEntry(u.key,form)?.actions?.[u.mode+'_'+action]||formEntry(u.key,form)?.actions?.[action])){ctx.font='9px sans-serif';ctx.fillStyle='#e8c68a';ctx.fillText('动作待绘 · '+(u.skills?.[action]?.name||P.generic_skills[action]?.name||({critical:'濒危',down:'倒地',victory:'胜利',guard:'防御',concerto:'延奏'})[action]||action),x,y+18);}if(u.side==='enemy'){ctx.font='10px "Microsoft YaHei",sans-serif';ctx.fillStyle='#deded0';ctx.fillText(u.name,x,y+18);if(u.rank!=='common'){ctx.font='9px sans-serif';ctx.fillStyle=u.broken_until>=battle.round&&u.broken_until?'#ffd78c':'#cdbb8a';ctx.fillText(u.broken_until>=battle.round&&u.broken_until?'RESONANCE BREAK':'◇ '+u.shield+' / '+u.maxshield,x,y+31);}}
 }

 return {w,h,left,top,x,y};}
// Hard-edged screen-pixel rope. It is a transient visual of the already resolved
// action event, never another attack or a source of gameplay state.
function pixelLine(ctx,a,b,size){let x=a.x,y=a.y,dx=Math.abs(b.x-x),sx=x<b.x?1:-1,dy=-Math.abs(b.y-y),sy=y<b.y?1:-1,err=dx+dy;for(;;){ctx.fillRect(x-Math.floor(size/2),y-Math.floor(size/2),size,size);if(x===b.x&&y===b.y)break;const e=2*err;if(e>=dy){err+=dy;x+=sx;}if(e<=dx){err+=dx;y+=sy;}}}
function drawActionEffects(ctx,now){stageEffects=[];for(const [id,v]of visuals){const u=battle.getUnit(id);if(u?.key!=='rover'||u.mode!=='electro'||v.action!=='skill'||now<v.start+(v.end-v.start)*.12||now>v.start+(v.end-v.start)*.82)continue;const a=stageBounds.find(b=>b.id===id),b=stageBounds.find(b=>b.id===v.target);if(!a||!b||!Number.isFinite(a.castX)||!Number.isFinite(a.castY))continue;const from={x:Math.round(a.castX),y:Math.round(a.castY)},to={x:Math.round(b.x),y:Math.round(b.headY+(b.y-b.headY)*.44)},dx=to.x-from.x,dy=to.y-from.y,len=Math.max(1,Math.hypot(dx,dy)),jags=[0,-5,4,-3,5,-4,0],points=jags.map((offset,i)=>({x:Math.round(from.x+dx*i/6-dy/len*offset),y:Math.round(from.y+dy*i/6+dx/len*offset)}));ctx.save();ctx.filter='none';ctx.shadowBlur=0;ctx.globalAlpha=1;for(const [color,size]of [['#302947',5],['#9870d8',3],['#dfcaff',1]]){ctx.fillStyle=color;for(let i=1;i<points.length;i++)pixelLine(ctx,points[i-1],points[i],size);}ctx.restore();stageEffects.push({kind:'electro_tether',actor:id,target:v.target,slot:a.slot,from,to,points});}}
function drawStage(now){requestAnimationFrame(drawStage);if(!battle||now-lastFrame<15)return;lastFrame=now;const canvas=$('battleCanvas'),rect=canvas.getBoundingClientRect(),W=Math.round(rect.width),H=Math.round(rect.height),dpr=Math.min(window.devicePixelRatio||1,2);if(!W||!H)return;if(canvas.width!==W*dpr||canvas.height!==H*dpr){canvas.width=W*dpr;canvas.height=H*dpr;renderCache.clear();}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,W,H);ctx.imageSmoothingEnabled=false;
 const focused=menuOpen&&!selection&&!busy&&battle.current?.side==='ally';ctx.save();if(focused)ctx.filter='blur(2.5px)';
 if(project.background.data){const r=getImage(project.background.data);if(r?.ready){const scale=project.background.fit==='contain'?Math.min(W/r.img.width,H/r.img.height):Math.max(W/r.img.width,H/r.img.height);ctx.globalAlpha=project.background.opacity;ctx.drawImage(r.img,(W-r.img.width*scale)/2,(H-r.img.height*scale)/2,r.img.width*scale,r.img.height*scale);ctx.globalAlpha=1;}}
 const pos=scenePositions(W,H);stageBounds=[];for(const p of [...pos].sort((a,b)=>a.y-b.y)){const u=battle.getUnit(p.id);if(focused&&u.id===battle.currentId)continue;drawUnit(ctx,u,p,W,H,now);}
 ctx.restore();if(focused){ctx.save();ctx.fillStyle='#07101888';ctx.fillRect(0,0,W,H);ctx.restore();const p=pos.find(p=>p.id===battle.currentId);if(p)drawUnit(ctx,battle.current,p,W,H,now);}
 drawActionEffects(ctx,now);
 for(const f of floats){if(now<f.start||now>f.end)continue;const p=pos.find(p=>p.id===f.id);if(!p)continue;const t=(now-f.start)/(f.end-f.start),index=floats.filter(x=>x.id===f.id&&x.start<=f.start).indexOf(f);ctx.save();ctx.globalAlpha=Math.min(1,(1-t)*2);ctx.textAlign='center';ctx.font=(f.kind==='break'?'bold 19px':f.kind==='damage'?'bold 25px':'bold 11px')+' sans-serif';ctx.fillStyle=({heal:'#adf2ba',shield:'#f4d387',break:'#f6d98e',status:'#bfa7eb'})[f.kind]||'#fff4d8';ctx.strokeStyle='#172126';ctx.lineWidth=3;const y=p.y-75-t*35-index*19;ctx.strokeText(f.text,p.x,y);ctx.fillText(f.text,p.x,y);ctx.restore();}floats=floats.filter(f=>f.end>now);
 if(portraitDirty){drawPortraits();portraitDirty=false;}positionOverlays();positionActorTrigger();if(previewCanvas&&$('assetDialog').open&&assetTab==='sprites')drawAssetPreview(now);
}
function positionActorTrigger(){const trigger=$('actorTrigger'),u=battle.current,b=stageBounds.find(p=>p.id===u?.id),active=u?.side==='ally'&&!busy&&!battle.result&&!selection;trigger.classList.toggle('hidden',!active||!b);if(!active||!b)return;const w=Math.max(40,Math.min(100,b.width*.8));trigger.style.left=Math.round(b.x-w/2)+'px';trigger.style.top=Math.round(b.top-2)+'px';trigger.style.width=w+'px';trigger.style.height=Math.max(42,b.height+7)+'px';trigger.setAttribute('aria-label',u.name+'，'+u.ap+' 普通行动点，'+(u.temp_ap||0)+' 临时行动点，点击打开行动菜单');trigger.setAttribute('aria-expanded',String(menuOpen));}

function drawAssetPreview(now){const c=previewCanvas,ctx=c.getContext('2d'),key=assetKey,s=D.slots[key];if(!s)return;const W=c.width=450,H=c.height=330;ctx.clearRect(0,0,W,H);ctx.imageSmoothingEnabled=false;const fake={id:'preview',key:s.entity,side:s.side||((own(P.enemies,s.entity))?'enemy':'ally'),form:s.form,hp:100,maxhp:100,status:{}};drawUnit(ctx,fake,{x:W*.5,y:H*.86},W,H,now,true,key);ctx.strokeStyle='#859b8770';ctx.beginPath();ctx.moveTo(0,H*.86);ctx.lineTo(W,H*.86);ctx.stroke();}
function renderSetup(){const cfg=project.battleConfig;$('encounterSelect').innerHTML=Object.keys(P.encounters).map(k=>`<option value="${esc(k)}">${esc(ENC[k]||k)}</option>`).join('')+'<option value="custom">自定义 · 1–4 个敌人</option>';$('difficultySelect').innerHTML=Object.entries(P.difficulties||{}).map(([k,d])=>`<option value="${esc(k)}" ${k===(cfg.difficulty||'standard')?'selected':''}>${esc(d.name)}</option>`).join('');$('difficultyDescription').textContent=P.difficulties?.[$('difficultySelect').value]?.description||'';$('teamChoices').innerHTML=Object.entries(P.characters).map(([key,u])=>`<label class="team-choice"><span><input type="checkbox" value="${key}" ${cfg.team.includes(key)?'checked':''}> ${esc(u.name)}</span><small>${LABEL[u.element]} · 速度 ${u.speed}</small>${u.mode_options?`<select data-mode="${key}" aria-label="${esc(u.name)}战斗模式">${u.mode_options.map(m=>`<option value="${m}" ${(cfg.mode?.[key]||u.mode_default)===m?'selected':''}>${LABEL[m]||m}模式</option>`).join('')}</select>`:''}${key==='rover'?`<select data-appearance="rover" aria-label="漂泊者性别与服装">${['male_default','male_school','female_default','female_school'].map(f=>`<option value="${f}" ${(project.appearance.rover||'male_default')===f?'selected':''}>${LABEL[f]} · ${D.forms.rover?.[f]?.readyUniquePoses||0}/${D.forms.rover?.[f]?.plannedUniquePoses||16}图</option>`).join('')}</select>`:''}</label>`).join('');$('encounterSelect').value=Array.isArray(cfg.encounter)?'custom':cfg.encounter;$('levelInput').value=cfg.level;$('hpInput').value=Math.round((cfg.hp_fraction??1)*100);$('hpOutput').textContent=$('hpInput').value+'%';$('customEnemySlots').innerHTML=Array.from({length:4},(_,i)=>`<label>敌方槽 ${i+1}<select data-enemy-slot="${i}"><option value="">空</option>${Object.entries(P.enemies).map(([k,e])=>`<option value="${k}" ${(Array.isArray(cfg.encounter)?cfg.encounter[i]:['snip','predator'][i])===k?'selected':''}>${esc(e.name)}</option>`).join('')}</select></label>`).join('');$('customEnemies').classList.toggle('hidden',$('encounterSelect').value!=='custom');$('setupError').textContent='';}
function startFromSetup(){const team=[...$('teamChoices').querySelectorAll('input:checked')].map(x=>x.value);if(team.length<1||team.length>4){$('setupError').textContent='请选择 1–4 名不同角色。';return;}const level=Number($('levelInput').value);if(!Number.isInteger(level)||level<1||level>60){$('setupError').textContent='等级需要是 1–60 的整数。';return;}let encounter=$('encounterSelect').value;if(encounter==='custom'){encounter=[...$('customEnemySlots').querySelectorAll('select')].map(s=>s.value).filter(Boolean);if(!encounter.length){$('setupError').textContent='自定义遭遇至少需要一名敌人。';return;}}$('teamChoices').querySelectorAll('[data-appearance]').forEach(s=>project.appearance[s.dataset.appearance]=s.value);const mode={};$('teamChoices').querySelectorAll('[data-mode]').forEach(s=>mode[s.dataset.mode]=s.value);startBattle({team,encounter,level,difficulty:$('difficultySelect').value,hp_fraction:Number($('hpInput').value)/100,mode});$('migrationNotice').classList.add('hidden');$('setupDialog').close();schedule();}
function renderAssetPanel(){previewCanvas=null;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===assetTab));if(assetTab==='sprites')renderSpritePanel();else if(assetTab==='background')renderBackgroundPanel();else if(assetTab==='audio')renderAudioPanel();else renderProjectPanel();}
function renderSpritePanel(){const keys=Object.keys(D.slots);if(!assetKey||!own(D.slots,assetKey))assetKey=keys[0];const s=D.slots[assetKey],cal=calibration(assetKey),entity=s.entity;const entities=[...Object.entries(P.characters),...Object.entries(P.enemies)].filter(([k])=>keys.some(slot=>D.slots[slot].entity===k));const forms=[...new Set(keys.filter(k=>D.slots[k].entity===entity).map(k=>D.slots[k].form))];const currentSlots=keys.filter(k=>D.slots[k].entity===entity&&D.slots[k].form===s.form);const override=project.overrides[assetKey];
 $('assetPanel').innerHTML=`<div class="asset-grid"><div class="asset-controls"><div class="form-grid" style="grid-template-columns:1fr 1fr"><label>角色 / 敌人<select id="assetEntity">${entities.map(([k,u])=>`<option value="${k}" ${k===entity?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label><label>形态 / 外观<select id="assetForm">${forms.map(f=>`<option value="${esc(f)}" ${f===s.form?'selected':''}>${esc(LABEL[f]||f)}</option>`).join('')}</select></label></div><label class="asset-field">动作槽（${currentSlots.length} · 已有图 ${currentSlots.filter(k=>D.slots[k].src).length}）<select id="assetSlot">${currentSlots.map(k=>`<option value="${esc(k)}" ${k===assetKey?'selected':''}>${esc(D.slots[k].action+' · '+D.slots[k].label)}</option>`).join('')}</select></label><div class="asset-buttons"><label class="file-label">导入此动作 PNG / WebP / JPG<input id="spriteFile" type="file" accept="image/png,image/webp,image/jpeg,image/gif"></label><button id="resetSpriteBtn">恢复原图</button><button id="inspectSpriteBtn">原尺寸审图</button></div><p class="asset-description">${override?'已替换：'+esc(override.name):s.pending?'待绘槽位：可导入本地原图；未列为完成素材。':s.needsRevision?'用户退回待修：'+esc(s.reviewNote):'当前随包图：'+esc(s.label)} · ${s.width}×${s.height}<br>朝向：${s.side==='enemy'?'左侧朝右':'右侧朝左 / 左前方'}。不进行镜像。身体基准 ${s.bodyHeight}px，原图透明边距保留。</p><div class="calibration-grid">${[['scale','显示倍率',.1,4,.01],['x','水平偏移 px',-500,500,1],['y','垂直偏移 px',-500,500,1],['ground','离地高度 px',-200,300,1],['bodyHeight','身体参考高度',20,3000,1],['outline','屏幕描边 px',0,3,1],['anchorX','接地点 X (比例)',-1,2,.001],['anchorY','接地点 Y (比例)',-1,2,.001],['headX','头顶锚点 X',0,1,.001],['headY','头顶锚点 Y',0,1,.001],['weaponX','武器锚点 X',0,1,.001],['weaponY','武器锚点 Y',0,1,.001],['portraitX','头像裁切 X',0,1,.001],['portraitY','头像裁切 Y',0,1,.001],['portraitW','头像裁切宽',.01,1,.001],['portraitH','头像裁切高',.01,1,.001]].map(([k,label,min,max,step])=>`<label class="asset-field">${label}<input type="number" data-cal="${k}" value="${cal[k]}" min="${min}" max="${max}" step="${step}"></label>`).join('')}</div><div class="asset-buttons"><button id="resetCalibration">重置校准</button><button id="applyFormCalibration">应用到本形态全部动作</button>${s.side==='ally'&&!['amy','denia'].includes(entity)?'<button id="useAppearance">设为当前外观</button>':''}</div><label class="inline-check"><input type="checkbox" id="showAnchors" ${project.settings.showAnchors?'checked':''}>战场显示接地 / 武器锚点</label></div><div><div class="asset-preview"><canvas id="assetPreviewCanvas"></canvas><span class="preview-label">原图预览 · 青接地 / 粉头顶 / 金武器</span></div><p class="asset-description" style="margin-top:12px">最近邻显示，描边在缩放后以屏幕像素补外轮廓，不改原 PNG。它不能恢复缩小消失的内部细节。角色位置和尺度可独立校准；武器锚点用于效果定位，不会把长武器强行贴地。</p><p class="asset-description">此预览按外框适配，仅用于看清原图；实际战场采用身体参考高度统一比例。头目身体固定约 3.5 倍友方，不按翼展等高。</p></div></div>`;
 previewCanvas=$('assetPreviewCanvas');$('inspectSpriteBtn').disabled=!sourceFor(assetKey);$('inspectSpriteBtn').onclick=()=>{const img=$('spriteFullImage');img.src=sourceFor(assetKey);img.alt=s.label+' · 不镜像原尺寸';$('spriteFullTitle').textContent=s.label+' · 原尺寸审图';modalOpen('spriteZoomDialog');};$('assetEntity').onchange=e=>{assetKey=keys.find(k=>D.slots[k].entity===e.target.value);renderSpritePanel();};$('assetForm').onchange=e=>{assetKey=keys.find(k=>D.slots[k].entity===entity&&D.slots[k].form===e.target.value);renderSpritePanel();};$('assetSlot').onchange=e=>{assetKey=e.target.value;renderSpritePanel();};$('spriteFile').onchange=e=>safeAction(async()=>{const f=e.target.files[0];if(!f)return;const chosenKey=assetKey,chosenProject=project;const item=await readImage(f);if(chosenProject!==project)throw new Error('项目已切换，请重新导入');project.overrides[chosenKey]=item;renderCache.clear();await persistProject();status('已导入 '+item.name+'，仅保存在本机。');renderSpritePanel();});$('resetSpriteBtn').onclick=()=>{delete project.overrides[assetKey];renderCache.clear();queueProjectSave();renderSpritePanel();status('已恢复随包原图。');};$('resetCalibration').onclick=()=>{delete project.calibration[assetKey];renderCache.clear();queueProjectSave();renderSpritePanel();};$('applyFormCalibration').onclick=()=>{const c=clone(calibration(assetKey));currentSlots.forEach(k=>project.calibration[k]=clone(c));queueProjectSave();status('本形态所有动作已应用相同校准；个别动作接地点仍可单独调整。');};$('assetPanel').querySelectorAll('[data-cal]').forEach(input=>input.oninput=()=>{const val=Number(input.value),min=Number(input.min),max=Number(input.max);if(!Number.isFinite(val)||val<min||val>max){input.setCustomValidity('超出范围');return;}input.setCustomValidity('');project.calibration[assetKey]={...calibration(assetKey),[input.dataset.cal]:val};renderCache.clear();queueProjectSave();});$('showAnchors').onchange=e=>{project.settings.showAnchors=e.target.checked;queueProjectSave();};if($('useAppearance'))$('useAppearance').onclick=()=>{project.appearance[entity]=s.form;queueProjectSave();status('当前外观已切换；数值与机制不变。');};
}
function renderBackgroundPanel(){const bg=project.background;$('assetPanel').innerHTML=`<div class="asset-grid"><div class="asset-controls"><label class="file-label">导入战斗背景<input id="backgroundFile" type="file" accept="image/png,image/webp,image/jpeg,image/gif"></label><p class="asset-description">当前：${esc(bg.name||'中性调试舞台（没有背景图片）')}<br>支持 PNG、WebP、JPG、GIF，单张不超过 20 MiB。不接受 SVG 或远程 URL。</p><label class="asset-field">铺放方式<select id="backgroundFit"><option value="cover" ${bg.fit==='cover'?'selected':''}>填满（裁切边缘）</option><option value="contain" ${bg.fit==='contain'?'selected':''}>完整显示（留边）</option></select></label><label class="asset-field">背景不透明度 <input id="backgroundOpacity" type="range" min="0" max="1" step="0.05" value="${bg.opacity}"></label><div class="asset-buttons"><button id="clearBackground">恢复中性舞台</button></div></div><div><div class="asset-preview" id="backgroundPreview" style="display:flex;align-items:center;justify-content:center">${bg.data?'<img id="bgPreviewImg" alt="背景预览" style="max-width:100%;max-height:360px;image-rendering:pixelated">':'<span class="muted">尚未导入背景素材</span>'}</div><p class="asset-description" style="margin-top:12px">此测试不包含八方旅人的背景、音乐或音效。背景只用于显示，不参与伤害或碰撞。</p></div></div>`;if($('bgPreviewImg'))$('bgPreviewImg').src=bg.data;$('backgroundFile').onchange=e=>safeAction(async()=>{const f=e.target.files[0];if(!f)return;const chosenProject=project;const item=await readImage(f);if(chosenProject!==project)throw new Error('项目已切换，请重新导入');project.background={...bg,...item};await persistProject();$('sceneLabel').textContent='本地背景 · '+item.name;renderBackgroundPanel();status('背景已导入，刷新仍保留（需浏览器允许本地存储）。');});$('backgroundFit').onchange=e=>{project.background.fit=e.target.value;queueProjectSave();};$('backgroundOpacity').oninput=e=>{project.background.opacity=Number(e.target.value);queueProjectSave();};$('clearBackground').onclick=()=>{project.background={data:null,name:'',fit:'cover',opacity:1};$('sceneLabel').textContent='中性调试舞台 · 等待背景素材';queueProjectSave();renderBackgroundPanel();};}
function renderAudioPanel(){$('assetPanel').innerHTML=`<div class="form-grid" style="grid-template-columns:1fr 1fr 1fr"><label>主音量<input id="masterVolume" type="range" min="0" max="1" step=".05" value="${project.settings.master}"></label><label>BGM 音量<input id="bgmVolume" type="range" min="0" max="1" step=".05" value="${project.settings.bgm}"></label><label>事件音效音量<input id="sfxVolume" type="range" min="0" max="1" step=".05" value="${project.settings.sfx}"></label></div><p class="asset-description">默认全部留空且静音，不生成测试声。导入 WAV / MP3 / OGG / M4A（单个 ≤30 MiB）。点击试听会请求浏览器开始播放；编码不支持时会明确提示。</p><div>${Object.entries(AUDIO).map(([key,label])=>{const a=project.audio[key];return `<div class="audio-row"><div><h3>${label}</h3><small>${esc(a?.name||'未设置 / 静音')}</small></div><input type="file" data-audio="${key}" aria-label="导入${label}" accept="audio/wav,audio/mpeg,audio/ogg,audio/mp4,audio/webm,.mp3,.wav,.ogg,.m4a"><div><button data-play="${key}" ${a?'':'disabled'}>试听</button> <button data-remove-audio="${key}" ${a?'':'disabled'}>清除</button></div></div>`;}).join('')}</div><div class="asset-buttons" style="margin-top:14px"><button id="stopAudio">停止试听</button><button id="audioMuteToggle">${muted?'解除静音':'全部静音'}</button></div>`;
 for(const [id,k] of [['masterVolume','master'],['bgmVolume','bgm'],['sfxVolume','sfx']])$(id).oninput=e=>{project.settings[k]=Number(e.target.value);if(bgm)bgm.volume=project.settings.master*project.settings.bgm;queueProjectSave();};$('assetPanel').querySelectorAll('[data-audio]').forEach(input=>input.onchange=e=>safeAction(async()=>{const f=e.target.files[0];if(!f)return;const chosenProject=project,audioKey=input.dataset.audio;const item=await readAudio(f);if(chosenProject!==project)throw new Error('项目已切换，请重新导入');project.audio[audioKey]=item;stopAllAudio();await persistProject();renderAudioPanel();status('音频已保存，本地播放需要用户点击解锁。');}));$('assetPanel').querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>{audioUnlocked=true;muted=false;updateMute();playAudio(b.dataset.play,true);});$('assetPanel').querySelectorAll('[data-remove-audio]').forEach(b=>b.onclick=()=>{delete project.audio[b.dataset.removeAudio];stopAllAudio();queueProjectSave();renderAudioPanel();});$('stopAudio').onclick=stopAllAudio;$('audioMuteToggle').onclick=()=>{toggleMute();renderAudioPanel();};}
function playAudio(key,preview=false){if(muted||!audioUnlocked||!project.audio[key]?.data)return;const data=project.audio[key].data;if(key==='bgm'){if(bgm){if(bgm.src===data&&!bgm.paused)return;bgm.pause();}bgm=new Audio(data);bgm.loop=!preview;bgm.volume=project.settings.master*project.settings.bgm;bgm.play().catch(()=>{status('浏览器未允许此音频播放，请重新点击试听或更换编码。',true);toast('音频未能播放，请点击试听或更换编码');});return;}
 const a=new Audio(data);a.volume=project.settings.master*project.settings.sfx;audioCache.set(a,a);a.onended=()=>audioCache.delete(a);a.onerror=()=>{audioCache.delete(a);if(preview)status('此音频无法解码，请换用 MP3、WAV 或 OGG。',true);};a.play().catch(()=>{audioCache.delete(a);if(preview)status('播放未成功：浏览器权限或音频编码不受支持。',true);});}
function stopAllAudio(){if(bgm){bgm.pause();bgm=null;}for(const a of audioCache.keys()){a.pause();a.currentTime=0;}audioCache.clear();}
function updateMute(){$('muteBtn').textContent=muted?'声音：静音':'声音：开启';$('muteBtn').setAttribute('aria-pressed',String(muted));}
function toggleMute(){muted=!muted;audioUnlocked=true;updateMute();if(muted)stopAllAudio();else playAudio('bgm');}
function renderProjectPanel(){$('assetPanel').innerHTML=`<div class="project-options"><p>项目文件会嵌入你导入的图片和音频、校准值、外观与编队设置，也可包含当前战局。随包的 ${Object.values(D.slots).filter(s=>s.src).length} 张默认 PNG 仍从 assets 文件夹读取，不重复嵌入。</p><p class="muted">离线版请保持整个文件夹一起移动。网页与离线版的本地存储相互独立，换浏览器/换设备后导入项目 JSON 即可恢复自定义素材；默认图需要这套程序的同版素材。</p><label class="inline-check"><input type="checkbox" id="includeBattle" checked>导出时包含当前战局</label><div class="project-buttons"><button id="exportProject" class="primary">导出可携项目 JSON</button><label class="file-label">导入项目<input id="importProject" type="file" accept="application/json,.json"></label></div><label class="inline-check"><input type="checkbox" id="reduceMotion" ${project.settings.reducedMotion?'checked':''}>减少动作与闪烁</label><p class="muted">本地状态：${store.available?'IndexedDB 可用；素材刷新后仍保存。':'当前浏览器不允许持久缓存，请及时导出项目。'} 不发送素材、战局或日志到服务器。</p><div class="rules-note">导入为原子操作：格式、大小、资源类型与战局全部通过检查后才替换当前项目。失败时保持当前项目与战局。不会执行 JSON 中的脚本、SVG、远程图片地址或网页。</div><div class="project-buttons"><button id="clearCache" class="danger">清理本程序本地缓存</button><button id="resetAllAssets">恢复所有默认素材 / 校准</button></div><p class="asset-description">清理仅影响此程序的本地数据库；不会删除你电脑上的原始文件。请先导出想保留的项目。</p></div>`;$('exportProject').onclick=()=>safeAction(()=>exportProject($('includeBattle').checked));$('importProject').onchange=e=>safeAction(async()=>{const f=e.target.files[0];if(!f)return;if(f.size>140*1024*1024)throw new Error('项目文件超过 140 MiB');const parsed=JSON.parse(await f.text());const checked=await validateProject(parsed);pause();epoch++;project=checked.project;if(checked.battle){battle=checked.battle;project.battleConfig=clone(battle.options);busy=false;auto=false;visuals.clear();floats=[];stageEffects=[];resetMenu();render();}else startBattle(project.battleConfig);stopAllAudio();imageCache.clear();renderCache.clear();await persistProject();await saveBattle(true);renderProjectPanel();$('sceneLabel').textContent=project.background.data?'本地背景 · '+project.background.name:'中性调试舞台 · 等待背景素材';status(checked.migration||'项目导入成功。自定义素材已嵌入，无需重新选择原文件。');if(checked.migration)showMigration(checked.migration);});$('reduceMotion').onchange=e=>{project.settings.reducedMotion=e.target.checked;queueProjectSave();};$('clearCache').onclick=()=>{if(!window.confirm('清除本程序保存的战局、素材和设置？电脑原文件不会被删除。'))return;safeAction(async()=>{await store.clear();savedSnapshot=null;project=freshProject();stopAllAudio();startBattle(project.battleConfig,false);clearTimeout(saveTimer);await store.clear();$('saveStatus').textContent='已清理本地缓存；当前为默认临时战局';renderProjectPanel();status('本程序本地缓存已清理。后续新设置会再次保存。');});};$('resetAllAssets').onclick=()=>{if(!window.confirm('恢复所有随包素材与校准？当前战局不变，导入素材将从此项目移除。'))return;const base=freshProject();project.overrides={};project.calibration={};project.appearance={};project.background=base.background;project.audio={};$('sceneLabel').textContent='中性调试舞台 · 等待背景素材';imageCache.clear();renderCache.clear();stopAllAudio();queueProjectSave();renderProjectPanel();status('已恢复全部默认素材。');};}
async function dataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('无法读取文件'));r.readAsDataURL(file);});}
async function readImage(file){if(file.size>20*1024*1024)throw new Error('图片超过 20 MiB');const bytes=new Uint8Array(await file.slice(0,16).arrayBuffer());let mime='';if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)mime='image/png';else if(bytes[0]===255&&bytes[1]===216)mime='image/jpeg';else if(String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')mime='image/webp';else if(String.fromCharCode(...bytes.slice(0,3))==='GIF')mime='image/gif';else throw new Error('只接受可识别的 PNG、JPG、WebP、GIF，不接受 SVG');const data=await dataURL(new Blob([file],{type:mime}));const dims=await decodeImage(data);return {data,name:file.name.slice(0,180),mime,width:dims.width,height:dims.height};}
async function decodeImage(data){return new Promise((resolve,reject)=>{const im=new Image(),timer=setTimeout(()=>reject(new Error('图片解码超时')),12000);im.onload=()=>{clearTimeout(timer);if(im.width>10000||im.height>10000||im.width*im.height>50000000)return reject(new Error('图片尺寸过大，最长边 ≤10000、总像素 ≤5000万'));resolve({width:im.width,height:im.height});};im.onerror=()=>{clearTimeout(timer);reject(new Error('图片损坏或格式不支持'));};im.src=data;});}
async function readAudio(file){if(file.size>30*1024*1024)throw new Error('音频超过 30 MiB');const b=new Uint8Array(await file.slice(0,16).arrayBuffer()),head=String.fromCharCode(...b);let mime='';if(head.startsWith('RIFF')&&head.slice(8,12)==='WAVE')mime='audio/wav';else if(head.startsWith('OggS'))mime='audio/ogg';else if(head.startsWith('ID3')||(b[0]===255&&(b[1]&224)===224))mime='audio/mpeg';else if(head.slice(4,8)==='ftyp')mime='audio/mp4';else if(b[0]===26&&b[1]===69&&b[2]===223&&b[3]===163)mime='audio/webm';else throw new Error('音频文件头不受支持，请使用 WAV、MP3、OGG、M4A');return {data:await dataURL(new Blob([file],{type:mime})),name:file.name.slice(0,180),mime};}
function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportProject(include){const data={...clone(project),battle:include&&battle?battle.snapshot():null,exportedAt:new Date().toISOString(),instructions:'Imported images/audio embedded. Built-in sprites depend on the matching assets directory.'};download('遭遇演算_项目_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data));status('项目已导出；包含自定义素材'+(include?'及当前战局':'')+'。');}
function isPlain(x){return !!x&&typeof x==='object'&&!Array.isArray(x)&&Object.getPrototypeOf(x)===Object.prototype;}
function bounded(v,lo,hi){return typeof v==='number'&&Number.isFinite(v)&&v>=lo&&v<=hi;}
function assertPlain(x,name){if(!isPlain(x))throw new Error(name+'格式无效');for(const k of Object.keys(x))if(['__proto__','constructor','prototype'].includes(k))throw new Error('不允许的字段 '+k);}
async function validateProject(raw){assertPlain(raw,'项目');if(raw.schema!=='resonant-project-v1'||raw.version!==1||raw.assetSet!=='20261009-v1')throw new Error('项目版本不匹配');const p=freshProject();let bytes=0;for(const k of ['overrides','calibration','appearance','background','audio','settings','battleConfig'])assertPlain(raw[k],k);
 for(const [key,item] of Object.entries(raw.overrides)){if(!own(D.slots,key))throw new Error('未知素材槽 '+key);p.overrides[key]=await checkedMedia(item,'image');bytes+=p.overrides[key].data.length;}
 for(const [key,cal] of Object.entries(raw.calibration)){if(!own(D.slots,key))throw new Error('未知校准槽');assertPlain(cal,'校准');const ranges={scale:[.1,4],x:[-500,500],y:[-500,500],ground:[-200,300],bodyHeight:[20,3000],outline:[0,3],anchorX:[-1,2],anchorY:[-1,2],headX:[0,1],headY:[0,1],weaponX:[0,1],weaponY:[0,1],portraitX:[0,1],portraitY:[0,1],portraitW:[.01,1],portraitH:[.01,1]};const c={};for(const [k,v] of Object.entries(cal)){if(!own(ranges,k)||!bounded(v,...ranges[k]))throw new Error('校准参数超范围：'+k);c[k]=v;}p.calibration[key]=c;}
 for(const [key,value] of Object.entries(raw.appearance)){if(!own(P.characters,key)||!(own(D.forms[key]||{},value)||key==='rover'&&['male_default','male_school','female_default','female_school'].includes(value)))throw new Error('外观无效');p.appearance[key]=value;}
 const bg=raw.background;if(bg.data){const item=await checkedMedia(bg,'image');p.background={...p.background,...item};bytes+=item.data.length;}if(!['cover','contain'].includes(bg.fit)||!bounded(bg.opacity,0,1))throw new Error('背景参数无效');p.background.fit=bg.fit;p.background.opacity=bg.opacity;
 for(const [key,item] of Object.entries(raw.audio)){if(!own(AUDIO,key))throw new Error('音频事件未知');p.audio[key]=await checkedMedia(item,'audio');bytes+=p.audio[key].data.length;}
 if(bytes>130*1024*1024)throw new Error('嵌入素材总量过大');for(const k of ['master','sfx','bgm']){if(!bounded(raw.settings[k],0,1))throw new Error('音量无效');p.settings[k]=raw.settings[k];}if(!bounded(raw.settings.outline,0,3))throw new Error('描边无效');p.settings.outline=raw.settings.outline;for(const k of ['showAnchors','reducedMotion']){if(typeof raw.settings[k]!=='boolean')throw new Error('设置无效');p.settings[k]=raw.settings[k];}
 const test=new BattleEngine(P,raw.battleConfig);p.battleConfig=clone(test.options);let loaded=null,migration='';if(raw.battle){if(raw.battle.parameter_version!==P.schema_version){if(['0.1.2-candidate','0.2.0-candidate'].includes(raw.battle.parameter_version)&&raw.battle.schema==='battle-engine-v1')migration='旧版 '+raw.battle.parameter_version+' 战局与当前 '+P.schema_version+' AP规则不兼容。已保留素材、外观、校准和编队；旧战局不续接，按当前规则重新开场。';else throw new Error('战局参数版本不支持');}else loaded=BattleEngine.restore(P,raw.battle);}return {project:p,battle:loaded,migration};}
async function checkedMedia(item,kind){assertPlain(item,'素材');if(typeof item.name!=='string'||item.name.length>180||typeof item.data!=='string')throw new Error('素材字段无效');const re=kind==='image'?/^data:image\/(png|jpeg|webp|gif);base64,[A-Za-z0-9+/]*={0,2}$/:/^data:audio\/(wav|mpeg|ogg|mp4|webm);base64,[A-Za-z0-9+/]*={0,2}$/;if(!re.test(item.data)||item.data.length>(kind==='image'?28:42)*1024*1024)throw new Error('素材类型或大小不受支持');const comma=item.data.indexOf(','),mime=item.data.slice(5,comma-7),base64=item.data.slice(comma+1);let binary;try{binary=atob(base64);}catch{throw new Error('素材编码损坏');}const blob=new Blob([Uint8Array.from(binary,c=>c.charCodeAt(0))],{type:mime});const file=new File([blob],item.name,{type:mime});return kind==='image'?readImage(file):readAudio(file);}
const MENU_ROOT=[['battle','战斗'],['skills','技能'],['outro','延奏'],['negotiate','交涉'],['escape','逃跑']];
const PORTRAIT_RECTS={'amy.human':[157,20,155,155],'amy.mecha':[132,67,170,170],'lynae.normal':[37,15,150,150],'lynae.peppermint':[29,10,160,160],'mornye.normal':[135,47,150,150],'mornye.winter':[139,45,150,150],'denia.red':[116,44,150,150],'denia.blue':[91,15,145,145],'chisa.normal':[312,72,168,168],'chisa.peach':[327,54,188,188],snip:[93,169,175,175],predator:[65,15,235,235],bracer:[254,26,325,325],carapace:[487,298,398,398],crownless:[718,100,510,510]};
function actionCategory(s){if(['pry','encourage'].includes(s.key))return 'removed';if(['end','wait','guard','basic','heavy'].includes(s.key)||s.key.startsWith('item_')||['battle','items','defense'].includes(s.category))return 'battle';if(s.key==='retreat')return 'escape';if(['taunt','negotiate'].includes(s.key)||s.category==='negotiate')return 'negotiate';return 'skills';}
function resetMenu(){menuCategory='root';selection=null;targetId=null;inspectedAction=null;menuOpen=false;menuActorId=battle?.currentId||null;}
function openActorMenu(){if(busy||!battle||battle.result||battle.current?.side!=='ally'||selection)return;menuOpen=true;menuActorId=battle.currentId;renderActions();$('actionList').querySelector('button')?.focus({preventScroll:true});}
function closeActorMenu(focus=true){resetMenu();renderActions();if(focus&&!busy)$('actorTrigger').focus({preventScroll:true});}
function describeCategory(key){const text={battle:['战斗','选择普攻、重击、防御、道具或结束行动。普通 AP 可结转，最多 6 点；临时 AP 只在接收窗口有效。'],skills:['技能','使用当前角色的专属能力。AP 与角色资源分别结算，选择目标前可查看实际消耗和效果。'],outro:['延奏','当前角色协奏满 100，且本窗口完成过至少一个付费动作后，可向其他队友交接。接收者下一行动窗口获得 2 点临时 AP，不插队。'],negotiate:['交涉','战场战术交互。各项会说明实际效果、持续时间与限制。'],escape:['逃跑','撤离会按当前遭遇规则结算。选择后仍需确认。']};const t=text[key]||['行动','选择操作查看效果'];$('detailTitle').textContent=t[0];$('detailBody').innerHTML='<p>'+esc(t[1])+'</p>';}
function selectedAction(key=selection){if(!key)return null;if(key.startsWith('__concerto:')){const c=battle.availableConcertos().find(x=>x.actor===key.slice(11));return c?{...c,key,name:'延奏 · '+battle.getUnit(c.actor).name,apCost:0}:null;}return battle.availableActions().find(x=>x.key===key);}
function inspectAction(key){inspectedAction=key;const s=selectedAction(key);if(!s)return;
 if(key.startsWith('__concerto:')){$('detailTitle').textContent=s.name;$('detailBody').innerHTML=`<p>${esc(s.effectSummary||'消耗个人 100 点协奏并结束自己的行动窗口；接收者下次正常行动获得 2 点临时 AP。')}</p><dl><dt>消耗</dt><dd>100 协奏；不消耗普通 AP</dd><dt>接收</dt><dd>2 临时 AP；不改变速度顺序</dd><dt>限制</dt><dd>当前角色本窗口已完成付费动作；不能交给自己或已有待接续的队友。</dd></dl><p class="detail-reason ${s.enabled?'':'blocked'}">${esc(s.reason||'选择接收者后确认。')}</p>`;return;}
 const cost=Object.entries(s.cost||{}).map(([k,v])=>(LABEL[k]||k)+' '+v).join(' / ')||'无',gain=Object.entries(s.gain||{}).map(([k,v])=>(LABEL[k]||k)+' +'+v).join(' / ')||'无';
 const target=s.targetText||(s.aoe?'全部敌方':({self:'自己',ally:'一名队友',other_ally:'另一名队友',all_allies:'全体队友'})[s.target]||'一名敌人');
 const desc=(typeof s.description==='string'?s.description:s.effectSummary||'按当前资源、形态与目标结算。')+(key==='taunt'?' 1 AP，本窗口一次；只能在敌方尚未瞄准/蓄力锁定前施放。下一次实际造成伤害的单体攻击改向施放者，并增加15%伤害，随后消费。群攻不改目标、不增加这15%、不消费。最长至施放后第2轮末；施放者倒地或撤离时清除。':'');let extra='';if((s.coef>0||s.part_coefficient)&&s.damagePreview?.length)extra+=`<dt>实际预测</dt><dd>${s.damagePreview.map(d=>esc((battle.getUnit(d.target)?.name||'目标')+'：'+(d.immune?'免疫':d.amount+' '+(LABEL[d.element]||d.element||'')+'伤害')+(d.part?' / 仅部件、不伤主体':'')+' / 共振 '+(d.resonance??0))).join('<br>')}</dd>`;if(s.healingPreview)extra+=`<dt>当前回复</dt><dd>预计 ${s.healingPreview.amount} 生命/人；裂伤时 ×0.75，实际不超过缺失生命，不复活。</dd>`;
 if(s.barrier)extra+=`<dt>护盾</dt><dd>${s.barrier} 点；同类取较高，不叠加。</dd>`;
 $('detailTitle').textContent=s.name;$('detailBody').innerHTML=`<p>${esc(desc)}</p><dl><dt>行动点</dt><dd>${s.apCost??s.ap_cost??1} AP${s.oncePerWindow?' · 每窗口一次':''}</dd><dt>目标</dt><dd>${esc(target)}</dd><dt>角色资源</dt><dd>${esc(cost)} / ${esc(gain)}</dd>${s.coef>0?`<dt>伤害 / 共振</dt><dd>伤害倍率 ${Number(s.coef).toFixed(2)}；共振伤害 ${s.resonanceDamage??s.resonance_damage??s.break_points??0}。</dd>`:''}${extra}<dt>协奏收益</dt><dd>${s.concertoGain??s.concerto??0} 点；受每轮上限限制。</dd>${s.durationText?`<dt>持续</dt><dd>${esc(s.durationText)}</dd>`:''}${s.cooldownText?`<dt>冷却</dt><dd>${esc(s.cooldownText)}</dd>`:''}</dl><p class="detail-reason ${s.enabled?'':'blocked'}">${esc(s.reason||'可使用；选中与取消均不会消耗。')}</p>`;
}
function menuButton(key,label,enabled,reason,meta=''){return `<button class="menu-action" data-action="${esc(key)}" aria-disabled="${!enabled}" ${busy?'disabled':''}><span>${esc(label)}</span><small>${esc(meta)}</small>${!enabled?'<span class="menu-lock" aria-hidden="true">◇</span>':''}</button>`;}
function bindMenuButtons(){for(const b of $('actionList').querySelectorAll('[data-action]')){b.onclick=()=>selectAction(b.dataset.action);b.onmouseenter=()=>inspectAction(b.dataset.action);b.onfocus=()=>inspectAction(b.dataset.action);}for(const b of $('actionList').querySelectorAll('[data-category]')){b.onclick=()=>openCategory(b.dataset.category);b.onmouseenter=()=>describeCategory(b.dataset.category);b.onfocus=()=>describeCategory(b.dataset.category);}}
function openCategory(key){if(busy||!menuOpen||battle?.current?.side!=='ally')return;selection=null;targetId=null;menuCategory=key;renderActions();describeCategory(key);$('actionList').querySelector('button')?.focus({preventScroll:true});}
function renderActions(){const a=battle.current,player=a?.side==='ally'&&!battle.result&&!busy;if(menuActorId!==battle.currentId)resetMenu();
 $('currentActor').textContent=a?.name||'—';$('turnCaption').textContent=busy?'RESOLVING':a?.side==='enemy'?'ENEMY TURN':'PLAYER TURN';$('actorAP').innerHTML=player?apMeter(a,true):'';
 $('commandPanel').classList.toggle('hidden',!player||!menuOpen||!!selection);$('actionDetail').classList.toggle('hidden',!player||!menuOpen||!!selection);$('targetArea').classList.toggle('hidden',!player||!selection);$('stage').classList.toggle('focus-mode',player&&menuOpen&&!selection);$('actorPrompt').classList.toggle('hidden',!player||menuOpen||!!selection);$('actorPrompt').textContent=player?a.name+' 的行动窗口 · 点击角色或按 Enter':' ';$('actorTrigger').classList.toggle('hidden',!player||!!selection);
 $('stepBtn').disabled=busy||!!battle.result||anyModal();$('autoBtn').disabled=busy||!!battle.result;$('autoBtn').setAttribute('aria-pressed',String(auto));$('autoBtn').textContent='自动演算：'+(auto?'开':'关');$('menuBackBtn').classList.toggle('hidden',menuCategory==='root');$('concertoList').classList.add('hidden');
 if(!player){$('actionList').innerHTML='';$('targetList').innerHTML='';$('confirmBtn').disabled=true;return;}
 if(!busy&&!selection)$('actionBanner').textContent=a.name+' · 普通 AP '+(a.ap??0)+' / 6 · 临时 '+(a.temp_ap??0)+' / 2';
 const actions=battle.availableActions();if(!selection){if(menuCategory==='root'){$('actionList').innerHTML=MENU_ROOT.map(([key,label])=>`<button class="root-option" data-category="${key}"><span>${label}</span><small>${key==='outro'&&battle.availableConcertos().some(c=>c.enabled)?'就绪':'›'}</small></button>`).join('');}else if(menuCategory==='outro'){$('actionList').innerHTML=battle.availableConcertos().map(c=>{const u=battle.getUnit(c.actor);return menuButton('__concerto:'+c.actor,u.name+' · 延奏',c.enabled,c.reason,u.concerto+'/100');}).join('');}else{$('actionList').innerHTML=actions.filter(s=>actionCategory(s)===menuCategory).map(s=>menuButton(s.key,s.name,s.enabled,s.reason,(s.apCost??s.ap_cost??1)+' AP'+(s.inventoryCount!=null?' · 余 '+s.inventoryCount:''))).join('');}if(!$('actionList').innerHTML)$('actionList').innerHTML='<p class="menu-empty">当前没有可选动作。</p>';}
 bindMenuButtons();renderTargets();if(!selection){if(inspectedAction&&selectedAction(inspectedAction))inspectAction(inspectedAction);else describeCategory(menuCategory==='root'?'battle':menuCategory);}$('menuFoot').textContent='↑↓选择 · Enter进入 · Esc返回';renderTacticalNotice();positionOverlays();
}
function selectAction(key){if(busy||!menuOpen||selection||battle.current?.side!=='ally')return;const s=selectedAction(key);if(!s)return;inspectAction(key);if(!s.enabled){toast(s.reason||'此行动暂不可用');return;}selection=key;const targets=s.targets?.length?s.targets:[battle.currentId];targetId=targets[0]||null;confirmLockUntil=performance.now()+180;playAudio('select');renderActions();$('targetList').querySelector('.selected')?.focus({preventScroll:true});}
function renderTargets(){if(!selection){$('targetList').innerHTML='';$('previewText').textContent='';return;}const s=selectedAction();if(!s){resetMenu();renderActions();return;}const ids=s.targets?.length?s.targets:[battle.currentId];if(!ids.includes(targetId))targetId=ids[0]||null;
 $('selectionHint').textContent=s.name+' · '+(s.aoe?'确认全部敌方':s.target==='all_allies'?'确认全体队友':'选择目标');$('targetList').innerHTML=ids.map(id=>{const u=battle.getUnit(id);return `<button class="target-btn ${id===targetId?'selected':''}" data-target="${esc(id)}" aria-pressed="${id===targetId}"><span>${esc(u.name)}</span><small>${u.side==='enemy'?(u.rank==='common'?'HP '+u.hp:'共振 '+u.shield):'HP '+u.hp+'/'+u.maxhp}</small></button>`;}).join('');
 for(const b of $('targetList').querySelectorAll('button'))b.onclick=()=>chooseTarget(b.dataset.target,true);$('confirmBtn').disabled=busy||!targetId;const t=battle.getUnit(targetId);const forecast=(s.coef>0||s.part_coefficient)?s.damagePreview?.find(d=>d.target===targetId):null;$('previewText').textContent=t?(s.aoe?'将作用于全部目标':t.name)+' · '+(s.apCost??s.ap_cost??0)+' AP'+(forecast?' · '+(forecast.immune?'目标免疫':forecast.amount+' '+(LABEL[forecast.element]||forecast.element||'')+'伤害')+(forecast.part?' · 仅部件、不伤主体':' · 共振 '+(forecast.resonance??0)):' · 确认后结算'):'';
}
function chooseTarget(id,focus=false){if(busy||!selection)return;const s=selectedAction(),ids=s?.targets?.length?s.targets:[battle.currentId];if(!ids.includes(id))return;targetId=id;playAudio('select');renderTargets();if(focus)$('targetList').querySelector('.selected')?.focus({preventScroll:true});}
function confirmSelection(){if(busy||!selection||!targetId||performance.now()<confirmLockUntil)return;const key=selection,target=targetId,s=selectedAction();if(!s?.enabled){toast(s?.reason||'行动已不可用');return;}confirmLockUntil=performance.now()+300;playAudio('confirm');execute(()=>key.startsWith('__concerto:')?battle.concerto(key.slice(11),target):key==='wait'?battle.wait():battle.act(key,target));}
function backMenu(){if(busy)return;if(selection){selection=null;targetId=null;menuOpen=true;}else if(menuCategory!=='root')menuCategory='root';else{closeActorMenu();return;}inspectedAction=null;renderActions();$('actionList').querySelector('button')?.focus({preventScroll:true});}

function renderQueue(){const current=battle.current;const portraits=(ids,kind)=>ids.map(id=>{const u=battle.getUnit(id);if(!u||u.hp<=0||u.retreated)return'';const skipped=u.side==='enemy'&&u.broken_until>0&&u.broken_until>=(kind==='next'?battle.round+1:battle.round);const label=u.name+' · '+(kind==='next'?'预计下一轮':'本轮')+(skipped?' · 共振击破跳过':'');return `<button class="portrait-token ${u.side} ${skipped?'will-skip':''}" data-portrait-unit="${esc(id)}" aria-label="${esc(label)}" title="${esc(label)}"><canvas aria-hidden="true"></canvas>${skipped?'<span class="skip-label">跳过</span>':''}</button>`;}).join('');$('currentPortrait').innerHTML=current?portraits([current.id],'current'):'';$('queue').innerHTML=portraits(battle.queue,'remaining');const prediction=typeof battle.queuePreview==='function'?battle.queuePreview():null;let next=prediction?.nextPreview?.ids||prediction?.next||prediction?.nextRound;if(Array.isArray(next))next=next.map(v=>typeof v==='string'?v:v.id);else next=battle.living('ally').concat(battle.living('enemy')).sort((a,b)=>b.speed-a.speed||(a.side===b.side?0:a.side==='ally'?-1:1)||a.slot-b.slot).map(u=>u.id);$('nextQueue').innerHTML=battle.result?'':portraits(next,'next');$('queueNote').textContent=busy?'结算中':battle.result?'已结束':'';drawPortraits();}
function drawPortraits(){for(const button of document.querySelectorAll('[data-portrait-unit]')){const u=battle.getUnit(button.dataset.portraitUnit),canvas=button.querySelector('canvas');if(!u||!canvas)continue;const key=slotFor(u,'idle'),s=D.slots[key],rec=getImage(sourceFor(key));if(!s||!rec?.ready){canvas.width=64;canvas.height=64;const cx=canvas.getContext('2d');cx.fillStyle='#24383e';cx.fillRect(0,0,64,64);cx.fillStyle='#aebdb1';cx.textAlign='center';cx.font='28px serif';cx.fillText('◇',32,35);cx.font='9px sans-serif';cx.fillText(!s||s.pending?'待绘':rec?.error?'缺图':'载入',32,53);continue;}const base=s.portraitRect||PORTRAIT_RECTS[s.entity+'.'+s.form]||PORTRAIT_RECTS[s.entity]||[0,0,s.width,s.height];const iw=rec.img.naturalWidth,ih=rec.img.naturalHeight,sx=iw/s.width,sy=ih/s.height;const c=calibration(key),custom=project.calibration[key];const rect=custom&&Number.isFinite(custom.portraitW)?[c.portraitX*iw,c.portraitY*ih,c.portraitW*iw,c.portraitH*ih]:[base[0]*sx,base[1]*sy,base[2]*sx,base[3]*sy];canvas.width=64;canvas.height=64;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,64,64);ctx.imageSmoothingEnabled=false;ctx.drawImage(rec.img,...rect,0,0,64,64);}}
function positionOverlays(){if(!battle?.current||!menuOpen||selection||busy)return;const stage=$('stage'),W=stage.clientWidth,H=stage.clientHeight;if(!W||!H)return;
 const menu=$('commandPanel'),detail=$('actionDetail'),p=scenePositions(W,H).find(p=>p.id===battle.currentId);if(!p)return;
 const mw=menu.offsetWidth||184,mh=Math.min(menu.offsetHeight||260,H-24),dw=Math.min(W<650?220:290,W-24),dh=Math.min(detail.offsetHeight||250,H-24),gap=12;
 // Keep commands on the ally's rear/right and details in the safe lower-left lane.
 const x=W<620?12:(p.x+50+mw<W-12?p.x+50:Math.max(12,p.x-mw-50)),y=W<620?12:Math.max(12,Math.min(H-mh-12,p.y-90));menu.style.left=Math.round(x)+'px';menu.style.top=Math.round(y)+'px';menu.style.maxHeight=Math.max(150,W<620?H-124:H-24)+'px';menu.dataset.anchorUnit=battle.currentId;
 if(W<620){detail.style.left='10px';detail.style.top='auto';detail.style.bottom='10px';detail.style.width=(W-20)+'px';detail.style.maxHeight='98px';}
 else {const actorBounds=stageBounds.find(b=>b.id===battle.currentId),actorLeft=actorBounds?actorBounds.left+p.x-actorBounds.x:p.x-42,dx=Math.max(12,Math.min(x-dw-gap,W*.17,actorLeft-dw-gap));detail.style.left=Math.round(dx)+'px';detail.style.top=Math.round(Math.max(12,H-dh-18))+'px';detail.style.bottom='auto';detail.style.width=dw+'px';detail.style.maxHeight=Math.max(120,H*.58)+'px';}
}

function showHistory(){const entries=window.RELEASE_NOTES?.entries||[];$('historyContent').innerHTML=entries.map(e=>`<h3>${esc(e.version)} · ${esc(e.stage)}</h3><p>${esc(e.summary||'本次反馈与改动进展')}</p>${e.requested?'<ol>'+e.requested.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol>':''}${e.decisions?'<p>'+e.decisions.map(esc).join('；')+'</p>':''}${e.validation?'<p>验证：'+esc(JSON.stringify(e.validation))+'</p>':''}${e.limitations?'<p>未验/限制：'+e.limitations.map(esc).join('；')+'</p>':''}`).join('');modalOpen('historyDialog');}

function showMigration(text){$('migrationNotice').textContent=text;$('migrationNotice').classList.remove('hidden');}
function renderTacticalNotice(){const charged=battle.living('enemy').map(e=>({e,intent:battle.enemyIntent(e.id)})).filter(x=>x.intent&&!x.intent.hidden);const text=charged.map(x=>'危险 · '+x.e.name+' / '+x.intent.name+'：'+(x.intent.counterplayText||'')).join(' · ');$('tacticalNotice').textContent=text;$('tacticalNotice').classList.toggle('hidden',!text||!!battle.result||menuOpen||!!selection);}

function wire(){$('assetsBtn').onclick=()=>{modalOpen('assetDialog');renderAssetPanel();};$('setupBtn').onclick=()=>{renderSetup();modalOpen('setupDialog');};$('helpBtn').onclick=()=>modalOpen('helpDialog');$('historyBtn').onclick=showHistory;$('menuBackBtn').onclick=backMenu;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modalClose(b.dataset.close));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(battle)renderActions();schedule();}));$('startBtn').onclick=()=>safeAction(startFromSetup);$('difficultySelect').onchange=()=>{$('difficultyDescription').textContent=P.difficulties[$('difficultySelect').value]?.description||'';};$('encounterSelect').onchange=()=>$('customEnemies').classList.toggle('hidden',$('encounterSelect').value!=='custom');$('hpInput').oninput=e=>$('hpOutput').textContent=e.target.value+'%';$('confirmBtn').onclick=confirmSelection;$('cancelBtn').onclick=backMenu;$('stepBtn').onclick=()=>execute(()=>battle.current?.side==='enemy'?battle.stepEnemy():battle.autoAction());$('autoBtn').onclick=()=>{auto=!auto;$('autoBtn').textContent='自动演算：'+(auto?'开':'关');$('autoBtn').setAttribute('aria-pressed',String(auto));schedule();};$('restartBtn').onclick=()=>{if(!window.confirm('重开当前遭遇？本场行动将清空。'))return;startBattle();};$('saveBtn').onclick=()=>saveBattle();$('resumeBtn').onclick=()=>safeAction(async()=>{const data=await store.get('battle')||savedSnapshot;if(!data){toast('还没有可读取的战局');return;}const loaded=BattleEngine.restore(P,data);pause();epoch++;battle=loaded;project.battleConfig=clone(loaded.options);busy=false;auto=false;resetMenu();visuals.clear();floats=[];stageEffects=[];render();schedule();toast('战局已读取');});$('exportLogBtn').onclick=()=>download('遭遇演算_战斗日志.json',JSON.stringify({parameterVersion:P.schema_version,options:battle.options,summary:battle.summary(),log:battle.log},null,2));$('muteBtn').onclick=toggleMute;$('speedSelect').onchange=schedule;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{assetTab=b.dataset.tab;renderAssetPanel();});$('actorTrigger').onclick=()=>menuOpen?closeActorMenu():openActorMenu();$('battleCanvas').onclick=e=>{if(busy)return;const r=e.target.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const hit=[...stageBounds].reverse().find(b=>x>=b.left&&x<=b.left+b.width&&y>=b.top&&y<=b.top+b.height);if(selection){if(hit)chooseTarget(hit.id,true);else closeActorMenu(false);return;}if(hit?.id===battle.currentId&&battle.current?.side==='ally'){menuOpen?closeActorMenu():openActorMenu();return;}if(menuOpen)closeActorMenu(false);};
 document.addEventListener('keydown',e=>{if(anyModal()||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;
  if(e.key==='Escape'){if(menuOpen||selection){backMenu();e.preventDefault();}return;}
  if(busy){if(['Enter',' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)&&$('stage').contains(document.activeElement))e.preventDefault();return;}
  if(e.repeat&&['Enter',' '].includes(e.key)){e.preventDefault();return;}
  if(selection){if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){const s=selectedAction(),ids=s?.targets?.length?s.targets:[battle.currentId],at=ids.indexOf(targetId),move=['ArrowDown','ArrowRight'].includes(e.key)?1:-1;chooseTarget(ids[(at+move+ids.length)%ids.length],true);e.preventDefault();return;}if(e.key==='Enter'&&($('stage').contains(document.activeElement)||document.activeElement===document.body)){e.preventDefault();if(document.activeElement===$('cancelBtn'))backMenu();else confirmSelection();return;}}
  const menu=$('commandPanel');if(menuOpen&&menu.contains(document.activeElement)){if(['ArrowDown','ArrowUp'].includes(e.key)){const buttons=[...$('actionList').querySelectorAll('button:not(:disabled)')],at=buttons.indexOf(document.activeElement),move=e.key==='ArrowDown'?1:-1;buttons[(at+move+buttons.length)%buttons.length]?.focus({preventScroll:true});e.preventDefault();return;}if(e.key==='ArrowLeft'){backMenu();e.preventDefault();return;}if(e.key==='Enter'||e.key==='ArrowRight'&&document.activeElement.dataset.category){e.preventDefault();document.activeElement.click();return;}}
  if(!menuOpen&&!selection&&battle.current?.side==='ally'&&e.key==='Enter'&&(document.activeElement===document.body||document.activeElement===$('actorTrigger')||document.activeElement===$('battleCanvas'))){e.preventDefault();openActorMenu();}
 });
 document.addEventListener('mouseover',e=>showStatusTooltip(e.target.closest('[data-tooltip]')));document.addEventListener('focusin',e=>showStatusTooltip(e.target.closest('[data-tooltip]')));document.addEventListener('mouseout',e=>{if(e.target.closest('[data-tooltip]'))$('statusTooltip').classList.add('hidden');});document.addEventListener('focusout',e=>{if(e.target.closest('[data-tooltip]'))$('statusTooltip').classList.add('hidden');});
 window.addEventListener('beforeunload',()=>{if(battle&&!busy)store.set('battle',battle.snapshot()).catch(()=>{});});}
function showStatusTooltip(el){const box=$('statusTooltip');if(!el){box.classList.add('hidden');return;}box.textContent=el.dataset.tooltip;box.classList.remove('hidden');const r=el.getBoundingClientRect(),w=Math.min(320,window.innerWidth-24);box.style.width=w+'px';box.style.left=Math.max(12,Math.min(window.innerWidth-w-12,r.right-w))+'px';box.style.top=Math.max(12,Math.min(window.innerHeight-box.offsetHeight-12,r.bottom+7))+'px';}
async function init(){if(!P||!window.BattleEngine)throw new Error('程序文件缺失，请完整解压，确保 parameters.js、engine.js 与 index.html 同目录。');wire();await store.init();try{const saved=await store.get('project');if(saved){const checked=await validateProject(saved);project=checked.project;}}catch(e){toast('上次项目无法恢复，已使用默认设置：'+e.message);}savedSnapshot=await store.get('battle');if(savedSnapshot){try{battle=BattleEngine.restore(P,savedSnapshot);project.battleConfig=clone(battle.options);render();schedule();}catch(e){await store.set('previousVersionBattle',savedSnapshot);showMigration('旧战局未载入：'+e.message+'。素材与校准保留，旧战局已另存本机备份；当前为新规则开场。');startBattle(project.battleConfig,false);}}else startBattle(project.battleConfig);$('saveStatus').textContent=store.available?'素材已保存在本浏览器 · 战局可导出':'浏览器阻止本地缓存 · 请导出项目';$('sceneLabel').textContent=project.background.data?'本地背景 · '+project.background.name:'中性调试舞台 · 等待背景素材';for(const key of Object.keys(D.slots))getImage(sourceFor(key));requestAnimationFrame(drawStage);}
// Read-only UI diagnostics: no credential, network, or gameplay mutation API.
window.BattleLabDiagnostics={getSnapshot:()=>battle?clone(battle.snapshot()):null,getProject:()=>clone(project),getQueue:()=>battle?.queuePreview?.()||null,getOverlayLayout:()=>({stage:{width:$('stage').clientWidth,height:$('stage').clientHeight},menu:{left:$('commandPanel').style.left,top:$('commandPanel').style.top,anchor:$('commandPanel').dataset.anchorUnit},detail:{left:$('actionDetail').style.left,top:$('actionDetail').style.top}}),getStageLayout:()=>({positions:scenePositions($('stage').clientWidth,$('stage').clientHeight),bounds:clone(stageBounds),effects:clone(stageEffects)}),getState:()=>({menuOpen,menuActorId,menuCategory,inspectedAction,round:battle?.round,current:battle?.currentId,result:clone(battle?.result||null),busy,selected:selection,targetId,assetCount:Object.values(D.slots).filter(s=>s.src).length,pendingAssetCount:Object.values(D.slots).filter(s=>s.pending).length,overrideCount:Object.keys(project.overrides).length,background:project.background.name,storage:store.available}),validateProject,assets:D};
init().catch(e=>{console.error(e);$('app').innerHTML='<div class="build-error"><h2>程序未能启动</h2><p>'+esc(e.message)+'</p><p>请完整解压后重新打开 index.html。</p></div>';});
})();
