'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');const {IDBFactory}=require('fake-indexeddb');const {boot,saveRecords,settle,sha,ROOT,fixtures}=require('./dom_harness.cjs');
const testedHashes=Object.fromEntries(['app.js','engine.js','parameters.js','storage.js','index.html','style.css'].map(f=>[f,sha(f)]));
const results=[],fights=[],clone=x=>JSON.parse(JSON.stringify(x));const state=h=>clone(h.w.BattleLabDiagnostics.getSnapshot()),project=h=>clone(h.w.BattleLabDiagnostics.getProject()),textState=h=>JSON.stringify(state(h));
const engine=h=>h.w.BattleEngine.restore(h.w.BATTLE_PARAMETERS,h.w.BattleLabDiagnostics.getSnapshot());
const categories=['battle','skills','defense','items','negotiate','escape'];
function key(h,key){h.w.document.activeElement.dispatchEvent(new h.w.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));}
function root(h){let n=0;while((h.diag().selected||h.diag().menuCategory!=='root')&&n++<4)h.click('#menuBackBtn');assert.strictEqual(h.diag().menuCategory,'root');}
function choose(h,key){root(h);if(key.startsWith('__concerto:'))h.click('[data-category=skills]');else{const a=engine(h).availableActions().find(a=>a.key===key);assert(a,'missing action '+key);h.click('[data-category='+a.category+']');}if(h.diag().selected!==key){const el=h.$('[data-action="'+key+'"]');assert(el,'missing DOM '+key);el.click();}}
async function act(h,key,target){const old=textState(h);choose(h,key);assert.strictEqual(textState(h),old,'select must not act');assert.strictEqual(h.diag().selected,key);const t=target?h.$('[data-target="'+target+'"]'):h.$('[data-target]');assert(t,'missing target');t.click();h.click('#confirmBtn');await settle(h);assert.notStrictEqual(textState(h),old);}
async function setup(h,enc='boss',team=['amy','lynae','mornye','denia'],difficulty='standard'){h.click('#setupBtn');for(const n of h.w.document.querySelectorAll('#teamChoices input[type=checkbox]'))n.checked=team.includes(n.value);h.change('#encounterSelect',enc);h.change('#difficultySelect',difficulty);h.click('#startBtn');await settle(h);}
async function readRecord(h,key){const db=await new Promise((r,j)=>{const q=h.db.open('resonant-encounter-lab-v1',1);q.onsuccess=()=>r(q.result);q.onerror=j});const out=await new Promise((r,j)=>{const q=db.transaction('records').objectStore('records').get(key);q.onsuccess=()=>r(q.result);q.onerror=j});db.close();return out;}
async function preload(db,records){const d=await new Promise((r,j)=>{const q=db.open('resonant-encounter-lab-v1',1);q.onupgradeneeded=()=>q.result.createObjectStore('records');q.onsuccess=()=>r(q.result);q.onerror=j});await new Promise((r,j)=>{const tx=d.transaction('records','readwrite');for(const [k,v] of Object.entries(records))tx.objectStore('records').put(v,k);tx.oncomplete=r;tx.onerror=j});d.close();}
async function fight(enc,difficulty='standard',speed='4',manual=true){const h=await boot();await setup(h,enc,undefined,difficulty);h.change('#speedSelect',speed);let n=0,ready=0,manualCount=0,seenCharges=0,chosen=[];while(!h.diag().result&&state(h).state.round<=60){await settle(h);if(h.diag().result)break;let b=engine(h);if(h.$('#tacticalNotice').textContent.includes('破防')&&!h.$('#tacticalNotice').classList.contains('hidden'))seenCharges++;const cs=b.availableConcertos().filter(c=>c.enabled);if(cs.length){ready++;if(manual){const c=cs[0],t=c.targets.map(id=>b.getUnit(id)).sort((a,z)=>(z.acted_round!==b.round)-(a.acted_round!==b.round)||z.atk-a.atk)[0];const before=state(h).state;await act(h,'__concerto:'+c.actor,t.id);const after=state(h).state;assert.strictEqual(after._currentId,before._currentId);assert.deepStrictEqual(after.queue,before.queue);assert.deepStrictEqual(after.allies.map(a=>a.normal_count),before.allies.map(a=>a.normal_count));manualCount++;b=engine(h);}}
 const [k,t]=b._choose(b.current);chosen.push({actor:b.currentId,key:k,target:t.id});await act(h,k,t.id);assert(++n<260,'fight timeout');}
 const out={enc,difficulty,speed,steps:n,readyWindows:ready,manualCount,seenCharges,result:clone(h.diag().result),chosen,state:state(h)};assert(out.result,'no terminal result');assert(!h.errors.length,h.errors);h.draws.length=0;await h.frame(3000);out.finalDraws=h.draws.filter(d=>d.canvas==='battleCanvas');h.close();return out;}
(async()=>{async function test(name,fn){try{const d=await fn();results.push({name,pass:true,detail:d??null});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL '+name+': '+e.message)}}
await test('Six roots live inside stage; no old bottom command panel',async()=>{const h=await boot();assert(h.$('#stage').contains(h.$('#commandPanel')));assert(!h.$('.command-panel'));assert.deepStrictEqual([...h.w.document.querySelectorAll('[data-category]')].map(x=>x.dataset.category),categories);assert.deepStrictEqual([...h.w.document.querySelectorAll('[data-category] span')].map(x=>x.textContent),['战斗','技能','防御','道具','交涉','逃跑']);assert(!h.errors.length,h.errors);h.close();});
await test('All six categories have real actions or precise disabled reasons',async()=>{const h=await boot(),before=textState(h),rows=[];for(const c of categories){root(h);h.click('[data-category='+c+']');if(['defense','escape'].includes(c)){assert(h.diag().selected);rows.push({category:c,selection:h.diag().selected});}else{const nodes=[...h.w.document.querySelectorAll('[data-action]')];assert(nodes.length,c+' empty');for(const node of nodes){node.focus();assert(h.$('#detailBody').textContent.trim().length>25);if(node.getAttribute('aria-disabled')==='true'){const selected=h.diag().selected;node.click();assert.strictEqual(h.diag().selected,selected);assert(h.$('.detail-reason').textContent.trim());}}rows.push({category:c,actions:nodes.map(x=>x.dataset.action)});}assert.strictEqual(textState(h),before);}h.close();return rows;});
await test('Hover, focus, category browsing and cancel are read-only; disabled actions remain focusable',async()=>{const h=await boot();h.click('[data-category=skills]');const before=textState(h),node=h.$('[data-action=spectrum]');assert(node);assert.strictEqual(node.getAttribute('aria-disabled'),'true');assert(!node.disabled);node.focus();assert.strictEqual(h.w.document.activeElement,node);assert.strictEqual(h.$('#detailTitle').textContent,engine(h).getSkill(engine(h).current,'spectrum').name);node.dispatchEvent(new h.w.MouseEvent('mouseenter'));node.click();assert.strictEqual(h.diag().selected,null);assert.strictEqual(textState(h),before);root(h);choose(h,'basic');h.click('#cancelBtn');assert.strictEqual(textState(h),before);h.close();});
await test('Action description matches current parameters, target, cost, gain and duration',async()=>{const h=await boot();for(const team of [['amy'],['lynae'],['mornye'],['denia'],['chisa']]){await setup(h,'boss',team);const b=engine(h);for(const a of b.availableActions()){root(h);h.click('[data-category='+a.category+']');const node=h.$('[data-action="'+a.key+'"]');if(node)node.focus();const body=h.$('#detailBody').textContent;assert(body.includes(a.effectSummary),a.key+' missing summary');assert(body.includes(a.targetText),a.key+' target');assert(body.includes(a.durationText),a.key+' duration');for(const v of Object.values(a.cost||{}))assert(body.includes(String(v)),a.key+' cost');}}h.close();});
await test('Current, remaining and predicted queues use only canvas portraits and exact IDs',async()=>{const h=await boot();const b=engine(h),ids=sel=>[...h.w.document.querySelectorAll(sel+' [data-portrait-unit]')].map(x=>x.dataset.portraitUnit);assert.deepStrictEqual(ids('#currentPortrait'),[b.currentId]);assert.deepStrictEqual(ids('#queue'),clone(b.queue));assert.deepStrictEqual(ids('#nextQueue'),clone(b.queuePreview().nextPreview.ids));assert(!ids('#queue').includes(b.currentId));for(const n of h.w.document.querySelectorAll('[data-portrait-unit]')){assert(n.querySelector('canvas'));assert(!/速度|琳奈|爱弥斯|咔嚓嚓/.test(n.textContent));assert(n.getAttribute('aria-label'));}assert(h.$('#nextQueue').parentElement.textContent.includes('预计'));h.close();});
await test('Wait updates current/remaining once and portraits never duplicate a normal token',async()=>{const h=await boot();const b=engine(h),id=b.currentId,oldNormal=b.current.normal_count;await act(h,'wait',id);const s=state(h).state;assert.strictEqual(s.allies.find(a=>a.id===id).normal_count,oldNormal);const ids=[...h.w.document.querySelectorAll('#currentPortrait [data-portrait-unit],#queue [data-portrait-unit]')].map(x=>x.dataset.portraitUnit);assert.strictEqual(ids.filter(x=>x===id).length,1);h.close();});
await test('Keyboard focus/arrows do not act; Enter on non-confirm focus does not execute old choice',async()=>{const h=await boot();h.$('[data-category=battle]').focus();const before=textState(h);key(h,'ArrowDown');assert.strictEqual(h.w.document.activeElement.dataset.category,'skills');key(h,'ArrowRight');assert.strictEqual(h.diag().menuCategory,'skills');key(h,'Escape');assert.strictEqual(h.diag().menuCategory,'root');choose(h,'basic');h.click('[data-target]');h.$('#cancelBtn').focus();key(h,'Enter');assert.strictEqual(textState(h),before);key(h,'Escape');assert.strictEqual(h.diag().selected,null);assert.strictEqual(textState(h),before);h.close();return 'Synthetic DOM keyboard events; native Tab/Enter default behavior requires real browser';});
await test('Repeated confirmation resolves exactly once',async()=>{const h=await boot();choose(h,'basic');h.click('[data-target]');const actor=state(h).state._currentId;for(let i=0;i<4;i++)h.click('#confirmBtn');await settle(h);assert.strictEqual(state(h).state.log.filter(e=>e.event==='action'&&e.actor===actor).length,1);assert.strictEqual(state(h).state.allies.find(a=>a.id===actor).normal_count,1);h.close();});
await test('Restart during animation discards stale completion and resets menu/resources',async()=>{const h=await boot();choose(h,'basic');h.click('[data-target]');h.click('#confirmBtn');assert(h.diag().busy);h.click('#restartBtn');for(let i=0;i<5;i++)await h.next();assert.strictEqual(h.diag().round,1);assert.strictEqual(h.diag().menuCategory,'root');assert.strictEqual(h.diag().selected,null);assert(!h.diag().busy);assert(!state(h).state.log.some(e=>e.event==='action'));assert(state(h).state.allies.every(a=>a.concerto===0&&Object.values(a.rsc).every(x=>x===0)));h.close();});
await test('Difficulty editing/cancel does not alter active battle; chosen new difficulty persists on restart/load',async()=>{const h=await boot(),before=textState(h);h.click('#setupBtn');h.change('#difficultySelect','challenge');assert.strictEqual(textState(h),before);h.click('[data-close=setupDialog]');assert.strictEqual(textState(h),before);await setup(h,'boss',undefined,'challenge');assert.strictEqual(state(h).state.options.difficulty,'challenge');assert(h.$('#difficultyBadge').textContent.includes(h.w.BATTLE_PARAMETERS.difficulties.challenge.name));await act(h,'basic');h.click('#saveBtn');await h.tick();h.click('#restartBtn');assert.strictEqual(state(h).state.options.difficulty,'challenge');h.click('#resumeBtn');await h.tick();assert.strictEqual(state(h).state.options.difficulty,'challenge');h.close();});
await test('Manual defense, finite item and retreat execute via their distinct menus',async()=>{const h=await boot();await setup(h,'boss',['lynae']);await act(h,'guard');const afterGuard=state(h).state;assert(afterGuard.log.some(e=>e.event==='action'&&e.skill==='guard'));const b=engine(h),item=b.availableActions().find(a=>a.category==='items'&&a.enabled);assert(item);const inventory=clone(b.inventory);await act(h,item.key,item.targets[0]);const s=state(h).state;assert.strictEqual(s.inventory[item.item],inventory[item.item]-1);await act(h,'retreat');assert.strictEqual(h.diag().result.outcome,'escaped');h.close();});
for(const enc of ['normal','elite_humanoid','elite_nonhumanoid','boss'])await test('Full manual menu→target→confirm fight '+enc,async()=>{const f=await fight(enc);fights.push(f);return {steps:f.steps,readyWindows:f.readyWindows,manualCount:f.manualCount,seenCharges:f.seenCharges,outcome:f.result.outcome,rounds:f.result.rounds};});
await test('Speed 1x versus 4x produces identical chosen actions and combat result',async()=>{const a=await fight('boss','standard','1'),b=fights.find(f=>f.enc==='boss');assert.deepStrictEqual(a.result,b.result);assert.deepStrictEqual(a.chosen,b.chosen);return {steps:a.steps};});
await test('Full manual Boss run without concerto keeps naturally earned 100 until explicit release',async()=>{const f=await fight('boss','standard','4',false);assert(f.readyWindows>0);assert.strictEqual(f.manualCount,0);assert.strictEqual(f.state.state.log.filter(x=>x.event==='concerto').length,0);return {readyWindows:f.readyWindows,finalConcerto:f.state.state.allies.map(a=>({key:a.key,value:a.concerto}))};});
await test('KO enemies no longer appear in target/queue/final canvas draw dispatch',async()=>{const f=fights.find(f=>f.result.outcome==='win');assert(f);assert(f.finalDraws.length);assert(!f.finalDraws.some(d=>/ENEMY_/.test(d.src)));return 'Canvas call dispatch only, not visual fade/pixel evidence';});
await test('IndexedDB reload restores exact active v0.2 state and selected difficulty',async()=>{const db=new IDBFactory(),h=await boot(db);await setup(h,'boss',undefined,'challenge');await act(h,'basic');h.click('#saveBtn');await h.tick();const s=state(h);h.close();const k=await boot(db);assert.deepStrictEqual(state(k),s);assert.strictEqual(state(k).state.options.difficulty,'challenge');k.close();});
await test('Legacy saved records retain custom media/calibration and preserve old battle backup',async()=>{const old=JSON.parse(fs.readFileSync(path.join(fixtures,'v01_saved_records.json'))),db=new IDBFactory();await preload(db,old);const h=await boot(db);assert.strictEqual(project(h).background.name,old.project.background.name);assert.deepStrictEqual(project(h).calibration,old.project.calibration);assert.notStrictEqual(state(h).parameter_version,old.battle.parameter_version);assert(h.$('#migrationNotice').textContent.includes('旧战局'));assert.deepStrictEqual(clone(await readRecord(h,'previousVersionBattle')),old.battle);h.close();});
await test('Legacy project import retains media and announces incompatible battle rather than silently restoring',async()=>{const h=await boot();h.click('#assetsBtn');h.click('[data-tab=project]');await h.import('#importProject','v01_project_with_battle.json');assert.strictEqual(project(h).background.name,'qa_checkerboard.png');assert(h.$('#migrationNotice').textContent.includes('旧版'));assert.strictEqual(state(h).state.round,1);assert(!state(h).state.log.some(x=>x.event==='action'));h.close();});
await test('Current project roundtrip restores embedded media, portrait crop, difficulty and exact battle',async()=>{const h=await boot();await setup(h,'boss',undefined,'challenge');await act(h,'basic');h.click('#assetsBtn');h.click('[data-tab=background]');await h.import('#backgroundFile','qa_checkerboard.png');h.click('[data-tab=sprites]');h.input('[data-cal=portraitX]','0.17');h.input('[data-cal=scale]','1.25');h.click('[data-tab=audio]');await h.import('[data-audio=hit]','qa_chime.wav');h.click('[data-tab=project]');h.click('#exportProject');const raw=await h.downloads.at(-1).blob.text(),saved=JSON.parse(raw);const k=await boot();k.click('#assetsBtn');k.click('[data-tab=project]');await k.import('#importProject','new.json',raw);assert.deepStrictEqual(state(k),saved.battle);assert.strictEqual(project(k).background.name,'qa_checkerboard.png');assert.strictEqual(project(k).audio.hit.name,'qa_chime.wav');assert(Object.values(project(k).calibration).some(x=>x.portraitX===.17&&x.scale===1.25));h.close();k.close();});
await test('Malformed/current corrupt imports leave both project and battle unchanged',async()=>{const h=await boot();await act(h,'basic');h.click('#assetsBtn');h.click('[data-tab=project]');h.click('#exportProject');const good=JSON.parse(await h.downloads.at(-1).blob.text()),before=textState(h),p=JSON.stringify(project(h));for(const raw of ['{bad',JSON.stringify({schema:'wrong'}),JSON.stringify({...good,battle:{...good.battle,state:{...good.battle.state,_currentId:null}}})]){await h.import('#importProject','bad.json',raw);assert.strictEqual(textState(h),before);assert.strictEqual(JSON.stringify(project(h)),p);}h.close();});
await test('File cancel/bad image/oversize and audio assignment do not mutate combat',async()=>{const h=await boot(),before=textState(h);h.click('#assetsBtn');h.click('[data-tab=background]');await h.cancelFile('#backgroundFile');await h.import('#backgroundFile','qa_bad_image.png');assert(h.$('#toast').textContent.includes('只接受'));await h.import('#backgroundFile','qa_oversize.png');assert(h.$('#toast').textContent.includes('20 MiB'));assert.strictEqual(project(h).background.name,'');h.click('[data-tab=audio]');await h.cancelFile('[data-audio=attack]');await h.import('[data-audio=attack]','qa_bad_audio.wav');assert(h.$('#toast').textContent.includes('音频文件头'));await h.import('[data-audio=attack]','qa_chime.wav');assert.strictEqual(project(h).audio.attack.name,'qa_chime.wav');assert.strictEqual(textState(h),before);h.close();});
await test('Sprite import retains original target despite slot switch while async reading',async()=>{const h=await boot();h.click('#assetsBtn');h.click('[data-tab=sprites]');const original=h.$('#assetSlot').value,input=h.$('#spriteFile');Object.defineProperty(input,'files',{configurable:true,value:[new File([fs.readFileSync(path.join(fixtures,'qa_checkerboard.png'))],'qa_checkerboard.png')]});input.dispatchEvent(new h.w.Event('change'));h.change('#assetEntity','amy');for(let i=0;i<12;i++)await h.tick();assert(project(h).overrides[original]);assert.strictEqual(Object.keys(project(h).overrides).length,1);h.close();});
await test('Focused Enter opens categories and confirms one action only; modal Enter cannot act',async()=>{const h=await boot(),before=textState(h);h.$('[data-category=battle]').focus();key(h,'Enter');assert.strictEqual(h.diag().menuCategory,'battle');h.$('[data-action=basic]').focus();key(h,'Enter');assert.strictEqual(h.diag().selected,'basic');h.$('[data-target]').focus();key(h,'Enter');assert.strictEqual(textState(h),before);h.click('#helpBtn');const still=textState(h);key(h,'Enter');assert.strictEqual(textState(h),still);h.click('[data-close=helpDialog]');h.$('#confirmBtn').focus();key(h,'Enter');key(h,'Enter');await settle(h);assert.strictEqual(state(h).state.log.filter(x=>x.event==='action'&&x.actor==='ally:1:lynae').length,1);h.close();});
await test('Read battle clears stale action/category/detail and returns to current actor root',async()=>{const h=await boot();h.click('#saveBtn');await h.tick();choose(h,'basic');h.click('[data-target]');h.click('#resumeBtn');for(let i=0;i<5;i++)await h.tick();assert.strictEqual(h.diag().selected,null);assert.strictEqual(h.diag().targetId,null);assert.strictEqual(h.diag().menuCategory,'root');assert.strictEqual(h.diag().inspectedAction,null);h.close();});
await test('Each concerto detail exposes exact special channel and duration from engine',async()=>{const h=await boot();await setup(h,'boss',['lynae','mornye','denia','chisa']);h.click('[data-category=skills]');for(const c of engine(h).availableConcertos()){const b=h.$('[data-action="__concerto:'+c.actor+'"]');assert(b);b.focus();assert(h.$('#detailBody').textContent.includes(c.effectSummary));assert(h.$('#detailBody').textContent.includes(c.durationText));}h.close();});
await test('Natural Amy and Denia form changes update persistent portrait source without preview mutation',async()=>{const output=[];for(const who of ['amy','denia']){const h=await boot();await setup(h,'boss',[who],'easy');let steps=0,targetForm=who==='amy'?'mech':'blue';while(!h.diag().result&&state(h).state.allies[0].form!==targetForm&&steps++<10){const b=engine(h),[k,t]=b._choose(b.current);await act(h,k,t.id);}assert.strictEqual(state(h).state.allies[0].form,targetForm);h.draws.length=0;await h.frame();const expected=who==='amy'?'amy_mecha_M01.png':'denia_blue_DB01.png';assert(h.draws.some(d=>d.src.endsWith(expected)&&d.args.length===8),expected+' portrait draw missing');output.push({who,form:targetForm,steps,source:expected});h.close();}return {drawDispatchOnly:output};});
const out={evidenceClass:'DOM/event integration: actual HTML/JS, fake IndexedDB, controlled timers and stub Canvas/Image/Audio; NOT real browser',timestamp:new Date().toISOString(),hashes:testedHashes,sourceUnchanged:Object.entries(testedHashes).every(([f,h])=>sha(f)===h),results,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length};fs.writeFileSync(path.join(__dirname,'dom_v02_audit_results.json'),JSON.stringify(out,null,2));fs.writeFileSync(path.join(__dirname,'dom_v02_fight_results.json'),JSON.stringify(fights,null,2));console.log(JSON.stringify({passed:out.passed,failed:out.failed,failures:results.filter(x=>!x.pass)},null,2));process.exitCode=out.failed||!out.sourceUnchanged?1:0;
})();
