'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('assert');
const root=path.resolve(__dirname,'../../..'),sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const ctx={};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'assets.js'),'utf8'),ctx);const D=JSON.parse(JSON.stringify(ctx.DEFAULT_ASSETS)),checks=[];
function check(name,f){try{checks.push({name,pass:true,detail:f()??null})}catch(e){checks.push({name,pass:false,error:e.message})}}
check('89 package-local PNGs match SHA and disallow mirroring',()=>{const R=JSON.parse(fs.readFileSync(path.join(root,'RUNTIME_ASSETS.json')));assert.equal(R.assets.length,89);assert.equal(Object.keys(D.slots).length,89);for(const [key,s] of Object.entries(D.slots)){assert(/^assets\/[^/]+\.png$/.test(s.src));assert.equal(sha(path.join(root,s.src)),s.sha256,key);assert.equal(s.mirrorAllowed,false);const r=R.assets.find(r=>r.slot===key);assert(r);assert.equal(r.path,s.src);assert.equal(r.sha256,s.sha256);assert.equal(r.size,fs.statSync(path.join(root,s.src)).size);}return {slots:89};});
check('All actions, sequences and transitions resolve',()=>{let actions=0,sequences=0;for(const [entity,forms] of Object.entries(D.forms))for(const [form,f] of Object.entries(forms)){for(const slot of [f.idle,...Object.values(f.actions)]){assert(D.slots[slot],slot);assert.equal(D.slots[slot].entity,entity);assert.equal(D.slots[slot].form,form);actions++;}for(const seq of Object.values(f.sequences||{}))for(const slot of seq){assert(D.slots[slot]);sequences++;}}for(const seq of Object.values(D.transitions))for(const slot of seq){assert(D.slots[slot]);sequences++;}return {actions,sequences};});
check('Readable manifest equals runtime manifest and excludes upstream identifiers',()=>{assert.deepStrictEqual(D,JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'))));const t=JSON.stringify(D);for(const key of ['sourcePath','sourceRegister','sourceAssetId','v3_generated','v3_review','libfile_','Sentinel_'])assert(!t.includes(key),key);return {equal:true};});
check('Mecha scale and all five enemy bodies preserved',()=>{assert.equal(D.forms.amy.mecha.bodyScale,1.7);assert.equal(Object.keys(D.enemies).length,5);for(const e of Object.values(D.enemies))assert(D.slots[e.slot||e.idle]);return {enemies:5};});
const result={evidenceClass:'STATIC PACKAGE ASSETS: no rendered pixels',timestamp:new Date().toISOString(),assetsSHA256:sha(path.join(root,'assets.js')),checks,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length};fs.writeFileSync(path.join(__dirname,'public_asset_audit_results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));process.exitCode=result.failed?1:0;
