'use strict';
// Independent v0.2 audit of delivered JavaScript. No browser/visual evidence.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto'),vm=require('vm');
const ROOT=path.resolve(process.env.QA_ROOT||path.join(__dirname,'../../..'));
const B=require(path.join(ROOT,'engine.js')),P=JSON.parse(fs.readFileSync(path.join(ROOT,'parameters.json'))),results=[];
const clone=x=>JSON.parse(JSON.stringify(x)),snap=b=>JSON.stringify(b.snapshot()),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex');
const testedHashes=Object.fromEntries(['engine.js','parameters.json','parameters.js'].map(f=>[f,hash(f)]));
function mk(team=['amy','lynae','mornye','denia'],encounter='boss',extra={}){const b=new B(P,{team,encounter,level:20,hp_fraction:1,seed:73,...extra});b.start();return b;}
function test(name,fn){try{const detail=fn();results.push({name,pass:true,detail:detail??null});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.stack});console.log('FAIL '+name+': '+e.message);}}
function rejectUnchanged(b,fn){const before=snap(b);const r=fn();assert.strictEqual(r.ok,false);assert(r.reason);assert.strictEqual(snap(b),before);}
const diffs=['easy','standard','challenge'];
function summarize(b,steps){return {team:b.options.team,encounter:b.options.encounter,difficulty:b.options.difficulty,steps,...b.summary()};}
function runPublic(b,{maxRounds=60,manualConcertos=false,policy='tactical',restore=false}={}){let steps=0,restores=0,firstReady=null,releases=[];while(!b.result&&b.round<=maxRounds){assert(b.current);if(b.current.side==='ally'){
  const ready=b.availableConcertos().filter(c=>c.enabled);if(ready.length&&!firstReady)firstReady={round:b.round,actor:ready[0].actor,normalCounts:b.allies.map(a=>({key:a.key,count:a.normal_count,concerto:a.concerto}))};
  if(manualConcertos)for(const c of ready){let ts=c.targets.map(id=>b.getUnit(id)).filter(t=>t.acted_round!==b.round);ts.sort((a,z)=>z.atk-a.atk);const t=ts[0]||b.getUnit(c.targets[0]);if(!t||b.validateConcerto(c.actor,t.id))continue;const before={current:b.currentId,queue:[...b.queue],count:b.allies.map(a=>a.normal_count),round:b.round};const r=b.concerto(c.actor,t.id);assert(r.ok,r.reason);assert.strictEqual(b.currentId,before.current);assert.deepStrictEqual(b.queue,before.queue);assert.deepStrictEqual(b.allies.map(a=>a.normal_count),before.count);assert.strictEqual(b.round,before.round);releases.push(...r.events.filter(e=>e.event==='concerto'));}
 }
 const oldLog=b.log.length;
 let r;if(b.current.side==='enemy')r=b.stepEnemy();else if(policy==='guard')r=b.act('guard',b.current.id);else if(policy==='basic')r=b.act('basic',b.living('enemy')[0].id);else {const [key,t]=b._choose(b.current);r=b.act(key,t.id);}assert(r.ok,r.reason);b.validate();assert(b.log.length>oldLog,'each turn must progress');steps++;
 if(restore){const saved=b.snapshot(),other=B.restore(P,saved);assert.strictEqual(snap(other),JSON.stringify(saved));restores++;}
 assert(steps<3000,'action-bound');
 }
 return {...summarize(b,steps),restores,firstReady,releases};}

test('v0.2 parameter JS equals JSON and versions changed explicitly',()=>{const ctx={};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(ROOT,'parameters.js'),'utf8'),ctx);assert.deepStrictEqual(clone(ctx.BATTLE_PARAMETERS),P);assert.notStrictEqual(P.schema_version,'0.1.2-candidate');assert(/^0\.2/.test(P.schema_version));return P.schema_version;});
test('Difficulty values and invalid inputs are validated; each setting changes enemy strength',()=>{assert(P.difficulties);for(const x of diffs)assert(P.difficulties[x],x);for(const x of ['not-real','__proto__','constructor',0,null])assert.throws(()=>mk(undefined,undefined,{difficulty:x}),String(x));const rows=diffs.map(difficulty=>{const b=mk(undefined,undefined,{difficulty});assert.strictEqual(b.options.difficulty,difficulty);return {difficulty,stats:b.enemies.map(e=>({hp:e.maxhp,atk:e.atk,shield:e.maxshield,pattern:e.pattern}))};});assert.strictEqual(new Set(rows.map(r=>JSON.stringify(r.stats))).size,3);return rows;});
test('Constructor retains zero-resource zero-concerto openings for every difficulty',()=>{for(const difficulty of diffs)for(const key of Object.keys(P.characters)){const b=mk([key],'boss',{difficulty});assert(b.allies.every(a=>a.concerto===0&&Object.values(a.rsc).every(v=>v===0)));}});
test('Caller config mutation cannot silently change ongoing difficulty or stored stats',()=>{const options={team:['amy','lynae'],encounter:'boss',difficulty:'easy'};const b=new B(P,options);b.start();const saved=snap(b);options.difficulty='challenge';options.team[0]='denia';assert.strictEqual(snap(b),saved);const c=B.restore(P,b.snapshot());assert.strictEqual(c.options.difficulty,'easy');assert.strictEqual(snap(c),saved);});
test('Old parameter-version save is explicitly rejected',()=>{const records=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/v01_saved_records.json')));assert.throws(()=>B.restore(P,records.battle),/版本|参数|存档/);});
test('Read-only action, concerto, intent and inspect calls do not mutate battle',()=>{for(const difficulty of diffs){const b=mk(undefined,undefined,{difficulty}),before=snap(b);for(let i=0;i<3;i++){b.availableActions();b.availableConcertos();for(const e of b.enemies)b.enemyIntent(e.id);b.summary();b.validate();}assert.strictEqual(snap(b),before);}});
test('Invalid commands and prototype names are mutation-free with visible reasons',()=>{for(const difficulty of diffs){const b=mk(undefined,undefined,{difficulty});for(const key of ['missing','__proto__','constructor','negotiate'])rejectUnchanged(b,()=>b.act(key,b.enemies[0].id));rejectUnchanged(b,()=>b.act('basic',b.current.id));for(const a of b.availableActions())if(!a.enabled)assert(a.reason);}});
test('Default autoAction never releases a player-earned concerto',()=>{const b=mk(undefined,'boss',{difficulty:'standard'});let ready=0,steps=0;while(!b.result&&b.round<=40){if(b.availableConcertos().some(x=>x.enabled))ready++;const r=b.autoAction();assert(r.ok,r.reason);assert(++steps<2000);}assert(ready>0,'No naturally earned manual concerto window');assert.strictEqual(b.log.filter(e=>e.event==='concerto').length,0);return {readyWindows:ready,summary:b.summary()};});
test('Natural manual concerto is reachable and releases without granting ordinary turns',()=>{const b=mk(undefined,'boss',{difficulty:'standard'});const r=runPublic(b,{manualConcertos:true,restore:true});assert(r.firstReady,'No natural ready window');assert(r.releases.length>0,'No manual releases');fs.writeFileSync(path.join(__dirname,'natural_manual_concerto_log.json'),JSON.stringify({result:r,log:b.log},null,2));return r;});
test('Elite/Boss special attacks execute real events under legal guard-only exposure',()=>{const rows=[];for(const enc of ['elite_humanoid','elite_nonhumanoid','boss']){const b=mk(undefined,enc,{difficulty:'standard'});const row=runPublic(b,{policy:'guard',maxRounds:18,restore:true});const enemyEvents=b.log.filter(e=>e.event==='enemy_action');const byEnemy=Object.fromEntries(b.enemies.filter(e=>e.rank!=='common').map(e=>[e.key,enemyEvents.filter(x=>x.actor===e.id).map(x=>x.skill)]));assert(enemyEvents.length);for(const e of b.enemies.filter(e=>e.rank!=='common')){const used=new Set(byEnemy[e.key]);assert(used.size>=2,'Enemy never executes distinct attacks '+e.key);if(e.rank==='boss'){assert(b.log.some(x=>x.event==='status'&&x.status==='charge'),'Boss has no actual charge');assert([...used].some(k=>/descent|rush|spin/.test(k)),'Boss charged release never executes');}}assert((b.count.damage_enemy||0)>0);rows.push({...row,byEnemy});fs.writeFileSync(path.join(__dirname,'enemy_'+enc+'_exposure_log.json'),JSON.stringify(b.log,null,2));}return rows;});
test('All 30 legal rosters × 4 encounters × 3 difficulties restore after every real action',()=>{const keys=Object.keys(P.characters),rows=[];let restored=0;for(let mask=1;mask<1<<keys.length;mask++){const team=keys.filter((_,i)=>mask&(1<<i));if(team.length>4)continue;for(const difficulty of diffs)for(const encounter of Object.keys(P.encounters)){const b=mk(team,encounter,{difficulty});const row=runPublic(b,{maxRounds:60,manualConcertos:true,restore:true});rows.push(row);restored+=row.restores;}}fs.writeFileSync(path.join(__dirname,'roster_difficulty_results.json'),JSON.stringify(rows,null,2));assert.strictEqual(rows.length,360);return {cases:rows.length,restored,outcomes:Object.fromEntries(['win','loss','inconclusive'].map(x=>[x,rows.filter(r=>r.outcome===x).length]))};});
test('Same seeded stochastic state restores to identical full continuation',()=>{let n=0;for(const difficulty of diffs){const b=mk(undefined,'boss',{difficulty,stochastic:true,seed:934});for(let i=0;i<9&&!b.result;i++)assert(b.autoAction().ok);let c=B.restore(P,b.snapshot());while(!b.result&&b.round<=60){const rb=b.autoAction(),rc=c.autoAction();assert.strictEqual(rb.ok,rc.ok);assert.strictEqual(snap(b),snap(c));assert(++n<2000);}assert(b.result);}return {actions:n};});
const out={evidenceClass:'NODE: actual JS engine, no DOM/browser',timestamp:new Date().toISOString(),root:'.',hashes:testedHashes,sourceUnchanged:Object.entries(testedHashes).every(([f,h])=>hash(f)===h),parameterVersion:P.schema_version,results,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length};fs.writeFileSync(path.join(__dirname,'engine_v02_audit_results.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({passed:out.passed,failed:out.failed,failures:results.filter(x=>!x.pass)},null,2));process.exitCode=out.failed||!out.sourceUnchanged?1:0;
