const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');const {parseHTML}=require(process.env.LINKEDOM_PATH||'/tmp/wuwa-ui-test/node_modules/linkedom');const {document}=parseHTML('<main></main>');const box={document,console,atob,btoa};vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/technical-preview.js'),'utf8'),box);const T=vm.runInContext('TechnicalPreview',box);document.querySelector('main').innerHTML=T.html();const panel=document.querySelector('.technical-animation');let now=0,serial=0;const timers=new Map();const assets={B:{idle:{src:'/B-idle.gif',durationMs:2000},hit:{src:'/B-hit.gif',durationMs:500},cast:{src:'/B-cast.gif',durationMs:760}},D:{idle:{src:'/D-idle.gif',durationMs:2000},hit:{src:'/D-hit.gif',durationMs:540},cast:{src:'/D-cast.gif',durationMs:920}}};const untouched=JSON.stringify(assets);const c=T.mount(panel,{assets,setTimeout:(fn,ms)=>{const id=++serial;timers.set(id,{fn,at:now+ms});return id},clearTimeout:id=>timers.delete(id)});
function advance(ms){const target=now+ms;for(;;){const e=[...timers].filter(([,t])=>t.at<=target).sort((a,b)=>a[1].at-b[1].at)[0];if(!e)break;timers.delete(e[0]);now=e[1].at;e[1].fn();}now=target}
const img=()=>panel.querySelector('img');assert.equal(c.getState().style,'D');img().onload();assert.equal(timers.size,0);
c.play('cast');let old=img();old.onload();advance(400);c.play('hit');let hit=img();hit.onload();assert.notEqual(hit,old);advance(539);assert.equal(c.getState().state,'hit');advance(1);assert.equal(c.getState().state,'idle');
c.play('hit');const first=img(),src=first.src;first.onload();c.play('hit');assert.notEqual(img().src,src,'new same-action URL must be a fresh resource identity');assert.notEqual(img(),first);first.onload();first.onerror();assert.equal(timers.size,0,'old load callback cannot schedule after replacement');img().onload();assert.equal(timers.size,1);
const select=panel.querySelector('[data-tech-style]');Object.defineProperty(select,'value',{value:'B',configurable:true});select.onchange();assert.equal(c.getState().state,'idle');assert.equal(c.getState().style,'B');assert.equal(timers.size,0);advance(2000);assert.equal(c.getState().style,'B');
c.play('cast');const bad=img();bad.onerror();assert.equal(c.getState().state,'unavailable');assert(panel.querySelector('.technical-placeholder'));assert.equal(timers.size,0);c.play('idle');img().onload();assert.equal(c.getState().state,'idle');
c.play('cast');img().onload();c.dispose();assert.equal(timers.size,0);advance(2000);assert.equal(JSON.stringify(assets),untouched);assert.equal(panel.querySelectorAll('[data-actor]').length,0,'technical preview cannot add a battlefield body');
const gif='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';const a=T.replayURL(gif),b=T.replayURL(gif);assert.notEqual(a,b);assert(atob(a.split(',')[1]).includes('technical-replay-'));assert.equal(atob(a.split(',')[1]).slice(-1),';');
console.log('PASS: cast overwritten by hit, repeated hit fresh node+src, stale load ignored, B/D cancels timers, return idle, bad-file fallback/retry, dispose, distinct replay-data payload, no game body/state access. Actual browser frame playback remains unverified.');
