'use strict';const fs=require('fs'),assert=require('assert/strict'),E=require('../../engine.js'),P=require('../../parameters.json');
const b=new E(P,{team:['amy','lynae','mornye','denia'],encounter:'boss',difficulty:'standard'});b.start();
while(!b.result&&!b.enemies[0].status.charge){if(b.current.side==='enemy')b.stepEnemy();else{const[k,t]=b._choose(b.current);assert.ok(b.act(k,t.id).ok);}}
const snapshot=b.snapshot(),start=b.log.length,results=[];
for(const strategy of ['break_setup','guard','heal_and_guard']){const c=E.restore(P,snapshot),boss=c.enemies[0];let limit=0;
 while(!c.result&&!c.log.slice(start).some(e=>['charge_interrupted','charge_released'].includes(e.event))&&limit++<30){if(c.current.side==='enemy')assert.ok(c.stepEnemy().ok);else{const a=c.current;let key='guard',target=a;if(strategy==='break_setup')[key,target]=c._choose(a);else if(strategy==='heal_and_guard'&&a.key==='mornye'){target=c.living('ally').sort((a,z)=>z.maxhp-z.hp-(a.maxhp-a.hp))[0];if(!c.validateAction(a.id,'heal',target.id))key='heal';else target=a;}assert.ok(c.act(key,target.id).ok);}}
 const ev=c.log.slice(start),summary={strategy,result:ev.some(e=>e.event==='charge_interrupted')?'interrupted':'released',enemyHP:boss.hp,enemyShield:boss.shield,allyHP:Object.fromEntries(c.allies.map(a=>[a.key,a.hp])),resources:Object.fromEntries(c.allies.map(a=>[a.key,a.rsc])),enemyDamage:ev.filter(e=>e.event==='damage'&&e.actor===boss.id).reduce((n,e)=>n+e.amount,0),healing:ev.filter(e=>e.event==='heal').reduce((n,e)=>n+e.amount,0),actions:ev.filter(e=>e.event==='action').map(e=>({round:e.round,actor:e.actor,skill:e.skill})),events:ev};results.push(summary);}
assert.equal(results[0].result,'interrupted');assert.equal(results[0].enemyDamage,0);assert.equal(results[1].result,'released');assert.ok(results[1].enemyDamage>0);assert.ok(results[2].healing>0);
fs.writeFileSync(__dirname+'/charge_choice_results.json',JSON.stringify({scope:'Three legal branches from the SAME naturally reached standard boss first charge at round 2, shield 4. No altered enemy state or injected resources. The healing branch pays existing Mornye calibration and an action. Each ends at charge interruption or release; resource and damage opportunity costs are retained.',snapshot,results},null,2));console.log(results.map(({strategy,result,enemyHP,enemyShield,enemyDamage,healing,allyHP})=>({strategy,result,enemyHP,enemyShield,enemyDamage,healing,allyHP})));
