'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const Engine=require('../../engine.js');
const params=require('../../parameters.json');
const clone=x=>JSON.parse(JSON.stringify(x));
const close=(x,y)=>assert.ok(Math.abs(x-y)<1e-8,`${x} != ${y}`);
function battle(options={}){const b=new Engine(params,{team:['rover_spectro','lynae','mornye'],encounter:'elite_humanoid',enemy_atk_scale:0,...options});assert.equal(b.start().ok,true);return b;}
function focus(b,u){b._currentId=u.id;b.queue=b.queue.filter(id=>id!==u.id);u.actedRound=Math.max(0,b.round-1);u.slotStartedRound=b.round;}
function nextRound(b){const r=b.round;let safety=0;while(b.round===r&&!b.result&&safety++<50){const a=b.current;assert.ok(a);const out=a.side==='enemy'?b.stepEnemy():b.act('guard',a.id);assert.equal(out.ok,true,out.reason);}assert.ok(safety<50);}
function untilEnemy(b,key){for(let i=0;i<50;i++){if(b.current?.key===key)return b.current;const u=b.current;assert.ok(u);const r=u.side==='enemy'?b.stepEnemy():b.act('guard',u.id);assert.equal(r.ok,true);}throw Error('enemy slot not reached');}
function projectiles(){const b=battle({team:['rover_spectro','lynae','mornye'],encounter:'dreamless',enemy_hp_scale:10});const boss=b.enemies[0];b.applyQ(b.allies[0],boss,boss.q);untilEnemy(b,'dreamless');b.stepEnemy();assert.equal(boss.q,156);untilEnemy(b,'dreamless');b.stepEnemy();assert.equal(boss.bossState,'projectiles');assert.equal(b.living('enemy').filter(u=>u.mechanicUnit).length,2);return {b,boss,ps:b.enemies.filter(u=>u.mechanicUnit)};}

test('initial model: eight panel stats, no AP/concerto pools and only one Rover',()=>{const b=battle();for(const a of b.allies){assert.equal(a.bp,1);assert.equal(a.energy,0);assert.equal(a.hp,a.maxhp);assert.equal(a.sp,a.maxsp);for(const k of ['ap','temp_ap','concerto','rsc'])assert.equal(k in a,false);}assert.throws(()=>new Engine(params,{team:['rover_spectro','rover_aero']}));assert.throws(()=>new Engine(params,{level:91}));});
test('every illegal BP value is atomic, including NaN and infinities',()=>{const b=battle();const a=b.allies[0];focus(b,a);for(const bp of [-1,4,1.5,NaN,Infinity,-Infinity,'1',null]){const before=JSON.stringify(b.snapshot());const r=b.act('A',b.enemies[0].id,{bp});assert.equal(r.ok,false,String(bp));assert.equal(JSON.stringify(b.snapshot()),before);}});
test('illegal target, insufficient SP and cooldown are mutation-free',()=>{const b=battle();const a=b.allies[0];focus(b,a);for(const [key,id,options] of [['A','bad',{}],['A',a.id,{}],['E1',b.enemies[0].id,{bp:3}]]){const before=JSON.stringify(b.snapshot());assert.equal(b.act(key,id,options).ok,false);assert.equal(JSON.stringify(b.snapshot()),before);}a.sp=0;const before=JSON.stringify(b.snapshot());assert.equal(b.act('E1',b.enemies[0].id).ok,false);assert.equal(JSON.stringify(b.snapshot()),before);});
test('one normal command per round; waiting does not pay, tick or count an action',()=>{const b=battle();const a=b.allies[0];focus(b,a);const before={sp:a.sp,bp:a.bp,energy:a.energy,round:b.round,id:b.action_id};assert.equal(b.act('wait',a.id).ok,true);assert.deepEqual({sp:a.sp,bp:a.bp,energy:a.energy,round:b.round,id:b.action_id},before);while(b.currentId!==a.id){const u=b.current;u.side==='enemy'?b.stepEnemy():b.act('guard',u.id);}assert.equal(b.act('wait',a.id).ok,false);assert.equal(b.act('A',b.enemies[0].id).ok,true);if(b.round===before.round){assert.equal(a.actedRound,b.round);assert.ok(b.availableActions(a.id).every(row=>!row.enabled));}});
test('BP natural growth suppresses exactly the round after spending and never restores SP',()=>{const b=battle();const a=b.allies[0];focus(b,a);a.bp=3;a.sp=17;b.act('A',b.enemies[0].id,{bp:3});assert.equal(a.bp,0);nextRound(b);assert.equal(a.bp,0);assert.equal(a.sp,17);nextRound(b);assert.equal(a.bp,1);assert.equal(a.sp,17);});
test('CD readyRound is r+N and E2A/E2B share one absolute clock',()=>{const b=battle({team:['rover_electro','lynae']});const a=b.allies[0];focus(b,a);a.bp=0;assert.equal(b.act('rover_electro_e2a',b.enemies[0].id).ok,true);assert.equal(a.cooldowns.rover_electro_e2,4);nextRound(b);focus(b,a);let before=JSON.stringify(b.snapshot());assert.equal(b.act('rover_electro_e2b',b.enemies[0].id).ok,false);assert.equal(JSON.stringify(b.snapshot()),before);nextRound(b);nextRound(b);focus(b,a);a.sp=a.maxsp;assert.equal(b.act('rover_electro_e2b',b.enemies[0].id).ok,true);});
test('energy has 0.0001 precision and receiver ER is independent of capped producer',()=>{const b=battle();const a=b.allies[0],other=b.allies[1];a.energy=a.energyCap;other.energy=0;other.er=1.151;b.distributeEnergy(a,15);assert.equal(a.energy,a.energyCap);close(other.energy,8.6325);assert.equal(b.log.filter(e=>e.event==='energy'&&e.target===other.id).length,1);});
test('four basic originals each have their own hit, but one root B and incremental Q',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];focus(b,a);a.bp=3;const q=t.q;const r=b.act('A',t.id,{bp:3});assert.equal(r.ok,true);const attacks=r.events.filter(e=>e.event==='original_attack'),hits=r.events.filter(e=>e.event==='successful_hit');assert.equal(attacks.length,4);assert.equal(hits.length,4);assert.equal(new Set(attacks.map(e=>e.attackId)).size,4);assert.equal(new Set(attacks.map(e=>e.rootActionId)).size,1);close(q-t.q,10.8);close(a.energy,15*a.er);assert.deepEqual(r.events.filter(e=>e.event==='q_damage').map(e=>e.amount),[6,2.1,1.5,1.2]);});
test('misses do not generate hits/Q while an actually launched attack still grants one B',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];focus(b,a);a.bp=3;const q=t.q;const out=b.act('A',t.id,{bp:3,forceMiss:true});assert.equal(out.events.filter(e=>e.event==='original_attack').length,4);assert.equal(out.events.filter(e=>e.event==='successful_hit').length,0);assert.equal(t.q,q);close(a.energy,15*a.er);});
test('elemental damage immunity is a successful hit but gives zero Q',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];focus(b,a);t.immune_elements=['spectro'];const hp=t.hp,q=t.q;const out=b.act('E1',t.id);assert.equal(t.hp,hp);assert.equal(t.q,q);assert.equal(out.events.filter(e=>e.event==='successful_hit').length,1);assert.equal(out.events.find(e=>e.event==='successful_hit').damageImmune,true);assert.ok(t.status.spectro_frazzle);close(a.energy,20*a.er);});
test('death stops remaining attacks on the fixed target, with no corpse Break',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];focus(b,a);a.bp=3;t.hp=1;t.q=.1;const out=b.act('A',t.id,{bp:3});assert.equal(out.events.filter(e=>e.event==='original_attack').length,1);assert.equal(out.events.filter(e=>e.event==='break').length,0);assert.ok(b.enemies[1].hp>0);});
test('derived packets cannot open attacks or receive implicit B/Q',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];const energy=a.energy,q=t.q,start=b.log.length;b.damage(a,t,{coef:.5,kind:'coordinated'});const rows=b.log.slice(start);assert.equal(rows.filter(e=>e.event==='original_attack'||e.event==='successful_hit').length,0);assert.equal(t.q,q);assert.equal(a.energy,energy);});
test('Break belongs to actual source, occurs once and consumes only next main slot',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];t.q=1;b.applyQ(a,t,1);b.applyQ(b.allies[1],t,100);const events=b.log.filter(e=>e.event==='break');assert.equal(events.length,1);assert.equal(events[0].source,a.id);untilEnemy(b,'bracer');const before=b.allies.map(a=>a.hp);const out=b.stepEnemy();assert.equal(out.events.find(e=>e.event==='enemy_action').skill,'break_recover');assert.deepEqual(b.allies.map(a=>a.hp),before);assert.equal(t.q,72);assert.equal(t.breakPending,false);assert.equal(out.events.some(e=>e.event==='original_attack'),false);});
test('R2 persists through rounds, death and revival; locked incoming energy is discarded',()=>{const b=battle({team:['amy','lynae'],enemy_hp_scale:10});const a=b.allies[0];focus(b,a);a.energy=a.energyCap;a.bp=5;assert.equal(b.act('R',b.enemies[0].id,{bp:0}).ok,true);assert.equal(a.r2Pending,true);assert.equal(a.form,'mech');assert.equal(a.energy,0);for(let i=0;i<3;i++)nextRound(b);assert.equal(a.r2Pending,true);b.distributeEnergy(b.allies[1],20);assert.equal(a.energy,0);b.damage(b.enemies[0],a,{base:1e9,kind:'original'});assert.equal(a.r2Pending,true);assert.equal(a.energyLocked,true);assert.equal(a.form,'mech');assert.equal(b.revive(a,100),true);assert.equal(a.r2Pending,true);nextRound(b);focus(b,a);a.bp=3;const out=b.act('R',b.enemies[0].id,{bp:3});assert.equal(out.ok,true);assert.equal(a.bp,0);assert.equal(a.r2Pending,false);assert.equal(a.energyLocked,false);b.distributeEnergy(b.allies[1],10);close(a.energy,5*a.er);});
test('R2 is a paid normal action, does not restart R cooldown and never charges energy twice',()=>{const b=battle({team:['amy','lynae'],enemy_hp_scale:10});const a=b.allies[0];focus(b,a);a.energy=125;a.bp=5;b.act('R1',b.enemies[0].id,{bp:0});assert.equal(a.cooldowns.R,4);nextRound(b);focus(b,a);const out=b.act('R2',b.enemies[0].id,{bp:3});assert.equal(out.ok,true);assert.equal(out.events.filter(e=>e.event==='action_commit').length,1);assert.equal(out.events.find(e=>e.event==='action_commit').energyCost,0);assert.equal(a.cooldowns.R,4);assert.equal(a.actedRound,2);});
test('damage uses attacker K, separate DEF shred/ignore and negative resistance branch',()=>{const b=battle();const a=b.allies[0],t=b.enemies[0];a.atk=200;a.level=20;t.def=100;t.resist.spectro=.1;close(b._damageMath(a,t,{coef:2,element:'spectro',canCrit:false}).damage,240);const d=b._damageMath(a,t,{coef:2,element:'spectro',defShred:.2,defIgnore:.2});assert.equal(d.damage,Math.floor(400*200/264*.9));t.resist.spectro=-.2;assert.equal(b._damageMath(a,t,{coef:1,element:'spectro'}).damage,Math.floor(200*200/300*1.1));});
test('DEF-scaled Mornye damage and preview agree',()=>{const b=battle();const a=b.allies[2],t=b.enemies[0];focus(b,a);const before=JSON.stringify(b.snapshot());const predicted=b.previewDamage(a,t,'A',{bp:0});assert.equal(JSON.stringify(b.snapshot()),before);const out=b.act('A',t.id);assert.equal(out.events.find(e=>e.event==='damage'&&e.kind==='original').damage,predicted);});
test('preview consumes neither one-use bonuses nor seeded RNG and includes paid setup bonus',()=>{const b=battle({team:['amy','lynae']});const a=b.allies[0],t=b.enemies[0];focus(b,a);b.act('E4',t.id);nextRound(b);focus(b,a);const before=JSON.stringify(b.snapshot());const p=b.previewPacket(a,t,'E2',{bp:0});assert.equal(JSON.stringify(b.snapshot()),before);const out=b.act('E2',t.id);assert.equal(out.events.find(e=>e.event==='damage'&&e.kind==='original').damage,p.damage);});
test('SP recovery excludes caster; fixed budget recipient clipping is not redistributed',()=>{const b=battle();const [a,x,y]=b.allies;a.sp=0;x.sp=x.maxsp-1;y.sp=0;assert.equal(b.restoreSP(a,a,99),0);assert.equal(a.sp,0);assert.equal(b.restoreSP(a,x,10),1);assert.equal(b.restoreSP(a,y,10),10);assert.equal(y.sp,10);});
test('test items are separate one-action limited inventory and may restore self',()=>{const b=battle();const a=b.allies[0];focus(b,a);a.sp=0;const n=b.inventory.sp;const out=b.act('item_sp',a.id);assert.equal(out.ok,true);assert.equal(a.sp,40);assert.equal(b.inventory.sp,n-1);assert.equal(a.energy,0);nextRound(b);focus(b,a);a.hp=100;assert.equal(b.act('item_repair',a.id).ok,true);assert.ok(a.hp>100);});
test('normal enemies never get Q and global control never invents a weak-point button',()=>{const b=battle({encounter:'normal'});assert.equal(b.enemies[0].q,0);b.applyQ(b.allies[0],b.enemies[0],100);assert.equal(b.enemies[0].q,0);assert.equal(b.availableActions(b.allies[0].id).some(a=>/feint|part|break_guard/.test(a.key)),false);});
test('Crownless threshold schedules a transformation slot instead of a free attack',()=>{const b=battle({encounter:'boss'}),boss=b.enemies[0];untilEnemy(b,'crownless');b.stepEnemy();boss.hp=Math.floor(boss.maxhp*.7);b._phaseFacts(boss);assert.equal(boss.phasePending,true);assert.equal(boss.phase,1);untilEnemy(b,'crownless');const out=b.stepEnemy();assert.equal(out.events.find(e=>e.event==='enemy_action').skill,'transform');assert.equal(out.events.filter(e=>e.event==='damage').length,0);assert.equal(boss.phase,2);});
test('Crownless counter stance reacts once to four originals and persists for the next root',()=>{const b=battle({team:['rover_spectro','lynae'],encounter:'boss',enemy_atk_scale:1,enemy_hp_scale:10}),boss=b.enemies[0],a=b.allies[0];b.addStatus(boss,'counter_stance',{owner:boss.id,coef:2.3,suppressed:false,slotBound:true});focus(b,a);b.queue=[b.allies[1].id,boss.id];a.bp=3;const out=b.act('A',boss.id,{bp:3});assert.equal(out.events.filter(e=>e.event==='counter').length,1);assert.ok(boss.status.counter_stance);});
test('Boss control policy preserves ordinary slow but high-pressure charge is immune',()=>{const b=battle({encounter:'boss'}),boss=b.enemies[0],a=b.allies[0];assert.equal(b.control(a,boss,'pull'),false);assert.equal(b.control(a,boss,'slow'),true);b._prepareCharge(boss,'wing_charge');assert.equal(b.control(a,boss,'bind'),false);assert.equal(boss.charge.required,1);const easy=battle({encounter:'boss',difficulty:'easy'}),e=easy.enemies[0];easy._prepareCharge(e,'wing_charge');assert.equal(easy.control(easy.allies[0],e,'bind'),true);assert.equal(e.charge.required,2);assert.equal(easy.control(easy.allies[1],e,'bind'),false);});
test('Dreamless creates two true targetable units, never independent action slots',()=>{const {b,boss,ps}=projectiles();assert.equal(boss.q,156);assert.equal(ps[0].hp,180);assert.equal(ps[0].def,90);assert.equal(ps[0].asset_key,'dreamless_projectile');assert.ok(ps.every(p=>!b.queue.includes(p.id)));for(const p of ps){assert.equal(b.control(b.allies[0],p,'pull'),false);assert.equal(b.control(b.allies[0],p,'bind'),false);assert.equal(b.heal(b.allies[0],p,10),0);}});
test('Dreamless reflections deal 486 unscaled damage and exactly54.6Q, two cross strict half',()=>{const {b,boss,ps}=projectiles();boss.atk=560;const before=boss.hp;const start=b.log.length;b.damage(b.allies[0],ps[0],{base:1e9,kind:'attached'});assert.equal(boss.hp,before-486);close(boss.q,101.4);assert.equal(boss.bossState,'projectiles');b.damage(b.allies[0],ps[1],{base:1e9,kind:'attached'});close(boss.q,46.8);assert.equal(boss.bossState,'special_interrupted');assert.equal(b.living('enemy').filter(p=>p.mechanicUnit).length,0);const events=b.log.slice(start);assert.equal(events.filter(e=>e.event==='reflection').length,2);assert.equal(events.filter(e=>e.event==='energy'||e.event==='original_attack'||e.event==='break').length,0);});
test('Dreamless exact78 does not interrupt; any legal crossing does and freezes furtherQ',()=>{const {b,boss}=projectiles();b.applyQ(b.allies[0],boss,78);assert.equal(boss.q,78);assert.equal(boss.bossState,'projectiles');b.applyQ(b.allies[0],boss,.1);close(boss.q,77.9);assert.equal(boss.bossState,'special_interrupted');b.applyQ(b.allies[0],boss,100);close(boss.q,77.9);untilEnemy(b,'dreamless');const out=b.stepEnemy();assert.equal(out.events.find(e=>e.event==='enemy_action').skill,'special_recover');assert.equal(boss.q,77.9);assert.equal(boss.phase,2);});
test('Dreamless full Break and special interruption merge into one recovery slot',()=>{const {b,boss}=projectiles();b.applyQ(b.allies[0],boss,156);assert.equal(boss.breakPending,true);assert.equal(boss.bossState,'special_interrupted');untilEnemy(b,'dreamless');const out=b.stepEnemy();assert.equal(out.events.find(e=>e.event==='enemy_action').skill,'break_recover');assert.equal(boss.q,156);assert.equal(boss.specialDone,true);assert.equal(boss.bossState,'normal');assert.equal(boss.breakPending,false);});
test('two normal response opportunities are guaranteed to every registered living ally',()=>{const {b,boss}=projectiles();assert.equal(b._canRelease(boss),false);for(let i=0;i<2;i++){untilEnemy(b,'dreamless');const counts=Object.values(boss.charge.opportunities);if(counts.some(n=>n<2)){const out=b.stepEnemy();assert.equal(out.events.find(e=>e.event==='enemy_action').skill,'charge_maintain');}else break;}while(!b._canRelease(boss)){const u=b.current;if(u.side==='ally')b.act('guard',u.id);else b.stepEnemy();}assert.ok(Object.values(boss.charge.opportunities).every(n=>n>=2));});
test('save/restore preserves seeded RNG, projectiles, response ledger and outcomes',()=>{const {b}=projectiles();const saved=b.snapshot();const restored=Engine.restore(params,saved);assert.deepEqual(restored.snapshot(),saved);for(let i=0;i<12&&!b.result;i++){assert.deepEqual(restored.autoAction(),b.autoAction());assert.deepEqual(restored.snapshot(),b.snapshot());}});
test('save format rejects changed parameters, methods, static stats, references and old versions',()=>{const b=battle();const mutations=[s=>s.version=3,s=>s.state.getUnit='hijack',s=>s.state.allies[0].resist.havoc=0,s=>s.state.allies[0].form='godmode',s=>s.state.queue.push('ghost'),s=>s.state.rngState=-1,s=>s.state.allies[0].status.guard={owner:'ghost',slotBound:true},s=>s.state.allies[0].ap=99,s=>s.state.result={outcome:'win'}];for(const mutate of mutations){const s=b.snapshot();mutate(s);assert.throws(()=>Engine.restore(params,s));}const p=clone(params);p.characters.amy.energy_cap=126;assert.throws(()=>Engine.restore(p,b.snapshot()));});
test('public previews never expose ordinary intent or leak a second normal action',()=>{const b=battle();const e=b.enemies.find(x=>x.key==='bracer');assert.equal(b.enemyIntent(e).visible,false);assert.equal(b.enemyIntent(e).name,'行动未公开');const a=b.allies[0];focus(b,a);assert.equal(b.availableActions(a.id).filter(x=>x.key==='A').length,0);assert.ok(b.availableActions(a.id).some(x=>x.key==='rover_spectro_a'));});
test('seeded critical roll is shared by every original packet in one root',()=>{const b=battle({stochastic:true,seed:913});const a=b.allies[0],t=b.enemies[0];focus(b,a);a.bp=3;a.cr=1;const expected=b._previewClone();expected._random();const out=b.act('A',t.id,{bp:3});assert.equal(b.rngState,expected.rngState);assert.equal(out.events.filter(e=>e.event==='damage'&&e.kind==='original').length,4);assert.ok(out.events.filter(e=>e.event==='damage'&&e.kind==='original').every(e=>e.crit));});
test('saved random stream replays actual critical-enabled commands identically',()=>{const b=battle({stochastic:true,seed:20261010,enemy_hp_scale:4});for(let i=0;i<6;i++)b.autoAction();const c=Engine.restore(params,b.snapshot());for(let i=0;i<24&&!b.result;i++){assert.deepEqual(b.autoAction(),c.autoAction());assert.equal(b.rngState,c.rngState);}assert.deepEqual(b.snapshot(),c.snapshot());});
test('snapshot rejects missing normal slots and forged state clocks',()=>{const b=battle();for(const mutate of [s=>s.state.queue.pop(),s=>s.state.fields={},s=>s.state.allies[0].cooldowns.unknown=3,s=>s.state.allies[0].actedRound=-1,s=>s.state._roleStatusSerial=-1]){const save=b.snapshot();mutate(save);assert.throws(()=>Engine.restore(params,save));}});
test('defense ends at the next owner slot; it is independent of a round-expiry buff',()=>{const b=battle();const a=b.allies[0];focus(b,a);b.act('guard',a.id);assert.ok(a.status.guard);const before=a.hp;b.damage(b.enemies[0],a,{base:100,element:'spectro',kind:'original'});assert.ok(before-a.hp<=50);while(b.currentId!==a.id){const u=b.current;u.side==='enemy'?b.stepEnemy():b.act('guard',u.id);}assert.equal(a.status.guard,undefined);assert.equal(b.currentId,a.id);});
test('despawning a still-living projectile clears its statuses and keeps save valid',()=>{const {b,boss,ps}=projectiles();const Effects=require('../../skill-effects');Effects.applyAbnormal(b,b.allies[0],ps[0],'spectro_frazzle',1,{active:false});assert.ok(ps[0].status.spectro_frazzle);b.applyQ(b.allies[0],boss,80);assert.equal(ps[0].retreated,true);assert.deepEqual(ps[0].status,{});assert.equal(b.validate(),true);assert.deepEqual(Engine.restore(params,b.snapshot()).snapshot(),b.snapshot());});
test('Crownless strong binding suppresses only the next counter, not the entire stance',()=>{const b=battle({team:['rover_spectro','lynae'],encounter:'boss',enemy_hp_scale:10}),boss=b.enemies[0],a=b.allies[0],second=b.allies[1];b.addStatus(boss,'counter_stance',{owner:boss.id,coef:2.3,suppressed:false,slotBound:true});assert.equal(b.control(a,boss,'bind'),true);assert.equal(boss.status.counter_stance.suppressedUses,1);focus(b,a);b.queue=[second.id,boss.id];const first=b.act('A',boss.id);assert.equal(first.events.filter(x=>x.event==='counter_suppressed').length,1);assert.equal(first.events.filter(x=>x.event==='counter').length,0);assert.equal(boss.status.counter_stance.suppressedUses,0);const next=b.act('A',boss.id);assert.equal(next.events.filter(x=>x.event==='counter').length,1);});
