'use strict';
module.exports=function(C){const {assert,path,root,O,test,close,eventRows,fixture,setTurn,act}=C;const FX=require(path.join(root,'skill-effects.js'));
 const body=(r,t)=>(r.events||[]).filter(x=>x.event==='damage'&&x.kind==='original'&&x.target===t.id).reduce((v,x)=>v+x.hpDamage,0);
 function refill(e,a){a.sp=a.maxsp;a.bp=5;setTurn(e,a);}
 for(const p of O.profiles)for(const s of p.skills)for(const v of s.conditional_variants||[])for(let bp=0;bp<4;bp++)test(`variant:${p.key}:${s.id}:${v.name}:BP${bp}`,()=>{
  const {e,a,t}=fixture(p.key);a.energy=a.energyCap;act(e,a,'R1',t);refill(e,a);a.energy=0;const n=v.numeric_audit,sp=a.sp,q=t.q;const r=act(e,a,s.id,t,{bp,choice:s.id==='E3'&&p.key==='denia'?'exile':undefined});assert.equal(sp-a.sp,n.sp);close(q-t.q,n.q_by_bp[bp]);assert.equal(eventRows(r,'original_attack').length,n.original_attacks_by_bp[bp]);let expected=0;for(let i=0;i<n.original_attacks_by_bp[bp];i++)expected+=Math.floor(a.atk*(n.role_class==='basic'?n.damage_atk_by_bp[0]*(i?.4:1):n.damage_atk_by_bp[bp]/n.original_attacks_by_bp[bp]));assert.equal(body(r,t),expected);assert.equal(a.energy,0);assert.ok(a.r2Pending);assert.equal(a.form,p.key==='amy'?'mech':'blue');
 });
 for(const who of ['mornye','chisa'])for(let bp=0;bp<4;bp++)for(const choice of ['attack','healing'])test(`healing branch:${who}:${choice}:BP${bp}`,()=>{
  const {e,a,t,b}=fixture(who);if(who==='mornye'){act(e,a,'E2',t);refill(e,a);}a.hp=1;b.hp=1;const ah=a.hp,bh=b.hp,q=t.q;const r=act(e,a,who==='mornye'?'E3':'E2',t,{bp,choice,allyTargetId:b.id});const scale=choice==='attack'?1:(who==='mornye'?[1,1.25,1.5,1.75]:[1,1.3,1.55,1.75])[bp];const heal=Math.floor((who==='mornye'?60+.55*a.def:35+.35*a.atk)*scale);assert.equal(a.hp-ah,heal);assert.equal(b.hp-bh,heal);const coef=(who==='mornye'?1.2:1.15)*(choice==='healing'?1:[1,1.4,1.75,2.05][bp]);assert.equal(body(r,t),Math.floor(coef*(who==='mornye'?a.def:a.atk)));close(q-t.q,(who==='mornye'?[8,10.8,12.8,14.4]:[7,9.5,11.2,12.6])[bp]);
 });
 test('Mornye repeated equal support gives no free base energy',()=>{const {e,a,t,b}=fixture('mornye');act(e,a,'E5',t);refill(e,a);a.cooldowns.E5=e.round;a.energy=0;b.energy=0;act(e,a,'E5',t);assert.equal(a.energy,0);assert.equal(b.energy,0);});
 test('Chisa heal requires successful hit, Aero paid heal survives all misses',()=>{let f=fixture('chisa');f.b.hp=1;act(f.e,f.a,'E2',f.t,{forceMiss:true,choice:'healing',bp:3});assert.equal(f.b.hp,1);f=fixture('rover_aero');f.b.hp=1;act(f.e,f.a,'rover_aero_e1',f.t,{forceMiss:true,bp:3});assert.ok(f.b.hp>1);});
 test('Denia red-only group cannot include giant immune Boss',()=>{const {e,a,t}=fixture('denia',{encounter:['crownless','snip']});act(e,a,'E1',t);assert.ok(!t.status.denia_group);assert.ok(e.enemies[1].status.denia_group);});
 test('Denia field exactly two round-end pulses, preserves red form after R2',()=>{const {e,a,t}=fixture('denia',{modes:{denia:'strain'}});a.energy=a.energyCap;act(e,a,'R1',t);refill(e,a);const r=act(e,a,'R2',t,{bp:3});assert.equal(r.events.filter(x=>x.event==='damage'&&x.kind==='field').length,0);assert.equal(a.form,'red');for(let i=0;i<3;i++){const start=e.log.length;e._endRound();const rows=e.log.slice(start).filter(x=>x.event==='damage'&&x.kind==='field');assert.equal(rows.length,i<2?e.enemies.length:0);e.round++;}assert.ok(!a.status.denia_field);assert.equal(a.form,'red');});
 test('Denia ally Break response exists only with explicit preexisting strain mark',()=>{const {e,a,t,b}=fixture('denia',{modes:{denia:'strain'}});act(e,a,'A',t);t.q=1;refill(e,b);const r=act(e,b,'A',t);assert.equal(eventRows(r,'break')[0].source,b.id);const responses=r.events.filter(x=>x.event==='damage'&&x.kind==='response');assert.equal(responses.length,1);assert.equal(responses[0].source,a.id);assert.ok(!t.status.strain_shift);});
 test('Mornye new observation cannot retroactively claim same-hit Break',()=>{const {e,a,t}=fixture('mornye');act(e,a,'E2',t);refill(e,a);t.q=1;const r=act(e,a,'E4',t);assert.equal(eventRows(r,'break').length,1);assert.ok(!t.status.mornye_interference);assert.ok(t.status.mornye_observation);});
 test('Mornye preexisting observation supports ally Break exactly once',()=>{const {e,a,t,b}=fixture('mornye');act(e,a,'E2',t);refill(e,a);act(e,a,'E4',t);refill(e,b);t.q=1;const r=act(e,b,'A',t,{bp:3});assert.ok(t.status.mornye_interference);assert.equal(t.status.mornye_interference.amount,.12);assert.ok(!t.status.mornye_observation);assert.equal(r.events.filter(x=>x.event==='damage'&&x.kind==='response').length,0);});
 test('Bound runs after shield; full absorption consumes zero charges',()=>{const {e,a,t,b}=fixture('mornye');act(e,a,'E1',t,{allyTargetId:b.id});delete b.status.mornye_guard;e.shield(a,b,10000,2);const hp=b.hp;e.damage(t,b,{base:5000,element:'spectro',kind:'original',rootActionId:999,attackId:999});assert.equal(b.hp,hp);assert.equal(b.status.mornye_bound.uses,3);});
 test('Bound third cap immediately heals exactly once and is not immortality',()=>{const {e,a,t,b}=fixture('mornye');act(e,a,'E1',t,{allyTargetId:b.id});delete b.status.mornye_guard;for(let i=0;i<3;i++){const hp=b.hp;const start=e.log.length;e.damage(t,b,{base:10000,element:'spectro',kind:'original',rootActionId:990+i,attackId:990+i});const heals=e.log.slice(start).filter(x=>x.event==='heal');assert.equal(heals.length,i===2?1:0);if(i<2)assert.equal(b.status.mornye_bound.uses,2-i);else assert.ok(!b.status.mornye_bound);}e.damage(t,b,{base:10000,kind:'original'});assert.equal(b.hp,0);});
 test('guard mitigation bounded before shield and counter only once after enemy root',()=>{const {e,a,t,b}=fixture('mornye');act(e,a,'E1',t,{allyTargetId:b.id});delete b.status.mornye_bound;const cap=1.2*a.def;e.shield(a,b,10000,2);const shield=b.status.barrier.amount;const raw=1000;const d=e.damage(t,b,{base:raw,element:'spectro',kind:'original',rootActionId:999,attackId:999});const K=100+5*t.level,nominal=Math.floor(raw*K/(K+b.def)*.9);const expected=Math.floor(nominal-Math.min(nominal*.6,cap));assert.equal(d.shieldDamage,expected);assert.equal(shield-b.status.barrier.amount,expected);const start=e.log.length;FX.afterEnemyRoot(e,{actor:t,rootActionId:999,kind:'original',completed:true});FX.afterEnemyRoot(e,{actor:t,rootActionId:999,kind:'original',completed:true});assert.equal(e.log.slice(start).filter(x=>x.event==='damage'&&x.kind==='counter').length,1);});
 test('Lynae coordinated attack crits independently with own CR',()=>{const {e,a,t,b}=fixture('lynae',{stochastic:true});a.cr=1;b.cr=0;act(e,a,'E5',t,{allyTargetId:b.id});refill(e,b);const r=act(e,b,'A',t,{bp:3});assert.ok(r.events.filter(x=>x.event==='damage'&&x.kind==='original').every(x=>!x.crit));assert.ok(r.events.filter(x=>x.event==='damage'&&x.kind==='coordinated').every(x=>x.crit));});
 test('public preview of consumable enhancement is snapshot/RNG neutral',()=>{const {e,a,t}=fixture('amy',{stochastic:true});act(e,a,'E4',t);refill(e,a);const before=e.snapshot();for(let i=0;i<4;i++){e.previewPacket(a,t,'E2',{bp:i});e.availableActions(a.id,i);}assert.deepEqual(e.snapshot(),before);});
 test('Amy fusion Break and E3 do not detonate same existing pool twice',()=>{const {e,a,t}=fixture('amy',{modes:{amy:'fusion'}});FX.applyAbnormal(e,a,t,'fusion_burst',4,{active:true});t.q=1;const r=act(e,a,'E3',t);assert.equal(eventRows(r,'break').length,1);assert.equal(eventRows(r,'fusion_burst').length,1);assert.ok(!t.status.fusion_burst);});
 test('Denia E3 secondary targets get explicit side coefficient and zero Q',()=>{const {e,a,t}=fixture('denia',{encounter:['bracer','bracer','bracer']});act(e,a,'E1',t);refill(e,a);a.energy=a.energyCap;act(e,a,'R1',t);refill(e,a);const q=e.enemies.map(x=>x.q);const r=act(e,a,'E3',t,{bp:3,choice:'exile',targetIds:e.enemies.slice(1).map(x=>x.id)});assert.equal(eventRows(r,'original_attack').length,1);close(q[0]-t.q,18);for(let i=1;i<3;i++){close(q[i]-e.enemies[i].q,0);assert.equal(body(r,e.enemies[i]),Math.floor(.65*2.05*a.atk));}});
 test('Denia E4 group extension grants Q once to each selected member',()=>{const {e,a,t}=fixture('denia',{encounter:['bracer','bracer','bracer']});act(e,a,'E1',t);refill(e,a);const q=e.enemies.map(x=>x.q);const r=act(e,a,'E4',t,{bp:3,targetIds:e.enemies.slice(1).map(x=>x.id)});assert.equal(eventRows(r,'original_attack').length,1);for(let i=0;i<3;i++){close(q[i]-e.enemies[i].q,18);assert.equal(body(r,e.enemies[i]),Math.floor(2.9725*a.atk));}});
 test('Denia spill consumes only valid single-root group attack, capped once not per hit',()=>{const {e,a,t,b}=fixture('denia');act(e,a,'E1',t);refill(e,a);act(e,a,'E5',b,{bp:0,targetIds:[b.id]});assert.ok(b.status.denia_spill);refill(e,b);const r=act(e,b,'A',t,{bp:3});const spills=r.events.filter(x=>x.event==='damage'&&x.category==='spill');assert.equal(spills.length,1);assert.equal(spills[0].damage,Math.floor(Math.min(2.2*b.atk*.2,.6*a.atk)));assert.ok(!b.status.denia_spill);assert.equal(eventRows(r,'original_attack').length,4);});
 test('Electro marrow is not consumed by derived Aero conversion',()=>{const {e,a,t,b}=fixture('rover_aero');e.addStatus(a,'electro_marrow',{id:'electro_marrow',roleEffect:true,ownerId:b.id,sourceId:b.id,expires:e.round+1,amount:24});FX.applyAbnormal(e,b,t,'spectro_frazzle',3,{active:false});a.sp=0;FX.convertAbnormal(e,a,t,'spectro_frazzle');assert.equal(a.sp,0);assert.ok(a.status.electro_marrow);});
 test('expired capacity trims fusion stacks without triggering burst',()=>{const {e,a,t}=fixture('amy');FX.addCapacity(e,a,t,'fusion_burst',1,1,'qa');FX.applyAbnormal(e,a,t,'fusion_burst',5,{active:true});const before=e.log.length;e._endRound();assert.equal(t.status.fusion_burst.stacks,5);assert.equal(e.log.slice(before).filter(x=>x.event==='fusion_burst').length,0);});

};
