'use strict';
module.exports=function(C){
 const {assert,Engine,P,test,close,eventRows,construct,setTurn,act}=C;
 function bossFixture(key='dreamless',team=['amy','lynae','mornye','chisa']){const e=construct(team,{encounter:[key],enemy_atk_scale:0});e.start();const b=e.enemies[0];b.hp=b.maxhp=1e7;for(const a of e.allies){a.bp=5;a.sp=a.maxsp;}return {e,b,a:e.allies[0]};}
 function enemyTurn(e,b){setTurn(e,b);const r=e.stepEnemy();assert.equal(r.ok,true,r.reason);return r;}
 function special(){const f=bossFixture();f.b.firstBreakRecovered=true;const r=enemyTurn(f.e,f.b);assert.equal(eventRows(r,'spawn').length,2);return f;}
 test('boss capacities exactly 112 and 156',()=>{assert.equal(bossFixture('crownless').b.maxq,112);assert.equal(bossFixture().b.maxq,156);});
 test('Crownless transform consumes slot without free attack',()=>{const {e,b,a}=bossFixture('crownless');enemyTurn(e,b);b.hp=b.maxhp*.70+1;e.damage(a,b,{base:10,element:'fusion',kind:'original'});assert.ok(b.phasePending);assert.equal(b.phase,1);const hp=e.allies.map(x=>x.hp),r=enemyTurn(e,b);assert.equal(b.phase,2);assert.equal(eventRows(r,'enemy_action')[0].skill,'transform');assert.deepEqual(e.allies.map(x=>x.hp),hp);});
 test('Crownless stance once per BP3 root, not removed by weak attack',()=>{const {e,b,a}=bossFixture('crownless');b.phase=2;b.mainActions=2;b.cooldowns.wing_charge=e.round+99;enemyTurn(e,b);assert.ok(b.status.counter_stance);const r=act(e,a,'A',b,{bp:3});assert.equal(eventRows(r,'original_attack').length,4);assert.equal(eventRows(r,'counter').length,1);assert.ok(b.status.counter_stance);const r2=act(e,e.allies[1],'A',b);assert.equal(eventRows(r2,'counter').length,1);});
 test('Crownless high-pressure charge immune to bind, interruptible by Break',()=>{const {e,b,a}=bossFixture('crownless');b.phase=2;b.mainActions=2;enemyTurn(e,b);assert.ok(b.charge);const before=JSON.stringify(b.charge);assert.equal(e.control(a,b,'bind'),false);assert.equal(JSON.stringify(b.charge),before);e.applyQ(a,b,b.q);assert.equal(b.q,0);assert.equal(b.charge,null);assert.ok(b.breakPending);assert.equal(eventRows(enemyTurn(e,b),'enemy_action')[0].skill,'break_recover');assert.equal(b.q,b.maxq);});
 test('Break loses exactly one enemy main action',()=>{const {e,b,a}=bossFixture('crownless');b.mainActions=1;e.applyQ(a,b,b.q);assert.equal(eventRows(enemyTurn(e,b),'enemy_action')[0].skill,'break_recover');assert.notEqual(eventRows(enemyTurn(e,b),'enemy_action')[0].skill,'break_recover');});
 test('Dreamless first Break recovery then dedicated special preparation',()=>{const {e,b,a}=bossFixture();e.applyQ(a,b,156);let r=enemyTurn(e,b);assert.equal(eventRows(r,'enemy_action')[0].skill,'break_recover');assert.equal(eventRows(r,'spawn').length,0);r=enemyTurn(e,b);assert.equal(eventRows(r,'enemy_action')[0].skill,'projectiles');assert.equal(eventRows(r,'spawn').length,2);assert.equal(eventRows(r,'damage').length,0);});
 test('Dreamless carries Q into special, below-half entry immediately interrupts',()=>{const {e,b,a}=bossFixture();b.firstBreakRecovered=true;e.applyQ(a,b,79);assert.equal(b.q,77);enemyTurn(e,b);assert.equal(b.q,77);assert.equal(b.bossState,'special_interrupted');assert.equal(e.living('enemy').filter(x=>x.mechanicUnit).length,0);});
 test('Dreamless exact78 not interrupted, 77.9 interrupted',()=>{const {e,b,a}=special();e.applyQ(a,b,78);assert.equal(b.q,78);assert.equal(b.bossState,'projectiles');e.applyQ(a,b,.1);assert.equal(b.q,77.9);assert.equal(b.bossState,'special_interrupted');assert.equal(e.living('enemy').filter(x=>x.mechanicUnit).length,0);});
 test('Dreamless each projectile reflects54.6 once, leftover attacks cancel',()=>{const {e,b,a}=special();const ps=e.living('enemy').filter(x=>x.mechanicUnit);a.atk=2000;const r=act(e,a,'A',ps[0],{bp:3});assert.equal(eventRows(r,'reflection').length,1);assert.equal(eventRows(r,'original_attack').length,1);close(b.q,101.4);assert.equal(b.bossState,'projectiles');e.damage(a,ps[0],{base:99999});close(b.q,101.4);const other=e.allies[1];other.atk=2000;const r2=act(e,other,'A',ps[1],{bp:3});assert.equal(eventRows(r2,'reflection').length,1);close(b.q,46.8);assert.equal(b.bossState,'special_interrupted');assert.equal(e.living('enemy').filter(x=>x.mechanicUnit).length,0);});
 test('Dreamless direct Q interrupt requires zero reflections',()=>{const {e,b,a}=special();e.applyQ(a,b,80);assert.equal(b.bossState,'special_interrupted');assert.equal(e.log.filter(x=>x.event==='reflection').length,0);});
 test('Dreamless Q0 merges special interruption and Break into one recovery',()=>{const {e,b,a}=special();e.applyQ(a,b,156);assert.ok(b.breakPending);assert.equal(b.bossState,'special_interrupted');assert.equal(eventRows(enemyTurn(e,b),'enemy_action')[0].skill,'break_recover');assert.ok(b.specialDone);assert.equal(b.q,156);assert.ok(!['break_recover','special_recover'].includes(eventRows(enemyTurn(e,b),'enemy_action')[0].skill));});
 test('Dreamless residual Q frozen until no-damage recovery ends',()=>{const {e,b,a}=special();e.applyQ(a,b,80);const q=b.q;e.applyQ(a,b,10);assert.equal(b.q,q);const r=enemyTurn(e,b);assert.equal(eventRows(r,'damage').length,0);assert.equal(b.q,q);assert.equal(b.phase,2);assert.ok(b.specialDone);});
 test('Dreamless all four allies obtain two normal responses before release',()=>{const {e,b}=special();let released=false,maintains=0;const count=Object.fromEntries(e.allies.map(a=>[a.id,0]));for(let i=0;i<30&&!released;i++){
  if(e.current.side==='ally'){const a=e.current;assert.equal(e.act('guard',a.id,{bp:0}).ok,true);count[a.id]++;}
  else{const saved={...b.charge?.opportunities},r=e.stepEnemy(),skill=eventRows(r,'enemy_action')[0]?.skill;if(skill==='charge_maintain')maintains++;if(skill==='charge_release'){released=true;for(const a of e.allies)assert.ok(saved[a.id]>=2,`${a.key} only ${saved[a.id]} responses`);}}
 }assert.ok(released);for(const a of e.allies)assert.ok(count[a.id]>=2);});
 test('Dreamless downed actor does not prolong response window',()=>{const {e,b}=special(),slow=e.allies[2];for(const a of e.allies)b.charge.opportunities[a.id]=a===slow?0:2;assert.equal(e._canRelease(b),false);e.damage(b,slow,{base:1e9,kind:'original'});assert.equal(e._canRelease(b),true);});
 test('Dreamless special ignores bind with no window extension',()=>{const {e,b,a}=special(),before=JSON.stringify(b.charge);assert.equal(e.control(a,b,'bind'),false);assert.equal(JSON.stringify(b.charge),before);});
 test('projectiles targetable, no slots, immune control/heal/revive',()=>{const {e,b,a}=special();for(const p of e.enemies.filter(x=>x.mechanicUnit)){assert.ok(e.availableActions(a.id,0).find(x=>x.key==='A').targets.includes(p.id));assert.ok(!e.queue.includes(p.id));assert.equal(e.control(a,p,'pull'),false);assert.equal(e.control(a,p,'bind'),false);p.hp=1;assert.equal(e.heal(a,p,100),0);p.hp=0;assert.equal(e.revive(p,100),false);}});
 test('Dreamless death cancels projectiles and prevents post-victory damage',()=>{const {e,b,a}=special();e.damage(a,b,{base:1e10,kind:'original'});assert.equal(e.living('enemy').length,0);const hp=e.allies.map(x=>x.hp);assert.equal(e.stepEnemy().ok,false);assert.deepEqual(e.allies.map(x=>x.hp),hp);});
 test('special snapshot preserves spawned units and response counts',()=>{const e=construct(['amy','lynae','mornye','chisa'],{encounter:'dreamless'});e.start();const b=e.enemies[0];e.applyQ(e.allies[0],b,b.q);e.stepEnemy();for(let i=0;i<20&&b.bossState!=='projectiles';i++){if(e.current.side==='enemy')e.stepEnemy();else e.act('guard',e.current.id,{bp:0});}assert.equal(b.bossState,'projectiles');const snap=JSON.parse(JSON.stringify(e.snapshot()));const restored=Engine.restore(P,snap);assert.deepEqual(restored.snapshot(),snap);assert.equal(restored.enemies.filter(x=>x.mechanicUnit).length,2);});
 test('Crownless normal bind suppresses exactly next stance counter, not remaining stance',()=>{const {e,b,a}=bossFixture('crownless');b.phase=2;b.mainActions=2;b.cooldowns.wing_charge=e.round+99;enemyTurn(e,b);assert.equal(e.control(a,b,'bind'),true);const first=act(e,a,'A',b);assert.equal(eventRows(first,'counter').length,0);const second=act(e,e.allies[1],'A',b);assert.equal(eventRows(second,'counter').length,1);assert.ok(b.status.counter_stance);});

};
