'use strict';
// Actual test.4 app+engine+role effects under jsdom. This is DOM/state evidence,
// not screenshot, canvas rasterization, real media decoding, or browser evidence.
const assert=require('node:assert/strict');
const {boot}=require('./ui_harness.cjs');
const {IDBFactory}=require('../independent/v02/node_modules/fake-indexeddb');
const checks=[];
const check=(name,fn)=>{fn();checks.push(name);};
const snapshot=h=>h.w.BattleLabDiagnostics.getSnapshot();
const unit=(h,key)=>snapshot(h).state.allies.find(u=>u.key===key);
async function dbRecord(factory,name,key,value){const db=await new Promise((res,rej)=>{const r=factory.open(name,1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});const result=await new Promise((res,rej)=>{const tx=db.transaction('records',arguments.length>3?'readwrite':'readonly');const r=arguments.length>3?tx.objectStore('records').put(value,key):tx.objectStore('records').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});db.close();return result;}
async function load(h,options,mutate){const e=new h.w.BattleEngine(h.w.BATTLE_PARAMETERS,options);e.start();if(mutate)mutate(e);e.validate();const p=h.w.BattleLabDiagnostics.getProject();p.battle=e.snapshot();h.click('#assetsBtn');h.click('[data-tab="project"]');await h.import('#importProject','scenario-test4.json',JSON.stringify(p));assert(!h.$('#assetStatus').textContent.includes('失败'),h.$('#assetStatus').textContent);h.click('[data-close="assetDialog"]');await h.tick();await h.until(()=>!h.diag().busy&&snapshot(h).state.allies.some(u=>u.id===h.diag().current),100);}
function open(h,category){if(!h.diag().menuOpen)h.click('#actorTrigger');if(h.diag().menuCategory!=='root')h.click('#menuBackBtn');h.click('[data-category="'+category+'"]');}
async function confirm(h){await h.frame(250);assert(!h.$('#confirmBtn').disabled,h.$('#previewText').textContent);h.click('#confirmBtn');}
(async()=>{
const factory=new IDBFactory(),legacySentinel={schema:'battle-engine-v1',keep:'test.3 unchanged'};
await dbRecord(factory,'resonant-encounter-lab-v1','battle',legacySentinel);
const h=await boot(factory);
try{
check('eight stats and BP/SP/energy, no obsolete action bars',()=>{assert.equal(h.w.document.querySelectorAll('#partyCards .base-stats').length,4);for(const card of h.w.document.querySelectorAll('.base-stats'))assert.deepEqual([...card.querySelectorAll('dt')].map(n=>n.textContent),['HP','SP','ATK','DEF','SPD','CR','CDMG','ER']);assert.equal(h.w.document.querySelectorAll('.ap-meter,.bar.concerto').length,0);assert(!h.$('#partyCards').textContent.includes('协奏'));});
h.click('#actorTrigger');check('six independent command entries',()=>assert.deepEqual([...h.w.document.querySelectorAll('[data-category]')].map(x=>x.textContent.replace('›','')),['战斗','技能','道具','防御','交涉','逃跑']));
h.click('[data-category="battle"]');h.$('[data-action="A"]').focus();const zero=h.$('#detailBody').textContent;h.click('[data-bp="1"]');const one=h.$('#detailBody').textContent;check('BP selection updates root budget and true hit preview',()=>{assert.match(zero,/6 Q \/ 1 次/);assert.match(one,/8.1 Q \/ 2 次/);assert.equal(h.w.document.activeElement.dataset.bp,'1');});
const before=JSON.stringify(snapshot(h));h.click('[data-action="A"]');h.click('#cancelBtn');check('cancel is state-neutral',()=>assert.equal(JSON.stringify(snapshot(h)),before));h.click('[data-action="A"]');check('ordinary-target forecast shows zero Q',()=>assert.match(h.$('#previewText').textContent,/0 本目标 Q（普通敌无共振）/));await confirm(h);h.click('#confirmBtn');check('double confirm commits one normal action',()=>{const s=snapshot(h).state;assert.equal(s.log.filter(x=>x.event==='action_commit'&&x.actor==='ally:1:lynae').length,1);assert.equal(unit(h,'lynae').bp,0);assert.notEqual(s._currentId,'ally:1:lynae');});
await h.until(()=>!h.diag().busy,30);check('battle log exposes real energy receipts in Chinese',()=>{assert.match(h.$('#battleLog').textContent,/共享能量 \+/);assert.match(h.$('#battleLog').textContent,/第 2 次原始攻击/);assert(!/slot_start|original_attack|successful_hit|action_end/.test(h.$('#battleLog').textContent));});
h.click('#setupBtn');check('one Rover slot with four configurations and independent outfit',()=>{assert.equal(h.w.document.querySelectorAll('#teamChoices input[value="rover"]').length,1);assert.equal(h.w.document.querySelectorAll('#roverBattleMode option').length,4);assert.equal(h.w.document.querySelectorAll('[data-appearance="rover"] option').length,4);});h.click('[data-close="setupDialog"]');
await load(h,{team:['amy'],encounter:['bracer'],level:20,initialEnergy:{amy:125},initialBP:{amy:1},enemy_hp_scale:100,enemy_atk_scale:0});
open(h,'skills');check('R1 occupies the one R entry',()=>{assert.equal(h.w.document.querySelectorAll('[data-action="R"]').length,1);assert.equal(h.w.document.querySelectorAll('[data-action="R1"],[data-action="R2"]').length,0);assert.match(h.$('[data-action="R"]').textContent,/过载/);});h.click('[data-action="R"]');await confirm(h);await h.until(()=>!h.diag().busy&&h.diag().current?.includes('amy'),100);open(h,'skills');h.$('[data-action="R"]').focus();check('same R becomes R2 with no second energy gate',()=>{assert.match(h.$('[data-action="R"]').textContent,/终结/);assert.match(h.$('#detailBody').textContent,/3BP|3 BP/);assert.equal(unit(h,'amy').energy,0);assert.equal(unit(h,'amy').r2Pending,true);assert.equal(h.$('[data-action="R"]').getAttribute('aria-disabled'),'true');});
// Persist a valid R2 fixture with enough BP; no fake full-energy refill.
await load(h,{team:['amy'],encounter:['bracer'],level:20,enemy_hp_scale:100,enemy_atk_scale:0},e=>{e.current.bp=3;e.current.energy=0;e.current.r2Pending=true;e.current.energyLocked=true;e.current.form='mech';});open(h,'skills');h.click('[data-bp="3"]');h.click('[data-action="R"]');check('MAX R2 target preview uses three BP once',()=>{assert.equal(h.$('#confirmBtn').disabled,false);assert.match(h.$('#previewText').textContent,/3 BP/);});await confirm(h);check('R2 finishes at zero energy and exits qualification',()=>{assert.equal(unit(h,'amy').r2Pending,false);assert.equal(unit(h,'amy').energyLocked,false);assert.equal(unit(h,'amy').bp,0);assert.equal(unit(h,'amy').form,'human');});
await h.until(()=>!h.diag().busy,30);
await load(h,{team:['lynae','amy'],encounter:['bracer'],level:20,enemy_hp_scale:100,enemy_atk_scale:0});open(h,'skills');h.$('[data-action="E5"]').focus();check('Lynae support explicitly applies only to the next R command',()=>assert.match(h.$('#detailBody').textContent,/只适用于下一次 R \/ R1 \/ R2，不适用于解放分类 E 或蓝态普攻/));h.click('[data-action="E5"]');check('enemy plus other-ally target is separately selectable',()=>{assert(h.$('#allyTargetSelect'));assert.equal(h.$('#allyTargetSelect').options.length,1);assert.notEqual(h.$('#allyTargetSelect').value,h.diag().current);});await confirm(h);check('two-target options arrive at authored role effect',()=>assert(unit(h,'amy').status.lynae_chase));await h.until(()=>!h.diag().busy,30);
await load(h,{team:['chisa'],encounter:['snip','predator'],initialBP:{chisa:3},enemy_hp_scale:100,enemy_atk_scale:0},e=>{for(const t of e.enemies)h.w.SkillEffects.applyAbnormal(e,e.allies[0],t,'spectro_frazzle',2);});open(h,'skills');h.click('[data-bp="1"]');h.click('[data-action="E6"]');check('per-enemy capacity selections are visible, not implicit',()=>{assert.equal(h.w.document.querySelectorAll('[data-extra-target]').length,2);assert.equal(h.w.document.querySelectorAll('[data-target-abnormal]').length,2);assert.equal(h.$('#confirmBtn').disabled,true);});h.$('[data-extra-target]').click();check('one legal target makes capacity confirmable',()=>assert.equal(h.$('#confirmBtn').disabled,false));h.click('#cancelBtn');
await load(h,{team:['rover_aero'],encounter:['bracer'],initialBP:{rover_aero:1},enemy_hp_scale:100,enemy_atk_scale:0},e=>{h.w.SkillEffects.applyAbnormal(e,e.allies[0],e.enemies[0],'spectro_frazzle',2);});open(h,'skills');h.click('[data-action="rover_aero_e3"]');h.change('#abnormalChoice','spectro_frazzle');check('conversion preview gives the actual transfer and new owner',()=>{assert.match(h.$('#previewText').textContent,/移走 2 层/);assert.match(h.$('#previewText').textContent,/原异常剩 0 层/);assert.match(h.$('#previewText').textContent,/风蚀变为 2 \/ 3/);});h.click('#cancelBtn');
// Explicit current-snapshot fixture tests expiry display without relying on the
// unrelated duration or source-cleanup mechanics under separate engine tests.
await load(h,{team:['amy','lynae'],encounter:['bracer'],enemy_hp_scale:100,enemy_atk_scale:0},e=>{const owner=e.allies[0];const put=(u,k,name,expires,extra)=>{u.status[k]={id:k,key:k,name,description:h.w.SkillEffects.describeStatus(k,extra),roleEffect:true,ownerId:owner.id,sourceId:owner.id,expires,token:++e._roleStatusSerial,order:++e._roleOrder,appliedRound:e.round,...extra};};put(e.allies[1],'amy_escort','护航',e.round,{uses:1,reduction:.25,capCoef:.60,activeRoot:null});put(owner,'amy_quick','迅应',null,{uses:1});h.w.SkillEffects.applyAbnormal(e,owner,e.enemies[0],'spectro_frazzle',2);});await h.frame();check('status icons are placed correctly, number-free and keyboard readable',()=>{const icon=h.$('#partyCards [data-status="amy_escort"]');assert(icon.classList.contains('expiring'));assert(!/\d/.test(icon.textContent));icon.focus();assert.match(h.$('#statusTooltip').textContent,/来源：爱弥斯/);assert.match(h.$('#statusTooltip').textContent,/剩余 1 回合/);assert.match(h.$('#statusTooltip').textContent,/剩余 1 次/);assert(!h.$('[data-status="amy_quick"]').classList.contains('expiring'));assert(h.$('#enemyStatusLayer [data-status="spectro_frazzle"]'));assert(!h.$('#enemyCards [data-status="spectro_frazzle"]'));});
check('ordinary next move stays undisclosed',()=>assert(!h.$('#enemyCards').textContent.includes('普通攻击')));
await load(h,{team:['lynae'],encounter:['predator'],enemy_hp_scale:100,enemy_atk_scale:0},e=>e._prepareCharge(e.enemies[0],'charge',1));check('common-enemy charge does not advertise unavailable Q breaking',()=>{assert.match(h.$('#enemyCards').textContent,/危险预警/);assert(!h.$('#enemyCards').textContent.includes('共振击破可中断'));assert(!h.$('#tacticalNotice').textContent.includes('共振击破可中断'));});
await load(h,{team:['lynae'],encounter:['snip'],enemy_hp_scale:.001,enemy_atk_scale:0});open(h,'battle');h.click('[data-action="A"]');await confirm(h);await h.until(()=>!h.diag().busy,30);check('victory totals use actual HP damage, not event counts',()=>{assert.equal(h.diag().result.outcome,'win');assert.match(h.$('#resultOverlay').textContent,/我方实际 HP 伤害 1 \/ 治疗量 0/);});
await h.tick();check('no DOM runtime errors',()=>assert.deepEqual(h.errors,[]));assert.deepEqual(await dbRecord(factory,'resonant-encounter-lab-v1','battle'),legacySentinel);checks.push('legacy database is untouched');
console.log(JSON.stringify({suite:'test4-ui-contract',passed:checks.length,checks,limits:['jsdom; no real browser layout/raster/media evidence']},null,2));
}finally{h.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
