'use strict';
const assert=require('node:assert/strict');const {boot}=require('./ui_harness.cjs');
(async()=>{const h=await boot();try{
// Natural deterministic battle only: no resource, phase, mechanic or status injection.
const e=new h.w.BattleEngine(h.w.BATTLE_PARAMETERS,{team:['amy','lynae','mornye','denia'],encounter:'dreamless',level:20,difficulty:'standard'});e.start();let steps=0;while(!e.result&&!e.living('enemy').some(u=>u.mechanicUnit)&&steps<200){const result=e.current.side==='enemy'?e.stepEnemy():e.autoAction();assert(result.ok,result.reason);steps++;}const projectiles=e.living('enemy').filter(u=>u.mechanicUnit);assert.equal(projectiles.length,2,'natural route did not reach projectiles');assert.equal(e.current.side,'ally');e.validate();const p=h.w.BattleLabDiagnostics.getProject();p.battle=e.snapshot();h.click('#assetsBtn');h.click('[data-tab="project"]');await h.import('#importProject','natural-projectile-battle.json',JSON.stringify(p));h.click('[data-close="assetDialog"]');await h.tick();await h.frame();
const layouts=[];const overlaps=(a,b)=>a.left<b.left+b.width&&a.left+a.width>b.left&&a.top<b.top+b.height&&a.top+a.height>b.top;for(const [W,H]of [[900,400],[884,514],[530,360]]){h.$('#battleCanvas').getBoundingClientRect=()=>({left:0,top:0,width:W,height:H,right:W,bottom:H});h.texts.length=0;await h.frame(1000);const bounds=h.w.BattleLabDiagnostics.getStageLayout().bounds,markers=projectiles.map(u=>bounds.find(b=>b.id===u.id));for(const m of markers){assert(m,'mechanic sprite absent');assert(m.left>=16&&m.top>=16&&m.left+m.width<=W-16&&m.top+m.height<=H-16,'mechanic outside stage');for(const b of bounds.filter(b=>b!==m))assert(!overlaps(m,b),'mechanic hidden by '+b.id);assert.equal(m.y,H*.80);}assert.equal(markers[0].x,W*.13);assert(Math.abs(markers[1].x-W*.30)<1e-9);const labels=h.texts.filter(x=>x.canvas==='battleCanvas').map(x=>x.text);assert(labels.filter(x=>x==='耐久 HP 180 / 180').length>=2,'mechanic HP durability labels absent');assert(!labels.some(x=>/0 \/ 0/.test(x)),'fake Q0/0 on mechanic');layouts.push({W,H,markers:markers.map(m=>({left:m.left,top:m.top,width:m.width,height:m.height}))});}
for(const u of projectiles){assert.equal(h.$('[data-portrait-unit="'+u.id+'"]'),null,'mechanic unit appeared in action order');assert(h.$('[data-enemy-status="'+u.id+'"]'),'mechanic feet missing');assert(h.$('#enemyCards').textContent.includes(u.name),'mechanic enemy card missing');}
h.click('#actorTrigger');h.click('[data-category="battle"]');h.click('[data-action="A"]');for(const u of projectiles)assert(h.$('[data-target="'+u.id+'"]'),'mechanic is not selectable');const target=h.$('[data-target="'+projectiles[1].id+'"]');target.click();assert.equal(h.diag().targetId,projectiles[1].id);assert.deepEqual(h.errors,[]);console.log(JSON.stringify({suite:'test4-ui-projectile-queue',naturalBattle:true,stepsToSpawn:steps,round:e.round,projectiles:projectiles.length,noMechanicsInCurrentRemainingOrNextOrder:true,enemyCardsFeetAndSelectionPreserved:true,twoMarkersVisibleWithoutOverlap:true,hpDurabilityInsteadOfFakeQ:true,layouts},null,2));
}finally{h.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
