'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const {boot,fixtures}=require('./ui_harness.cjs');
const checks=[];const check=(name,fn)=>{fn();checks.push(name);};
(async()=>{const h=await boot();try{
h.click('#assetsBtn');
check('visual workbench retains sixteen calibration controls and source inspection',()=>{assert.equal(h.w.document.querySelectorAll('[data-cal]').length,16);assert(h.$('#inspectSpriteBtn'));assert(h.$('#applyFormCalibration'));assert(h.$('#resetCalibration'));});
const slot=h.$('#assetSlot').value;await h.import('#spriteFile','qa_checkerboard.png');h.input('[data-cal="scale"]','1.25');check('custom sprite and calibration remain independent of combat',()=>{const p=h.w.BattleLabDiagnostics.getProject();assert.match(p.overrides[slot].data,/^data:image\/png;base64,/);assert.equal(p.calibration[slot].scale,1.25);});
h.click('[data-tab="background"]');await h.import('#backgroundFile','qa_checkerboard.png');h.change('#backgroundFit','contain');h.input('#backgroundOpacity','0.65');check('background import and fitting still work',()=>{const p=h.w.BattleLabDiagnostics.getProject();assert.equal(p.background.fit,'contain');assert.equal(p.background.opacity,.65);assert.equal(p.background.name,'qa_checkerboard.png');});
h.click('[data-tab="audio"]');await h.import('[data-audio="bgm"]','qa_chime.wav');check('local audio import and controls retained',()=>{assert.match(h.w.BattleLabDiagnostics.getProject().audio.bgm.data,/^data:audio\/wav;base64,/);assert(h.$('[data-play="bgm"]'));assert(h.$('#masterVolume'));assert(h.$('#stopAudio'));});
h.click('[data-tab="project"]');h.click('#exportProject');const exported=JSON.parse(await h.downloads.at(-1).blob.text());check('portable new project exports new combat schema and parameter fingerprint',()=>{assert.equal(exported.schema,'resonant-project-test4');assert.equal(exported.version,4);assert.equal(exported.battle.schema_version,'battle-v04');assert(exported.battle.parameter_fingerprint);assert.equal(exported.battle.parameter_fingerprint,h.w.BattleEngine.parameterFingerprint(h.w.BATTLE_PARAMETERS));assert(exported.overrides[slot]);assert(exported.audio.bgm);assert.equal(exported.calibration[slot].scale,1.25);});
const before=JSON.stringify(h.w.BattleLabDiagnostics.getProject());const snapshotBefore=JSON.stringify(h.w.BattleLabDiagnostics.getSnapshot());const bad=JSON.parse(JSON.stringify(exported));bad.overrides[slot].data='https://remote.invalid/private.png';await h.import('#importProject','remote-rejected.json',JSON.stringify(bad));check('remote media rejection is atomic',()=>{assert.equal(JSON.stringify(h.w.BattleLabDiagnostics.getProject()),before);assert.equal(JSON.stringify(h.w.BattleLabDiagnostics.getSnapshot()),snapshotBefore);assert.match(h.$('#toast').textContent,/素材类型/);});
const altered=JSON.parse(JSON.stringify(exported));altered.battle.parameter_fingerprint='wrong';await h.import('#importProject','bad-fingerprint.json',JSON.stringify(altered));check('parameter-mismatched combat is rejected without replacing current state',()=>{assert.equal(JSON.stringify(h.w.BattleLabDiagnostics.getSnapshot()),snapshotBefore);assert.match(h.$('#toast').textContent,/存档版本.*不兼容/);});
const old=JSON.parse(JSON.stringify(exported));old.schema='resonant-project-v1';old.version=1;old.battle={schema:'battle-engine-v1',parameter_version:'0.3.0-candidate',state:{ap:6,concerto:100}};old.battleConfig.team=['rover','amy'];old.battleConfig.mode={rover:'electro',amy:'tune'};old.appearance.rover='female_school';await h.import('#importProject','old-test3-project.json',JSON.stringify(old));check('explicit legacy import preserves checked media/settings and maps only one Rover',()=>{const p=h.w.BattleLabDiagnostics.getProject();assert.equal(p.schema,'resonant-project-test4');assert.deepEqual([...p.battleConfig.team],['rover_electro','amy']);assert.equal(p.appearance.rover,'female_school');assert.equal(p.battleConfig.mode.amy,'rupture');assert(p.overrides[slot]);assert(p.audio.bgm);assert.equal(p.calibration[slot].scale,1.25);assert.match(h.$('#migrationNotice').textContent,/旧战局不续接/);const s=h.w.BattleLabDiagnostics.getSnapshot();assert.equal(s.schema_version,'battle-v04');assert(s.state.allies.every(u=>!('ap' in u)&&!('concerto' in u)));});
const restored=await boot(h.db);try{check('new namespace restores imported assets and newly initialized legal battle',()=>{assert(restored.w.BattleLabDiagnostics.getProject().overrides[slot]);assert.equal(restored.w.BattleLabDiagnostics.getProject().appearance.rover,'female_school');assert.equal(restored.w.BattleLabDiagnostics.getSnapshot().schema_version,'battle-v04');assert.deepEqual(restored.errors,[]);});}finally{restored.close();}
check('no DOM runtime errors',()=>assert.deepEqual(h.errors,[]));console.log(JSON.stringify({suite:'test4-ui-migration',passed:checks.length,checks,limits:['jsdom codec doubles; real browser media and persistence need browser verification']},null,2));
}finally{h.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
