'use strict';
const assert=require('node:assert/strict');const {boot}=require('./ui_harness.cjs');
const checks=[];const check=(name,fn)=>{fn();checks.push(name);};
const state=h=>h.w.BattleLabDiagnostics.getSnapshot().state;
const unit=(h,key)=>state(h).allies.find(u=>u.key===key);
async function load(h,options,mutate){const e=new h.w.BattleEngine(h.w.BATTLE_PARAMETERS,options);e.start();mutate?.(e);e.validate();const p=h.w.BattleLabDiagnostics.getProject();p.battle=e.snapshot();h.click('#assetsBtn');h.click('[data-tab="project"]');await h.import('#importProject','branch-fixture.json',JSON.stringify(p));assert(!h.$('#toast').textContent.includes('失败'),h.$('#toast').textContent);h.click('[data-close="assetDialog"]');await h.tick();await h.until(()=>!h.diag().busy&&state(h).allies.some(u=>u.id===h.diag().current),100);}
function open(h,cat){h.click('#actorTrigger');h.click('[data-category="'+cat+'"]');}
async function confirm(h){await h.frame(250);assert.equal(h.$('#confirmBtn').disabled,false,h.$('#previewText').textContent);h.click('#confirmBtn');}
// Construct authored, validator-accepted group fixtures to isolate the UI's
// target and option plumbing. The effects themselves have independent tests.
function grouped(e){const owner=e.allies.find(u=>u.key==='denia');for(const t of e.enemies){const k='denia_group';t.status[k]={id:k,key:k,name:'归群',description:'同组联动',roleEffect:true,ownerId:owner.id,sourceId:owner.id,expires:e.round+1,token:++e._roleStatusSerial,order:++e._roleOrder,appliedRound:e.round,groupId:'ui-fixture-group'};}}
(async()=>{const h=await boot();try{
await load(h,{team:['denia'],encounter:['snip','snip','snip'],enemy_hp_scale:100,enemy_atk_scale:0},e=>{grouped(e);const a=e.allies[0];a.r2Pending=true;a.energyLocked=true;a.energy=0;a.form='blue';});open(h,'skills');h.click('[data-action="E3"]');const baseSP=unit(h,'denia').sp;check('Denia branch and grouped extra targets are reachable',()=>{assert.equal(h.$('#actionChoice').options.length,2);assert.equal(h.w.document.querySelectorAll('[data-extra-target]').length,2);assert.match(h.$('#previewText').textContent,/18 SP/);});h.change('#actionChoice','exile');check('exile branch previews its true additional SP cost',()=>assert.match(h.$('#previewText').textContent,/24 SP/));for(const input of [...h.w.document.querySelectorAll('[data-extra-target]')]){h.$('[data-extra-target="'+input.dataset.extraTarget+'"]').click();}await confirm(h);check('extra target and exile options reach the real engine',()=>{assert.equal(unit(h,'denia').sp,baseSP-24);const hits=state(h).log.filter(l=>l.event==='successful_hit');assert.equal(new Set(hits.map(l=>l.target)).size,3);});await h.until(()=>!h.diag().busy,30);
await load(h,{team:['denia','amy'],encounter:['snip','snip','snip'],enemy_hp_scale:100,enemy_atk_scale:0},grouped);open(h,'skills');h.click('[data-bp="1"]');h.click('[data-action="E5"]');check('Denia E5 shows two independently selected allies at 1 BP',()=>{assert.equal(h.w.document.querySelectorAll('[data-extra-target]').length,2);assert.match(h.$('#targetOptions').textContent,/1–2名/);});for(const input of [...h.w.document.querySelectorAll('[data-extra-target]')])h.$('[data-extra-target="'+input.dataset.extraTarget+'"]').click();await confirm(h);check('multi-ally support is granted to each selected recipient',()=>{assert(unit(h,'denia').status.denia_spill);assert(unit(h,'amy').status.denia_spill);});await h.until(()=>!h.diag().busy&&h.diag().current.includes('amy'),50);open(h,'battle');h.click('[data-action="A"]');check('active spill support exposes a fixed secondary target',()=>{assert(h.$('#spillTargetSelect'));assert.equal(h.$('#spillTargetSelect').options.length,2);});const secondary=h.$('#spillTargetSelect').options[1].value;h.change('#spillTargetSelect',secondary);await confirm(h);check('selected spill target is preserved through commit',()=>{assert(state(h).log.some(l=>l.event==='damage'&&l.category==='spill'&&l.target===secondary));});await h.until(()=>!h.diag().busy,30);
await load(h,{team:['amy','mornye','chisa'],encounter:['snip'],enemy_hp_scale:100,enemy_atk_scale:0},e=>{while(e.current.key!=='amy'){if(e.current.side==='enemy')e.stepEnemy();else e.act('guard',e.currentId,{bp:0});}});open(h,'skills');h.click('[data-action="E5"]');check('single other-ally support uses one target picker',()=>{assert.equal(h.$('#allyTargetSelect'),null);assert.equal(h.w.document.querySelectorAll('[data-target]').length,2);});const allyTarget=[...h.w.document.querySelectorAll('[data-target]')].find(n=>n.textContent.includes('千咲'));allyTarget.click();await confirm(h);check('other-ally selection is not overwritten by a hidden default',()=>{assert(unit(h,'chisa').status.amy_escort);assert(!unit(h,'mornye').status.amy_escort);});await h.until(()=>!h.diag().busy,30);
check('no DOM runtime errors',()=>assert.deepEqual(h.errors,[]));console.log(JSON.stringify({suite:'test4-ui-target-branches',passed:checks.length,checks,limits:['validator-accepted fixtures under jsdom; no browser layout claim']},null,2));
}finally{h.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
