'use strict';
// Runs the actual shipped engine. Scenario fixtures are deliberately synthetic;
// their passing asserts rule semantics, not encounter balance or visual quality.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../../engine.js'),P=require('../../parameters.json');
const clone=x=>JSON.parse(JSON.stringify(x));const results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.message);}}
function fixture(team=['lynae','amy','mornye','chisa'],enemy='crownless') {let p=clone(P);p.enemies[enemy].hp=30000;p.enemies[enemy].atk=10;p.enemies[enemy].speed=10;team.forEach((k,i)=>p.characters[k].speed=120-i*10);const b=new E(p,{team,encounter:[enemy]});b.start();return b;}
function turn(b,id){let n=0;while(!b.result&&b.currentId!==id&&n++<50){if(b.current.side==='enemy')b.stepEnemy();else b.end();}assert.equal(b.currentId,id);}
function rejectAtomic(b,fn){const pre=b.snapshot(),r=fn();assert.equal(r.ok,false);assert.deepEqual(b.snapshot(),pre);}
test('opening AP4 and concerto20, no duplicate start recovery',()=>{let b=fixture();b.start();for(let a of b.allies){assert.equal(a.ap,4);assert.equal(a.concerto,20);}assert.equal(b.round,1);});
test('two repeatable2AP attacks and automatic window close',()=>{let b=fixture(),a=b.current,t=b.enemies[0];assert(b.act('basic',t.id).ok);assert.equal(b.currentId,a.id);assert.equal(a.ap,2);assert(b.act('basic',t.id).ok);assert.notEqual(b.currentId,a.id);assert.equal(a.window_actions,2);assert.equal(a.concerto_gain_round,40);});
test('normal AP carry, round+4 and overflow cap6',()=>{let b=fixture(),a=b.current;b.act('basic',b.enemies[0].id);b.end();turn(b,a.id);assert.equal(b.round,2);assert.equal(a.ap,6);b.end();turn(b,a.id);assert.equal(a.ap,6);assert(b.count.ap_recovery_overflow>=4);});
test('6+2 allows four2AP attacks and temporary is paid first',()=>{let b=fixture(),a=b.current;a.ap=6;a.temp_ap=2;a.relay_pending=true;a.status.outro={amp:.2,liberation_extra:0,expires:2,window_bound:true};let t=b.enemies[0];for(let i=0;i<4;i++){assert(b.act('basic',t.id).ok);if(i===0){assert.equal(a.ap,6);assert.equal(a.temp_ap,0);assert(a.relay_pending);}}assert.equal(a.window_actions,4);assert.equal(a.ap,0);assert.equal(a.concerto_gain_round,40);});
test('outro requires current actor and previous paid action',()=>{let b=fixture(),a=b.current,t=b.allies[1];a.concerto=100;rejectAtomic(b,()=>b.concerto(a.id,t.id));rejectAtomic(b,()=>b.concerto(t.id,a.id));b.act('basic',b.enemies[0].id);assert(b.concerto(a.id,t.id).ok);assert.equal(t.temp_ap,2);assert(t.relay_pending);assert.equal(a.acted_round,1);});
test('outro cannot self target or stack on pending receiver',()=>{let b=fixture(),a=b.current;a.concerto=100;b.act('basic',b.enemies[0].id);rejectAtomic(b,()=>b.concerto(a.id,a.id));const t=b.allies[1];t.relay_pending=true;t.temp_ap=2;t.status.outro={amp:.2,liberation_extra:0,expires:2,window_bound:true};rejectAtomic(b,()=>b.concerto(a.id,t.id));});
test('late relay waits until receiver next window, then expires',()=>{let b=fixture(),a=b.current,donor=b.allies[1];b.end();assert.equal(b.currentId,donor.id);donor.concerto=100;b.act('basic',b.enemies[0].id);b.concerto(donor.id,a.id);assert.equal(a.acted_round,1);assert(!b.queue.includes(a.id));turn(b,a.id);assert.equal(b.round,2);assert.equal(a.temp_ap,2);b.end();assert.equal(a.temp_ap,0);assert(!a.relay_pending);assert(!a.status.outro);});
test('just-filled concerto retains zeroAP window to choose outro',()=>{let b=fixture(),a=b.current;a.concerto=60;b.act('basic',b.enemies[0].id);b.act('basic',b.enemies[0].id);assert.equal(a.ap,0);assert.equal(a.concerto,100);assert.equal(b.currentId,a.id);assert(b.concerto(a.id,b.allies[1].id).ok);});
test('buff persists across two paid sub-actions',()=>{let b=fixture(),a=b.current,t=b.enemies[0];a.temp_ap=2;a.relay_pending=true;a.status.outro={amp:.2,liberation_extra:0,expires:2,window_bound:true};b.act('basic',t.id);b.act('basic',t.id);assert(a.status.outro);assert(b.log.filter(e=>e.event==='damage'&&e.actor===a.id).every(e=>e.amp_applied===.2));});
test('only current actor can issue paid action and rejection is atomic',()=>{let b=fixture();rejectAtomic(b,()=>b.act('not_a_skill',b.enemies[0].id));rejectAtomic(b,()=>b.act('basic',b.allies[1].id));rejectAtomic(b,()=>b.act('spectrum',b.enemies[0].id));});
test('support once/window and field can combine with taunt',()=>{let b=fixture(['mornye','lynae']),a=b.current;a.rsc.calibration=100;assert(b.act('field',a.id).ok);assert.equal(a.ap,2);rejectAtomic(b,()=>b.act('field',a.id));assert(b.act('taunt',b.enemies[0].id).ok);assert.equal(a.ap,1);});
test('empty heal consumes cost but gives no concerto',()=>{let b=fixture(['mornye','lynae']),a=b.current;a.rsc.calibration=30;let c=a.concerto;b.act('heal',a.id);assert.equal(a.concerto,c);assert.equal(a.rsc.calibration,0);assert.equal(a.ap,2);});
test('guard1AP ends window and survives until next owner window',()=>{let b=fixture(),a=b.current;assert(b.act('guard',a.id).ok);assert.equal(a.ap,3);assert(a.status.guard);turn(b,a.id);assert(!a.status.guard);});
test('all common enemies have zero resonance',()=>{for(let e of Object.values(P.enemies))if(e.rank==='common')assert.equal(e.shield,0);});
test('skill resonance not weapon/element weakness',()=>{let b=fixture(),a=b.current,t=b.enemies[0],before=t.shield;b.act('survey',t.id);assert.equal(before-t.shield,24);assert.equal(a.rsc.color,0);assert.equal(b.isweak(a,t),false);});
test('Lynae resource break and output alternatives use same60color',()=>{let b=fixture(),a=b.current;a.rsc.color=60;const x=b.getSkill(a,'skate'),y=b.getSkill(a,'spectrum');assert.deepEqual(x.cost,y.cost);assert.equal(x.resonance_damage,40);assert.equal(y.resonance_damage,8);assert(x.coef<y.coef);b.act('skate',b.enemies[0].id);assert.equal(a.rsc.color,0);rejectAtomic(b,()=>b.act('skate',b.enemies[0].id));});
test('break before enemy slot skips current round only',()=>{let b=fixture(),a=b.current,t=b.enemies[0];t.shield=24;b.act('survey',t.id);assert.equal(t.skip_round,1);while(b.round===1&&!b.result)b.current.side==='ally'?b.end():b.stepEnemy();assert.equal(b.count.skipped_enemy_actions,1);assert.equal(t.shield,t.maxshield);assert.equal(t.recovery_lock,false);});
test('break after enemy slot skips following round only',()=>{let p=clone(P);p.enemies.crownless.speed=200;p.enemies.crownless.hp=30000;const b=new E(p,{team:['lynae'],encounter:'boss'});b.start();b.stepEnemy();const t=b.enemies[0];t.shield=24;b.act('survey',t.id);assert.equal(t.skip_round,2);b.end();assert.equal(b.round,2);assert.equal(b.count.skipped_enemy_actions,1);});
test('already broken has no1.5damage bonus',()=>{let b=fixture(),a=b.current,t=b.enemies[0];const base=b.previewDamage(a,'basic',t).amount;t.broken_until=1;t.skip_round=1;t.shield=0;let before=t.hp;b.act('basic',t.id);assert.equal(before-t.hp,base);});
test('joint budget respects participant elements and DEF',()=>{let b=fixture(),t=b.enemies[0],a=b.current;t.shield=24;t.immune_elements=['fusion'];const before=b.allies[1].concerto;b.act('survey',t.id);assert.equal(b.count.joint_attacks,1);assert.equal(b.allies[1].concerto,before);assert(b.log.some(e=>e.event==='immune'&&e.actor===b.allies[1].id));assert(b.log.filter(e=>e.damage_source==='joint').every(e=>!e.status_damage));});
test('joint never consumes special status-outro token',()=>{let b=fixture(),t=b.enemies[0],a=b.allies[3];a.status.status_outro={amp:.25,expires:2,window_bound:true};t.shield=24;b.act('survey',t.id);assert(a.status.status_outro);});
test('ordinary intent cannot reveal next skill or target',()=>{let b=fixture(),i=b.enemyIntent(b.enemies[0]);assert(i.hidden);assert.equal(i.key,null);assert.deepEqual(i.targets,[]);});
test('committed charge target cannot be retargeted by taunt',()=>{let b=fixture(),t=b.enemies[0];t.status.charge={expires:3,target:b.allies[2].id};t.pattern_i=2;rejectAtomic(b,()=>b.act('taunt',t.id));assert.equal(b._enemyTarget(t).id,b.allies[2].id);assert(b.enemyIntent(t).committed);});
test('feint is contextual cost1 and does not damage or give resources',()=>{let b=fixture(),a=b.current,t=b.enemies[0];rejectAtomic(b,()=>b.act('feint',t.id));t.status.brace={expires:3,target:a.id,used:false};let hp=t.hp,c=a.concerto;b.act('feint',t.id);assert.equal(a.ap,3);assert.equal(t.hp,hp);assert.equal(a.concerto,c);assert(!t.status.brace);});
test('parts consume2AP and do not damage body or give resources',()=>{let b=fixture(),a=b.current,t=b.enemies[0];t.part={...clone(t.part_spec),hp:1,destroyed:false};t.status.charge={expires:3,target:a.id};t.pattern_i=2;let hp=t.hp,q=t.shield,c=a.concerto;b.act('disrupt_part',t.id);assert.equal(a.ap,2);assert.equal(t.hp,hp);assert.equal(t.shield,q);assert.equal(a.concerto,c);assert(!t.status.charge);assert.equal(b.count.parts_destroyed,1);});
test('every element has explicit resistance and immune prism remains0damage',()=>{for(let e of Object.values(P.enemies))assert.deepEqual(Object.keys(e.resist).sort(),Object.keys(P.elements).sort());for(let el of ['fusion','spectro','aero','havoc']){const p=clone(P);p.characters.rover.mode_default=el;let b=new E(p,{team:[el==='fusion'?'amy':'rover'],modes:{rover:el},encounter:[el+'_prism']});b.start();let t=b.enemies[0],before=t.hp;b.act('basic',t.id);assert.equal(t.hp,before);assert.equal(b.current.concerto,20);}});
test('four Rover modes are one identity with distinct personal kits',()=>{for(let mode of P.characters.rover.mode_options){let b=new E(P,{team:['rover'],modes:{rover:mode},encounter:'normal'});assert.equal(b.allies[0].element,mode);assert.equal(b.allies[0].id,'ally:0:rover');assert.equal(b.allies[0].rsc.energy,0);E.restore(P,b.snapshot());}});
test('electro critical needs100surge and60concerto',()=>{let b=new E(P,{team:['rover'],modes:{rover:'electro'},encounter:'boss'});b.start();while(b.current.side==='enemy')b.stepEnemy();let a=b.current;a.rsc.surge=100;rejectAtomic(b,()=>b.act('enhanced',b.enemies[0].id));a.concerto=60;assert(b.act('enhanced',b.enemies[0].id).ok);assert(a.status.critical);assert.equal(a.rsc.surge,0);});
test('snapshot rejects old schema/version',()=>{let b=fixture(),x=b.snapshot();x.schema='battle-engine-v1';assert.throws(()=>E.restore(b.params,x));x=b.snapshot();x.parameter_version='0.2.0-candidate';assert.throws(()=>E.restore(b.params,x));});
for(const [field,val] of [['ap',7],['ap',-1],['ap',2.5],['temp_ap',3],['temp_ap',1],['relay_pending','yes'],['window_actions',9],['concerto_gain_round',41],['atk',999999],['skip_round',10]])test('snapshot rejects '+field+'='+val,()=>{let b=fixture(),x=b.snapshot();x.state.allies[0][field]=val;assert.throws(()=>E.restore(b.params,x));});
test('snapshot rejects fake new skill and repeated once/window marker',()=>{let b=fixture(),x=b.snapshot();x.state.allies[0].window_skills={'evil':1};x.state.allies[0].window_actions=1;assert.throws(()=>E.restore(b.params,x));});
test('live battle replay restores every paid action identically',()=>{let b=new E(P,{team:['amy','lynae','mornye','chisa'],encounter:'boss',auto_concerto:true});b.start();for(let i=0;i<300&&!b.result;i++){const restored=E.restore(P,b.snapshot()),a=b.autoAction(),r=restored.autoAction();assert.deepEqual(a,r);assert.deepEqual(b.snapshot(),restored.snapshot());}assert(b.result);});
for(const mode of P.characters.rover.mode_options)test('lethal retaliation cancels remaining Rover effects '+mode,()=>{let p=clone(P);p.characters.rover.speed=200;p.enemies.bracer.hp=30000;p.enemies.bracer.atk=9999;let b=new E(p,{team:['rover','mornye'],modes:{rover:mode},encounter:['bracer']});b.start();const a=b.current,t=b.enemies[0];a.hp=1;a.rsc[a.primary]=100;a.concerto=60;t.status.brace={expires:3,target:a.id,used:false};assert(b.act('enhanced',t.id).ok);assert.equal(a.hp,0);assert.deepEqual(a.status,{});assert(!t.status.spectro_mark&&!t.status.wind_mark);assert(!b.log.some(e=>e.event==='heal'));E.restore(p,b.snapshot());});
test('AOE stops on source lethal retaliation and cannot hit later enemies',()=>{let p=clone(P);p.characters.denia.speed=200;p.enemies.bracer.hp=30000;p.enemies.bracer.atk=9999;let b=new E(p,{team:['denia','chisa'],encounter:['bracer','snip']});b.start();const a=b.current,t=b.enemies[0],second=b.enemies[1];a.hp=1;t.status.brace={expires:3,target:a.id,used:false};let before=second.hp;assert(b.act('stage',t.id).ok);assert.equal(a.hp,0);assert.equal(second.hp,before);assert(!t.status.fusion);E.restore(p,b.snapshot());});
test('phase threshold announces the AOE before next-round transition',()=>{let b=fixture(),t=b.enemies[0];t.phase_pending=true;let before=b.snapshot(),i=b.enemyIntent(t);assert(i.dangerous&&i.phaseWarning&&i.committed);assert.equal(i.key,'wingpulse');assert.deepEqual(i.targets,b.living('ally').map(a=>a.id));assert.deepEqual(b.snapshot(),before);});
test('a committed descent warning takes priority over phase announcement',()=>{let b=fixture(),t=b.enemies[0];t.phase_pending=true;t.status.charge={expires:3,target:b.allies[0].id};t.pattern_i=2;let i=b.enemyIntent(t);assert.equal(i.key,'descent');assert(!i.phaseWarning);});
test('lethal Rover counter interrupts enemy AOE and attached debuffs',()=>{let p=clone(P);p.characters.rover.speed=300;p.characters.amy.speed=200;p.enemies.crownless.speed=100;p.enemies.crownless.difficulty_patterns.standard=['sweep'];let b=new E(p,{team:['rover','amy'],modes:{rover:'electro'},encounter:'boss'});b.start();const [a,next]=b.allies,t=b.enemies[0];t.hp=1;assert(b.act('counter',a.id).ok);assert(b.end().ok);let hp=next.hp;assert(b.stepEnemy().ok);assert.equal(t.hp,0);assert.equal(next.hp,hp);assert(!next.status.exposed);assert(!a.status.exposed);assert.equal(b.result.outcome,'win');const ko=b.log.findIndex(e=>e.event==='incapacitated'&&e.unit===t.id);assert(!b.log.slice(ko+1).some(e=>e.event==='damage'&&e.actor===t.id));E.restore(p,b.snapshot());});
test('counter really takes0.6 damage and preview agrees, not0.65',()=>{let p=clone(P);p.characters.rover.speed=300;p.characters.amy.speed=200;p.enemies.crownless.speed=100;p.enemies.crownless.difficulty_patterns.standard=['sweep'];let b=new E(p,{team:['rover','amy'],modes:{rover:'electro'},encounter:'boss'});b.start();const a=b.current,t=b.enemies[0];assert(b.act('counter',a.id).ok);b.end();const k=120+4*t.level,expected=Math.floor(t.atk*t.skills.sweep.coef*k/(k+a.def)*.6);assert.equal(b.previewPacket(t,a,t.skills.sweep.coef,t.element),expected);const hp=a.hp;b.stepEnemy();assert.equal(hp-a.hp,expected);const packet=b.log.find(e=>e.event==='damage'&&e.actor===t.id&&e.target===a.id);assert.equal(packet.mitigation,.6);});
test('dead damage sources cannot produce any further packet',()=>{let b=fixture(),a=b.current,t=b.enemies[0];a.hp=0;b._kill(a);let hp=t.hp,n=b.log.length;assert.equal(b._damage(a,t,10),0);assert.equal(t.hp,hp);assert.equal(b.log.length,n);});
for(const setup of [{initialHP:{amy:0}},{hp_fraction:0},{initialHP:{amy:.5,lynae:0}}])test('initially incapacitated actors clear AP and concerto '+JSON.stringify(setup),()=>{let b=new E(P,{team:['amy','lynae'],encounter:'boss',...setup});for(const a of b.allies)if(a.hp===0){assert(a.dead);assert.equal(a.ap,0);assert.equal(a.concerto,0);assert.deepEqual(a.status,{});}E.restore(P,b.snapshot());b.start();E.restore(P,b.snapshot());if(b.allies.every(a=>a.dead)){assert.equal(b.result.outcome,'loss');assert.equal(b.round,0);}else{assert.equal(b.current.key,'lynae');assert(!b.queue.includes(b.allies[0].id));}});
const report={date:new Date().toISOString(),scope:'actual shipped engine; synthetic rule fixtures and one live-engine strategy replay; not browser or human playtest',total:results.length,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,results};
fs.writeFileSync(path.join(__dirname,'engine_ap_results.json'),JSON.stringify(report,null,2)+'\n');console.log(`${report.passed}/${report.total} rule tests passed`);if(report.failed)process.exitCode=1;
