// Exports real-engine initial-state DOM, not a rendered screenshot or playable build.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const {parseHTML}=require(process.env.LINKEDOM_PATH||'/tmp/wuwa-ui-test/node_modules/linkedom');
const root=path.resolve(__dirname,'..');const output=path.resolve(process.argv[2]||'readonly-preview.html');
const fixture=JSON.parse(cp.execFileSync('python',['-c',`import json,tempfile
from app import Lab
l=Lab(user=tempfile.mkdtemp());args={'candidate':'A','stage':'early','roles':['lynae','mornye','chisa']};p=l.profile(args);args['routes']={x['role_id']:x['allowed'][0] for x in p['profile']['required_choices']};args['encounter_id']='LIVE_BOSS_01_ALLY';b=l.create(args);print(json.dumps({'catalog':l.catalog(),'profile':p,'battle':b}))`],{cwd:root,encoding:'utf8',maxBuffer:40*1024*1024}));
const {document,window}=parseHTML(fs.readFileSync(path.join(root,'web/index.html'),'utf8'));const dialog=document.querySelector('dialog');dialog.showModal=()=>{};dialog.close=()=>{};
const box={document,window,console,setTimeout:()=>0,clearTimeout(){},Blob,URL,sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},fetch:()=>{throw Error('export must not fetch')},fixture};vm.createContext(box);
for(const name of ['rule-text.js','asset-catalog.js','technical-assets.js','technical-preview.js','visual-ui.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,'web/assets',name),'utf8').replace(/boot\(\);\s*$/,''),box);
vm.runInContext('catalog=fixture.catalog;candidate=catalog.candidates[0];profile=fixture.profile.profile;battle=fixture.battle;renderBattle()',box);
const V=vm.runInContext('VisualUI',box),labels={aemeath:'爱弥斯',lynae:'琳奈',mornye:'莫宁',denia:'达妮娅',chisa:'千咲'};
const appendix=document.createElement('section');appendix.className='panel';appendix.innerHTML='<h2>已核角色资料图标</h2>'+Object.entries(labels).map(([id,label])=>`<details><summary>${label}</summary>${V.portrait(id,label)}${V.gameTags(id)}${V.roleGallery(id)}</details>`).join('');document.querySelector('#app').append(appendix);
for(const button of document.querySelectorAll('button'))button.disabled=!button.hasAttribute('data-tech-action');
for(const select of document.querySelectorAll('select'))if(select.id!=='visual-style'&&!select.hasAttribute('data-tech-style'))select.disabled=true;
let imageCount=0;for(const image of document.querySelectorAll('img')){const src=image.getAttribute('src');if(!src?.startsWith('/assets/private-research/'))throw Error('unexpected image source');const p=path.join(root,'web',src.split('?')[0].slice(1));if(!fs.existsSync(p))throw Error('missing image '+src);const type=p.endsWith('.gif')?'image/gif':'image/webp';image.setAttribute('src',`data:${type};base64,${fs.readFileSync(p).toString('base64')}`);imageCount++;}
const css=fs.readFileSync(path.join(root,'web/assets/style.css'),'utf8');const body=document.querySelector('#app').outerHTML;
const technicalAssets=JSON.parse(JSON.stringify(vm.runInContext('TechnicalGIFAssets',box)));
for(const entries of Object.values(technicalAssets))for(const asset of Object.values(entries)){asset.src='data:image/gif;base64,'+fs.readFileSync(path.join(root,'web',asset.src.slice(1))).toString('base64');}
const technicalSource=fs.readFileSync(path.join(root,'web/assets/technical-preview.js'),'utf8');
const script='const OfflineTechnicalAssets='+JSON.stringify(technicalAssets)+';'+technicalSource+';TechnicalPreview.mount(document.querySelector(".technical-animation"),{assets:OfflineTechnicalAssets});document.querySelector("#visual-style").onchange=function(){document.querySelector(".battlefield-panel").dataset.style=this.value;};document.querySelector("#reduce-motion").onchange=function(){document.querySelector(".battlefield-panel").classList.toggle("reduced-motion",this.checked);};';
const html='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>鸣潮UI开发 · 技术动作离线预览</title><style>'+css+'</style><header class="panel"><h1>UI开发 · 技术动作离线预览</h1><p>真实引擎初始快照导出DOM，尚未完成浏览器布局验收。这不是游戏程序，所有战斗/皮肤按钮禁用；仅技术样片的待机、受击、施放及B/D切换可操作，不改变任何游戏状态。D v2为阶段候选，B比例仍待修。原角色图像仅私人研究。</p></header>'+body+'<script>'+script+'</script></html>';
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,html);const check=parseHTML(html).document;if(check.querySelectorAll('[data-actor="PLAYER_BODY_01"]').length!==1)throw Error('body duplication');if([...check.querySelectorAll('img')].some(i=>!i.src.startsWith('data:')))throw Error('external image dependency');if([...check.querySelectorAll('button')].some(b=>!b.disabled&&!b.hasAttribute('data-tech-action')))throw Error('game action enabled in preview');if(check.querySelectorAll('[data-tech-action]:not([disabled])').length!==3)throw Error('technical preview controls missing');if(check.querySelectorAll('script[src]').length)throw Error('external script dependency');console.log(JSON.stringify({output,imageCount,bytes:Buffer.byteLength(html),units:check.querySelectorAll('.battle-unit').length,battleReadonlyVerified:true,technicalControls:3,embeddedTechnicalGifs:6,realBrowserRendered:false}));
