'use strict';
// Actual app events and draw-call selection; mocked media/canvas is not browser pixel evidence.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),A=require('node:assert/strict');
const ROOT=process.env.QA_ROOT||process.cwd(),OUT=process.env.QA_OUT||__dirname;
const {boot,settle}=require(path.join(ROOT,'tests/independent/v03/dom_harness_v03.cjs'));
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex');
const files=['app.js','assets.js','assets/manifest.json','engine.js','parameters.js','tests/independent/v03/dom_harness_v03.cjs'],hashes=Object.fromEntries(files.map(f=>[f,hash(f)]));let results=[];
(async()=>{for(const form of ['male_default','male_school','female_default','female_school'])for(const mode of ['spectro','havoc','aero','electro'])for(const action of ['basic','skill']){let h;try{h=await boot();await settle(h);Object.defineProperty(h.$('#stage'),'clientWidth',{value:1000});Object.defineProperty(h.$('#stage'),'clientHeight',{value:600});h.$('#battleCanvas').getBoundingClientRect=()=>({left:0,top:0,width:1000,height:600});h.click('#setupBtn');for(const x of h.w.document.querySelectorAll('#teamChoices input'))x.checked=x.value==='rover';h.change('[data-appearance=rover]',form);h.change('[data-mode=rover]',mode);h.change('#difficultySelect','easy');h.click('#startBtn');await settle(h);await h.frame(40);let before=h.w.BattleLabDiagnostics.getSnapshot().state,a=before.allies[0],assets=h.w.BattleLabDiagnostics.assets,key=assets.forms.rover[form].actions[mode+'_'+action],s=assets.slots[key];if(!s?.src||s.pending){results.push({form,mode,action,status:'not_run_pending_asset',slot:key});continue;}A.notEqual(key,assets.forms.rover[form].idle);h.click('#actorTrigger');h.click('[data-category='+ (action==='basic'?'battle':'skills') +']');h.click('[data-action='+action+']');await h.frame(250);h.click('#confirmBtn');h.draws.length=0;await h.frame(200);let after=h.w.BattleLabDiagnostics.getSnapshot().state;A.equal(after.allies[0].ap,a.ap-a.skills[action].ap_cost);A.ok(after.log.some(x=>x.event==='action'&&x.actor===a.id&&x.skill===action));A.ok(h.draws.some(x=>x.canvas==='battleCanvas'&&x.src===s.src),form+'/'+mode+'/'+action+' missing action draw dispatch');A.equal(h.errors.length,0);results.push({form,mode,action,pass:true,slot:key,src:s.src,sha256:s.sha256});}catch(e){results.push({form,mode,action,pass:false,error:e.stack});}finally{h?.close();}}
const result={evidence:'Independent actual event-to-sprite draw dispatch with simulated Canvas/Image/Audio/IDB/clock. Does not certify pixels, rendering scale or real browser.',hashes,unchanged:files.every(f=>hash(f)===hashes[f]),passed:results.filter(x=>x.pass).length,failed:results.filter(x=>x.pass===false).length,notRun:results.filter(x=>x.status==='not_run_pending_asset').length,results};fs.writeFileSync(path.join(OUT,'asset_increment_e_independent_results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));process.exitCode=result.failed||!result.unchanged?1:0;})();
