'use strict';
// Independent event integration. Browser pixels, media and native default input are NOT certified.
const path=require('node:path'),fs=require('node:fs'),A=require('node:assert/strict'),crypto=require('node:crypto');
const ROOT=process.env.QA_ROOT||process.cwd(),OUT=process.env.QA_OUT||__dirname;
const {boot,settle,setup}=require(path.join(ROOT,'tests/independent/v03/dom_harness_v03.cjs'));
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex');let files=['app.js','index.html','style.css','engine.js','parameters.js','assets.js','tests/independent/v03/dom_harness_v03.cjs'],hashes=Object.fromEntries(files.map(f=>[f,sha(f)])),results=[];
const snapshot=h=>JSON.stringify(h.w.BattleLabDiagnostics.getSnapshot());
const key=(h,k,repeat=false)=>h.w.document.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:k,repeat,bubbles:true,cancelable:true}));
async function begin(){let h=await boot();await settle(h);let stage=h.$('#stage');Object.defineProperty(stage,'clientWidth',{configurable:true,value:1100});Object.defineProperty(stage,'clientHeight',{configurable:true,value:600});await h.frame(300);return h;}
function choose(h,action,category='battle'){h.click('#actorTrigger');h.click(`[data-category="${category}"]`);h.click(`[data-action="${action}"]`);}
async function check(name,fn){let h;try{h=await begin();await fn(h);A.equal(h.errors.length,0,JSON.stringify(h.errors));results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}finally{h?.close();}}
(async()=>{
await check('Target cycling, invalid blank and cancel are mutation-free across repeated menu opens',async h=>{let s=snapshot(h);for(let n=0;n<4;n++){choose(h,'basic');let targets=[...h.w.document.querySelectorAll('[data-target]')].map(x=>x.dataset.target);A.ok(targets.length>=2);for(let i=0;i<targets.length+1;i++){key(h,'ArrowRight');A.ok(targets.includes(h.diag().targetId));A.equal(snapshot(h),s);}key(h,'Escape');A.equal(h.diag().menuCategory,'battle');A.ok(h.diag().menuOpen);A.equal(snapshot(h),s);key(h,'Escape');key(h,'Escape');A.equal(h.diag().menuOpen,false);A.equal(snapshot(h),s);}});
await check('Blank click while targeting closes selection and depth without paying',async h=>{let s=snapshot(h);choose(h,'basic');h.$('#battleCanvas').dispatchEvent(new h.w.MouseEvent('click',{clientX:1,clientY:1,bubbles:true}));A.equal(h.diag().selected,null);A.equal(h.diag().menuOpen,false);A.ok(!h.$('#stage').classList.contains('focus-mode'));A.equal(snapshot(h),s);});
await check('Modal keyboard input cannot submit the pending battle action',async h=>{let s=snapshot(h);choose(h,'basic');await h.frame(250);h.click('#helpBtn');for(let k of ['ArrowLeft','Enter','Enter','Escape'])key(h,k);A.equal(snapshot(h),s);});
await check('All target-selection keyboard arrows are available and wrap',async h=>{choose(h,'basic');let start=h.diag().targetId;key(h,'ArrowRight');A.notEqual(h.diag().targetId,start);key(h,'ArrowLeft');A.equal(h.diag().targetId,start);key(h,'ArrowDown');A.notEqual(h.diag().targetId,start);key(h,'ArrowUp');A.equal(h.diag().targetId,start);});
await check('Rapid double confirmation pays one AP charge and one action',async h=>{let before=h.w.BattleLabDiagnostics.getSnapshot().state,id=before._currentId;choose(h,'basic');await h.frame(250);h.click('#confirmBtn');let committed=snapshot(h);for(let n=0;n<8;n++){h.click('#confirmBtn');key(h,'Enter',n%2===0);}A.equal(snapshot(h),committed);await settle(h);let after=h.w.BattleLabDiagnostics.getSnapshot().state;A.equal(after.log.filter(e=>e.event==='action'&&e.actor===id).length,1);A.equal(after.allies.find(a=>a.id===id).ap,before.allies.find(a=>a.id===id).ap-2);A.equal(h.diag().menuOpen,false);});
await check('Restart interrupts old action animation and stale completion',async h=>{choose(h,'basic');await h.frame(250);h.click('#confirmBtn');A.ok(h.diag().busy);h.click('#restartBtn');await settle(h);for(let i=0;i<10;i++)await h.next();let s=h.w.BattleLabDiagnostics.getSnapshot().state;A.equal(s.round,1);A.equal(s.log.filter(e=>e.event==='action').length,0);A.ok(s.allies.every(a=>a.ap===4));A.equal(h.diag().menuOpen,false);A.equal(h.diag().selected,null);A.equal(h.diag().busy,false);});
await check('Cancelled encounter edit preserves battle data',async h=>{let before=snapshot(h);h.click('#setupBtn');h.change('#encounterSelect','boss');h.change('#difficultySelect','challenge');h.click('[data-close="setupDialog"]');A.equal(snapshot(h),before);});
await check('Save/load clears stale selected action while preserving exact state',async h=>{choose(h,'basic');await h.frame(250);h.click('#confirmBtn');await settle(h);h.click('#saveBtn');await h.tick();await h.tick();let before=snapshot(h);choose(h,'basic');h.click('#resumeBtn');for(let i=0;i<8;i++)await h.tick();A.equal(snapshot(h),before);A.equal(h.diag().selected,null);A.equal(h.diag().targetId,null);A.equal(h.diag().menuOpen,false);});
await check('Battle menu keeps defense and item and excludes removed generic tricks',async h=>{h.click('#actorTrigger');let roots=[...h.w.document.querySelectorAll('[data-category]')].map(x=>x.dataset.category);A.ok(!roots.includes('defense')&&!roots.includes('items'));h.click('[data-category="battle"]');let keys=[...h.w.document.querySelectorAll('[data-action]')].map(x=>x.dataset.action);A.ok(keys.includes('guard'));A.ok(keys.includes('item_repair'));A.ok(!keys.includes('pry')&&!keys.includes('encourage'));});
await check('All original workbench sections remain reachable',async h=>{h.click('#assetsBtn');A.ok(h.$('#spriteFile'));for(let tab of ['background','audio','project','sprites']){h.click(`[data-tab="${tab}"]`);A.ok(h.$('#assetPanel').textContent.trim());}A.ok(h.$('#assetEntity'));A.ok(h.$('#assetSlot'));});
await check('Initial stage data positions enemy to left and allies to right without mirror',async h=>{let layout=h.w.BattleLabDiagnostics.getStageLayout(),s=h.w.BattleLabDiagnostics.getSnapshot().state;A.ok(layout.positions.length>=s.allies.length+s.enemies.length);let enemies=layout.positions.filter(x=>x.id.startsWith('enemy:')),allies=layout.positions.filter(x=>x.id.startsWith('ally:'));A.ok(enemies.length&&allies.length);A.ok(Math.max(...enemies.map(x=>x.x))<Math.min(...allies.map(x=>x.x)));A.ok(!fs.readFileSync(path.join(ROOT,'style.css'),'utf8').includes('scaleX(-1)'));});
await check('Focused Cancel plus Enter returns to menu rather than paying for target',async h=>{let before=snapshot(h);choose(h,'basic');await h.frame(250);h.$('#cancelBtn').focus();key(h,'Enter');A.equal(snapshot(h),before);A.equal(h.diag().selected,null);A.ok(h.diag().menuOpen);A.equal(h.diag().menuCategory,'battle');});
await check('Setup close re-enables step and auto debug controls immediately',async h=>{await setup(h,'elite_humanoid',['amy','lynae']);A.equal(h.$('#stepBtn').disabled,false);A.equal(h.$('#autoBtn').disabled,false);let before=snapshot(h);h.click('#stepBtn');A.notEqual(snapshot(h),before);await settle(h);});
await check('Visible Bracer stance warning is not incorrectly hidden as ordinary intent',async h=>{await setup(h,'elite_humanoid',['amy','lynae']);let seen=false;for(let i=0;i<30&&!h.diag().result;i++){h.click('#stepBtn');await settle(h);let s=h.w.BattleLabDiagnostics.getSnapshot().state,e=s.enemies.find(x=>x.key==='bracer');if(e.status.brace){seen=true;A.ok(h.$('#enemyCards').textContent.includes('危险预警'));A.ok(h.$('#enemyCards').textContent.includes('架岩'));break;}}A.ok(seen,'did not reach brace fixture');});
await check('Boss phase threshold publishes a warning before phase damage executes',async h=>{await setup(h,'boss',['amy','lynae','mornye','chisa']);let seen=false;for(let i=0;i<100&&!h.diag().result;i++){h.click('#stepBtn');let s=h.w.BattleLabDiagnostics.getSnapshot().state,e=s.enemies[0];if(e.phase_pending||e.phase_attack_pending){seen=true;A.ok(h.$('#enemyCards').textContent.includes('危险预警'));A.ok(/展翼|阶段/.test(h.$('#enemyCards').textContent));break;}await settle(h);}A.ok(seen,'did not reach phase warning fixture');});
await check('Head markers use finite explicit head anchors above ground',async h=>{await h.frame(500);let bounds=h.w.BattleLabDiagnostics.getStageLayout().bounds;A.ok(bounds.length);for(let b of bounds){A.ok(Number.isFinite(b.headX)&&Number.isFinite(b.headY),b.id);A.ok(b.headY<b.y,b.id);}});
for(const who of ['amy','rover'])await check(who==='amy'?'Old idle-alias hurt keeps critical sprite when struck at low HP':'Distinct Rover hurt sprite renders on impact and returns to critical',async h=>{h.click('#setupBtn');for(const x of h.w.document.querySelectorAll('#teamChoices input'))x.checked=x.value===who;h.change('#encounterSelect','custom');for(const [i,x]of [...h.w.document.querySelectorAll('[data-enemy-slot]')].entries())x.value=i===0?'snip':'';h.change('#difficultySelect','easy');h.input('#hpInput',25);h.click('#startBtn');let hit=false;for(let i=0;i<10;i++){let s=h.w.BattleLabDiagnostics.getSnapshot().state,c=s.allies.concat(s.enemies).find(x=>x.id===s._currentId);if(c.side==='enemy'){h.click('#stepBtn');h.draws.length=0;await h.frame(200);let after=h.w.BattleLabDiagnostics.getSnapshot().state,a=after.allies[0];A.ok(a.hp>0&&a.hp/a.maxhp<=.25);let assets=h.w.BattleLabDiagnostics.assets,form=assets.forms[who][who==='amy'?'human':'male_default'],expected=assets.slots[form.actions[who==='amy'?'critical':'hurt']].src;let drawn=h.draws.filter(x=>x.canvas==='battleCanvas');A.ok(drawn.some(x=>x.src===expected),JSON.stringify(drawn));A.ok(!drawn.some(x=>x.src===assets.slots[form.idle].src));h.draws.length=0;await h.frame(600);A.ok(h.draws.some(x=>x.canvas==='battleCanvas'&&x.src===assets.slots[form.actions.critical].src));hit=true;break;}h.click('#stepBtn');while(h.diag().busy)await h.next();}A.ok(hit);});
await check('Project export/import preserves real embedded bytes, new head calibration and exact AP battle',async h=>{choose(h,'basic');await h.frame(250);h.click('#confirmBtn');await settle(h);h.click('#assetsBtn');h.click('[data-tab=background]');await h.import('#backgroundFile','qa_checkerboard.png');h.click('[data-tab=sprites]');h.input('[data-cal=headX]','0.31');h.input('[data-cal=headY]','0.19');h.input('[data-cal=scale]','1.25');h.click('[data-tab=audio]');await h.import('[data-audio=hit]','qa_chime.wav');h.click('[data-tab=project]');h.click('#exportProject');let raw=await h.downloads.at(-1).blob.text(),saved=JSON.parse(raw),k=await begin();try{k.click('#assetsBtn');k.click('[data-tab=project]');await k.import('#importProject','roundtrip.json',raw);A.deepEqual(JSON.parse(snapshot(k)),saved.battle);let restored=JSON.parse(JSON.stringify(k.w.BattleLabDiagnostics.getProject()));for(let key of ['overrides','calibration','appearance','background','audio'])A.deepEqual(restored[key],saved[key]);A.ok(Object.values(restored.calibration).some(c=>c.headX===.31&&c.headY===.19&&c.scale===1.25));A.equal(restored.background.name,'qa_checkerboard.png');A.equal(restored.audio.hit.name,'qa_chime.wav');}finally{k.close();}});
await check('Malformed and out-of-range project imports are atomic for both project and combat',async h=>{h.click('#assetsBtn');h.click('[data-tab=project]');h.click('#exportProject');let good=JSON.parse(await h.downloads.at(-1).blob.text()),before=snapshot(h),proj=JSON.stringify(h.w.BattleLabDiagnostics.getProject()),badHead=structuredClone(good),badAP=structuredClone(good);badHead.calibration['amy.human.A01']={headX:1.01};badAP.battle.state.allies[0].ap=7;for(let raw of ['{broken',JSON.stringify(badHead),JSON.stringify(badAP)]){await h.import('#importProject','bad.json',raw);A.equal(snapshot(h),before);A.equal(JSON.stringify(h.w.BattleLabDiagnostics.getProject()),proj);}});
await check('Actual v0.1 project file retains custom assets but starts a new AP-rule battle',async h=>{const raw=fs.readFileSync(path.join(ROOT,'tests/independent/v02/fixtures/v01_project_with_battle.json'),'utf8'),old=JSON.parse(raw);h.click('#assetsBtn');h.click('[data-tab=project]');await h.import('#importProject','old.json',raw);let p=JSON.parse(JSON.stringify(h.w.BattleLabDiagnostics.getProject())),s=h.w.BattleLabDiagnostics.getSnapshot();for(let key of ['overrides','calibration','appearance','audio'])A.deepEqual(p[key],old[key]);A.equal(p.background.data,old.background.data);A.notEqual(s.parameter_version,old.battle.parameter_version);A.ok(h.$('#migrationNotice').textContent.includes('旧版'));A.ok(s.state.allies.every(a=>a.ap===4));});
for(const width of [620,650,700,1000])await check('Simulated '+width+'px stage detail panel clears all four current actors after forward movement',async h=>{const height=600,stage=h.$('#stage');Object.defineProperty(stage,'clientWidth',{configurable:true,value:width});Object.defineProperty(stage,'clientHeight',{configurable:true,value:height});h.$('#battleCanvas').getBoundingClientRect=()=>({left:0,top:0,width,height,right:width,bottom:height});let visited=[];for(let n=0;n<4;n++){await h.frame(40);let id=h.diag().current;h.click('#actorTrigger');await h.frame(40);A.ok(h.diag().menuOpen);let l=h.w.BattleLabDiagnostics.getStageLayout(),b=l.bounds.find(x=>x.id===id),p=l.positions.find(x=>x.id===id),detail=h.$('#actionDetail');A.equal(b.x,p.x,'draw loop retained a stale pre-movement position');A.ok(Number.isFinite(b.headX));let edge=parseFloat(detail.style.left)+parseFloat(detail.style.width);A.ok(edge<=b.left-10,JSON.stringify({id,width,edge,actorLeft:b.left}));visited.push(id);h.click('[data-category=battle]');h.click('[data-action=end]');await h.frame(250);h.click('#confirmBtn');await settle(h);}A.equal(new Set(visited).size,4);A.ok(visited.some(x=>x.endsWith(':denia')));});
const result={evidence:'Independent DOM-event integration only. Uses existing harness with mocked Canvas/Audio/Image/IndexedDB/timers; not actual-browser evidence.',timestamp:new Date().toISOString(),hashes,unchanged:files.every(f=>hashes[f]===sha(f)),passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results};fs.writeFileSync(path.join(OUT,'dom_e_independent_results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));process.exitCode=result.failed||!result.unchanged?1:0;
})();
