'use strict';
// Independent specification tests. Artificial fixtures isolate rules, not balance.
const test=require('node:test'); const A=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const ROOT=process.env.QA_ROOT||process.cwd();
const Engine=require(path.join(ROOT,'engine.js'));const P=JSON.parse(fs.readFileSync(path.join(ROOT,'parameters.json')));
const clone=x=>JSON.parse(JSON.stringify(x)); const snap=b=>JSON.stringify(b.snapshot());
function fixture(team=['amy'],opts={}){const p=clone(P);for(const e of Object.values(p.enemies)){e.hp=1000000;e.speed=100;}for(const [i,c] of Object.values(p.characters).entries()){c.hp=100000;c.speed=300-i;}const b=new Engine(p,{team,encounter:'boss',enemy_atk_scale:0,...opts});b.start();return b;}
function end(b){const r=b.act('end',b.current.id);A.ok(r.ok,r.reason);return r;}
function untilRound(b,r){let n=0;while(b.round<r&&!b.result&&n++<100){if(b.current.side==='enemy')A.ok(b.stepEnemy().ok);else end(b);}A.ok(n<100);A.equal(b.round,r);}
function untilActor(b,key){let n=0;while(b.current?.key!==key&&!b.result&&n++<100){if(b.current.side==='enemy')A.ok(b.stepEnemy().ok);else end(b);}A.ok(n<100);A.equal(b.current?.key,key);}
function basic(b){const r=b.act('basic',b.living('enemy')[0].id);A.ok(r.ok,r.reason);return r;}
function unchangedReject(b,fn){let before=snap(b),r=fn();A.equal(r.ok,false);A.ok(r.reason);A.equal(snap(b),before);}

test('normal AP opens exactly four and start is idempotent',()=>{let b=fixture(['amy','lynae']);for(const a of b.allies)A.equal(a.ap,4);let s=snap(b);b.start();A.equal(snap(b),s);});
test('paid attack retains actor, repeat spends AP and then closes window',()=>{let b=fixture(),a=b.current;basic(b);A.equal(a.ap,2);A.equal(b.current.id,a.id);basic(b);A.equal(a.ap,0);A.notEqual(b.current?.id,a.id);});
test('carry adds four instead of topping up, cap six and no transfer',()=>{let b=fixture(['amy','lynae']);basic(b);A.equal(b.allies[0].ap,2);A.equal(b.allies[1].ap,4);end(b);untilRound(b,2);A.equal(b.allies[0].ap,6);A.equal(b.allies[1].ap,6);end(b);untilRound(b,3);A.equal(b.allies[0].ap,6);});
test('eight budget supports four 2 AP attacks with no three-action cap',()=>{let b=fixture(),a=b.current;a.ap=6;a.temp_ap=2;a.relay_pending=true;for(let i=0;i<4;i++){A.equal(b.current.id,a.id);basic(b);}A.equal(a.ap,0);A.equal(a.temp_ap,0);});
test('temporary AP paid before normal pool',()=>{let b=fixture(),a=b.current;a.ap=6;a.temp_ap=2;a.relay_pending=true;basic(b);A.equal(a.temp_ap,0);A.equal(a.ap,6);});
test('insufficient AP, invalid target and removed generic actions reject atomically',()=>{let b=fixture();b.current.ap=1;for(let [s,t] of [['basic',b.enemies[0].id],['pry',b.enemies[0].id],['encourage',b.current.id],['basic','missing'],['__proto__',b.current.id]])unchangedReject(b,()=>b.act(s,t));});
test('outro cannot fire before a paid action and has no self target',()=>{let b=fixture(['amy','lynae']),a=b.current;a.concerto=100;unchangedReject(b,()=>b.concerto(a.id,b.allies[1].id));basic(b);unchangedReject(b,()=>b.concerto(a.id,a.id));});
test('outro gives recipient temporary two and ends source window',()=>{let b=fixture(['amy','lynae']),a=b.current,t=b.allies[1];a.concerto=100;basic(b);let targetAP=t.ap;let r=b.concerto(a.id,t.id);A.ok(r.ok,r.reason);A.equal(a.concerto,0);A.equal(t.temp_ap,2);A.equal(t.ap,targetAP);A.equal(t.relay_pending,true);A.notEqual(b.current.id,a.id);});
test('recipient buff and unspent temporary AP expire at recipient window end',()=>{let b=fixture(['amy','lynae']),a=b.current,t=b.allies[1];a.concerto=100;basic(b);A.ok(b.concerto(a.id,t.id).ok);untilActor(b,t.key);A.equal(t.temp_ap,2);end(b);A.equal(t.temp_ap,0);A.equal(t.relay_pending,false);A.equal(t.status.outro,undefined);});
test('already-acted recipient relay persists until next personal window',()=>{let b=fixture(['amy','lynae']);end(b);let a=b.current,t=b.allies[0];A.equal(a.key,'lynae');a.concerto=100;basic(b);A.ok(b.concerto(a.id,t.id).ok);A.equal(t.temp_ap,2);A.equal(t.relay_pending,true);untilRound(b,2);A.equal(b.current.id,t.id);A.equal(t.temp_ap,2);end(b);A.equal(t.temp_ap,0);});
test('pending recipient cannot stack relay even after temporary points consumed',()=>{let b=fixture(['amy','lynae','mornye']);let [a,t,c]=b.allies;a.concerto=100;basic(b);A.ok(b.concerto(a.id,t.id).ok);untilActor(b,t.key);basic(b);A.equal(t.temp_ap,0); // expiry must still wait for window end
A.equal(t.relay_pending,true);c.concerto=100;unchangedReject(b,()=>b.concerto(c.id,t.id));});
test('concerto real gain is bounded per actor per round',()=>{let b=fixture(),a=b.current;a.ap=6;a.temp_ap=2;let before=a.concerto;for(let i=0;i<4;i++)basic(b);A.ok(a.concerto-before<=40);A.ok(a.concerto_gain_round<=40);});
test('all six element resistances are explicit for every enemy',()=>{const keys=['glacio','fusion','electro','aero','spectro','havoc'];for(let [k,e] of Object.entries(P.enemies)){let rs=e.resistances||e.resistance||e.resist;for(let el of keys)A.ok(Number.isFinite(rs?.[el]),`${k}.${el}`);A.ok(Number.isFinite(e.def));A.ok(!e.weak_elements?.length);A.ok(!e.weak_weapons?.length);}});
test('common enemies have no resonance, elite and boss do',()=>{let b=new Engine(P,{team:['amy'],encounter:'normal'});for(let e of b.enemies)if(e.rank==='common'){A.equal(e.shield,0);A.equal(e.maxshield,0);}for(let encounter of ['elite_humanoid','elite_nonhumanoid','boss']){if(!P.encounters[encounter])continue;let x=new Engine(P,{team:['amy'],encounter});for(let e of x.enemies)if(e.rank!=='common')A.ok(e.maxshield>0);}});
test('basic resonance amount ignores DEF and elemental damage resistance',()=>{let x=fixture(),y=fixture();x.enemies[0].def=0;y.enemies[0].def=100000;x.enemies[0].resist={...x.enemies[0].resist,fusion:1};y.enemies[0].resist={...y.enemies[0].resist,fusion:.1};let xs=x.enemies[0].shield,ys=y.enemies[0].shield;basic(x);basic(y);A.equal(xs-x.enemies[0].shield,ys-y.enemies[0].shield);A.ok(xs-x.enemies[0].shield>0);});
test('break before enemy acts skips current round and recovers next round',()=>{let b=fixture(),e=b.enemies[0];e.shield=1;basic(b);A.equal(e.broken_until,1);A.equal(e.recovery_lock,false);end(b);A.equal(b.round,2);A.equal(e.normal_count,0);A.equal(e.shield,e.maxshield);A.equal(e.broken_until,0);A.equal(e.recovery_lock,false);});
test('break after enemy acts skips next round exactly',()=>{let b=fixture(['amy','lynae']);b.enemies[0].speed=299.5; // first round queue already built, use round two to respect fixed-order contract
untilRound(b,2);end(b);A.equal(b.current.side,'enemy');A.ok(b.stepEnemy().ok);let e=b.enemies[0],prior=e.normal_count;A.equal(b.current.key,'lynae');e.shield=1;basic(b);A.equal(e.broken_until,3);end(b);untilRound(b,4);A.equal(e.normal_count,prior);A.equal(e.shield,e.maxshield);});
test('break joint reward follows low coefficient reference budget and grants no recipient resource',()=>{let b=fixture(['amy','lynae','mornye','denia']),e=b.enemies[0];e.shield=1;let before=b.allies.slice(1).map(a=>({id:a.id,rsc:clone(a.rsc),ap:a.ap,temp_ap:a.temp_ap,c:a.concerto}));let r=basic(b);let joint=r.events.filter(x=>/joint/.test(x.event));A.ok(joint.length>0);for(let s of before){let a=b.getUnit(s.id);A.deepEqual(a.rsc,s.rsc);A.equal(a.ap,s.ap);A.equal(a.temp_ap,s.temp_ap);A.equal(a.concerto,s.c);}let expected=b.allies.reduce((sum,a)=>sum+Math.max(1,Math.floor(a[a.damage_stat||'atk']*(.72/b.allies.length)*(120+4*a.level)/(120+4*a.level+e.def)*((e.resist||{})[a.element]??1))),0);A.equal(joint.find(x=>x.event==='joint_attack').amount,expected);});
test('ordinary enemy intent does not reveal skill/target and danger is distinct',()=>{let b=fixture(),e=b.enemies[0],i=b.enemyIntent(e.id);A.ok(i);if(!i.committed&&!i.dangerous&&!i.telegraphed){A.ok(!i.key||i.key==='hidden');A.ok(!i.targets?.length);}});
test('normal action restore preserves every new field and deterministic next step',()=>{let b=fixture(['amy','lynae']);basic(b);let s=b.snapshot(),r=Engine.restore(b.params,s);A.deepEqual(r.snapshot(),s);A.deepEqual(basic(r),basic(b));A.deepEqual(r.snapshot(),b.snapshot());});
test('tampered AP and action state snapshots are rejected',()=>{let b=fixture();let s=b.snapshot();for(let [key,val] of [['ap',7],['ap',-1],['ap',1.5],['temp_ap',3],['temp_ap',-1],['window_actions',-1],['concerto_gain_round',41],['relay_pending','yes']]){let bad=clone(s);bad.state.allies[0][key]=val;A.throws(()=>Engine.restore(b.params,bad),`${key}=${val}`);}});
test('parameter JS and JSON expose exact same current data',()=>{const vm=require('node:vm');let c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(ROOT,'parameters.js'),'utf8'),c);const data=c.window.BATTLE_PARAMETERS;A.ok(data,`exports: ${Object.keys(c)}`);A.deepEqual(clone(data),P);});

test('joint reward does not consume or amplify personal next-status buff',()=>{let b=fixture(['amy','denia']),t=b.allies[1],e=b.enemies[0];t.status.status_outro={amp:.25,expires:1,window_bound:true};e.shield=1;basic(b);A.ok(t.status.status_outro,'joint consumed unrelated future status buff');});

test('break adds no generic 1.5x vulnerability to following attacks',()=>{let b=fixture(),e=b.enemies[0];e.shield=1;let d1=basic(b).events.find(x=>x.event==='damage'&&x.actor===b.allies[0].id&&!x.status_damage);let d2=basic(b).events.find(x=>x.event==='damage'&&x.actor===b.allies[0].id&&!x.status_damage);A.equal(d1.amount,d2.amount);A.equal(d2.broken_bonus,false);});
function untilCharge(b){let n=0;while(!b.enemies[0].status.charge&&n++<100){if(b.current.side==='enemy')A.ok(b.stepEnemy().ok);else end(b);}A.ok(n<100);A.ok(b.enemies[0].status.charge);while(b.current.side==='enemy')A.ok(b.stepEnemy().ok);return b.enemies[0];}
function enemyStep(b){let n=0;while(b.current?.side!=='enemy'&&!b.result&&n++<20)end(b);A.ok(n<20);let r=b.stepEnemy();A.ok(r.ok,r.reason);return r;}
test('Bracer feint is a 1 AP costly alternative without body damage, resource or concerto',()=>{let b=fixture(['amy'],{encounter:['bracer']}),e=b.enemies[0];untilRound(b,2);A.ok(e.status.brace);let a=b.current,hp=e.hp,r=clone(a.rsc),c=a.concerto,ap=a.ap;A.ok(b.act('feint',e.id).ok);A.equal(a.ap,ap-1);A.equal(e.status.brace,undefined);A.equal(e.hp,hp);A.deepEqual(a.rsc,r);A.equal(a.concerto,c);unchangedReject(b,()=>b.act('feint',e.id));});
test('Crownless part cancellation costs actions but does not damage body or skip an extra window',()=>{let b=fixture(['amy','lynae'],{encounter:['crownless']}),e=untilCharge(b),a=b.current,hp=e.hp,rs=clone(a.rsc),c=a.concerto,beforeAP=a.ap,parts=0;A.ok(e.part);while(e.part&&parts++<4){A.equal(b.current.id,a.id);A.ok(b.act('disrupt_part',e.id).ok);}A.equal(parts,3);A.equal(a.ap,beforeAP-6);A.equal(e.hp,hp);A.deepEqual(a.rsc,rs);A.equal(a.concerto,c);A.equal(e.status.charge,undefined);A.equal(e.skip_round,0);let r=enemyStep(b);A.ok(r.events.some(x=>x.event==='enemy_action'));A.ok(!r.events.some(x=>x.event==='enemy_action'&&x.skill==='descent'));});
test('Carapace part route costs 4 AP and reduces rather than cancels release',()=>{let b=fixture(['amy','lynae'],{encounter:['carapace'],enemy_atk_scale:1}),e=untilCharge(b),raw=Engine.restore(b.params,b.snapshot()),hp=e.hp,a=b.current,before=a.ap;A.ok(b.act('disrupt_part',e.id).ok);A.ok(b.act('disrupt_part',e.id).ok);A.equal(a.ap,before-4);A.equal(e.hp,hp);A.ok(e.part.destroyed);let reduced=enemyStep(b),full=enemyStep(raw);let rd=reduced.events.filter(x=>x.event==='damage'&&x.actor===e.id).map(x=>x.amount),fd=full.events.filter(x=>x.event==='damage'&&x.actor===e.id).map(x=>x.amount);A.equal(rd.length,fd.length);A.ok(reduced.events.some(x=>x.event==='charge_released'));for(let i=0;i<rd.length;i++)A.ok(Math.abs(rd[i]-fd[i]*.45)<=1);});
test('Committed target rejects post-lock taunt atomically',()=>{let b=fixture(['amy','lynae'],{encounter:['bracer']}),e=untilCharge(b),i=b.enemyIntent(e.id);A.ok(i.committed);A.ok(i.targets.length);unchangedReject(b,()=>b.act('taunt',e.id));A.deepEqual(b.enemyIntent(e.id).targets,i.targets);});
test('Danger break cancels pending action and its part with no immediate replacement attack',()=>{let b=fixture(['amy','lynae'],{encounter:['crownless']}),e=untilCharge(b);e.shield=1;let r=basic(b);A.equal(e.status.charge,undefined);A.equal(e.part,null);A.ok(r.events.some(x=>x.event==='charge_interrupted'));A.ok(!r.events.some(x=>x.event==='enemy_action'));});
test('Rover marker ownership is removed on retreat and remains restorable',()=>{for(let mode of ['spectro','aero']){let b=fixture(['rover','amy'],{mode:{rover:mode}});untilActor(b,'rover');A.ok(b.act('skill',b.enemies[0].id).ok);A.ok(b.act('retreat',b.current.id).ok);A.ok(!b.enemies[0].status.spectro_mark);A.ok(!b.enemies[0].status.wind_mark);A.deepEqual(Engine.restore(b.params,b.snapshot()).snapshot(),b.snapshot());}});
test('Prisms immune to own element but have no resonance, other element hurts',()=>{for(let key of ['glacio_prism','fusion_prism','aero_prism','spectro_prism','havoc_prism']){let p=clone(P),e=p.enemies[key];A.ok(e);let b=new Engine(p,{team:['amy'],encounter:[key],enemy_atk_scale:0});b.start();while(b.current.side==='enemy')b.stepEnemy();let u=b.current,t=b.enemies[0];u.element=e.immune_elements[0];let hp=t.hp;b.act('basic',t.id);A.equal(t.hp,hp);A.equal(t.shield,0);u.element=u.element==='fusion'?'spectro':'fusion';A.ok(b.act('basic',t.id).ok);A.ok(t.hp<hp);}});
test('Lethal retaliation cannot recreate dead Rover effects in any mode',()=>{for(let mode of ['spectro','havoc','aero','electro']){let b=fixture(['rover','amy'],{mode:{rover:mode},encounter:['bracer'],enemy_atk_scale:1});untilRound(b,2);untilActor(b,'rover');let a=b.current,e=b.enemies[0];a.hp=1;a.concerto=100;for(let k of Object.keys(a.rsc))a.rsc[k]=a.resources[k];let skill=['havoc','electro'].includes(mode)?'enhanced':'skill';let result=b.act(skill,e.id);A.ok(result.ok,mode+': '+result.reason);A.equal(a.hp,0);A.deepEqual(a.status,{});A.ok(Object.values(e.status).every(s=>s.owner!==a.id));A.deepEqual(Engine.restore(b.params,b.snapshot()).snapshot(),b.snapshot());}});
test('Current basic damage preview includes Havoc enhanced state',()=>{let b=fixture(['rover'],{mode:{rover:'havoc'}}),a=b.current,e=b.enemies[0];a.rsc.umbra=100;a.ap=6;A.ok(b.act('enhanced',e.id).ok);let predicted=b.previewDamage(a.id,'basic',e.id).amount;let r=b.act('basic',e.id);A.ok(r.ok);A.equal(r.events.find(x=>x.event==='damage'&&x.damage_source==='direct').amount,predicted);});
test('Enemy AOE stops remaining targets and debuffs when source is killed by counter',()=>{let p=clone(P);p.characters.rover.speed=300;p.characters.amy.speed=200;p.enemies.crownless.speed=100;p.enemies.crownless.pattern=['sweep'];p.enemies.crownless.difficulty_patterns={standard:['sweep']};let b=new Engine(p,{team:['rover','amy'],mode:{rover:'electro'},encounter:'boss'});b.start();let a=b.allies[0],other=b.allies[1],e=b.enemies[0];e.hp=1;let untouched=other.hp;A.ok(b.act('counter',a.id).ok);if(b.current?.id===a.id)end(b);if(b.current?.id===other.id)end(b);let r=b.stepEnemy();A.ok(r.ok);A.equal(e.hp,0);A.equal(other.hp,untouched);A.ok(b.allies.every(x=>!x.status.exposed));let death=r.events.findIndex(x=>x.event==='incapacitated'&&x.unit===e.id);A.ok(death>=0);A.ok(!r.events.slice(death+1).some(x=>x.event==='damage'&&x.actor===e.id));A.deepEqual(Engine.restore(p,b.snapshot()).snapshot(),b.snapshot());});
test('Counter applies stated 0.6 mitigation and matching status preview',()=>{let b=fixture(['rover'],{mode:{rover:'electro'},enemy_atk_scale:1});let a=b.current,e=b.enemies[0],s=b.getSkill(e,'spear'),hp=a.hp;A.ok(b.act('counter',a.id).ok);let expected=Math.floor(e.atk*s.coef*(120+4*e.level)/(120+4*e.level+a.def)*((a.resist||{})[e.element]??1)*.6);let predicted=b.previewPacket(e,a,s.coef,e.element,false);let r=b.stepEnemy();A.ok(r.ok);A.equal(hp-a.hp,expected);A.equal(predicted,expected);});
test('Initially defeated allies have no AP/concerto and partial or full KO snapshots restore',()=>{for(let options of [{initialHP:{amy:0}},{hp_fraction:0}]){let b=new Engine(P,{team:['amy','lynae'],encounter:'boss',...options});b.start();for(let a of b.allies)if(a.hp===0){A.equal(a.ap,0);A.equal(a.concerto,0);A.equal(a.temp_ap,0);}A.deepEqual(Engine.restore(P,b.snapshot()).snapshot(),b.snapshot());}});
test('Taunt redirects at 1 AP and amplifies only the next single-target hit by fifteen percent',()=>{for(let key of ['spear','sweep']){let p=clone(P);p.characters.amy.hp=100000;p.characters.amy.speed=300;p.characters.lynae.hp=100000;p.characters.lynae.speed=290;p.enemies.crownless.speed=100;p.enemies.crownless.pattern=[key];p.enemies.crownless.difficulty_patterns={standard:[key]};let b=new Engine(p,{team:['amy','lynae'],encounter:'boss'});b.start();let e=b.enemies[0],a=b.current,ap=a.ap,s=b.getSkill(e,key),hp=a.hp;A.ok(b.act('taunt',e.id).ok);A.equal(a.ap,ap-1);end(b);end(b);let r=b.stepEnemy();A.ok(r.ok);let d=r.events.find(x=>x.event==='damage'&&x.target===a.id);A.ok(d);let amp=key==='spear'?.15:0;A.equal(d.amp_applied,amp);let expected=Math.floor(e.atk*s.coef*(120+4*e.level)/(120+4*e.level+a.def)*((a.resist||{})[e.element]??1)*(1+amp));A.equal(hp-a.hp,expected);if(key==='spear')A.equal(e.status.taunt,undefined);else A.ok(e.status.taunt);A.deepEqual(Engine.restore(p,b.snapshot()).snapshot(),b.snapshot());}});
