'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),A=require('node:assert/strict');
const ROOT=process.env.QA_ROOT||process.cwd(),OUT=process.env.QA_OUT||__dirname;
const {boot,settle}=require(path.join(ROOT,'tests/independent/v03/dom_harness_v03.cjs'));
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,f))).digest('hex');let files=['app.js','assets.js','engine.js','parameters.js','tests/independent/v03/dom_harness_v03.cjs'],hashes=Object.fromEntries(files.map(f=>[f,hash(f)])),results=[];
const snap=h=>h.w.BattleLabDiagnostics.getSnapshot(),layout=h=>h.w.BattleLabDiagnostics.getStageLayout();
const choose=h=>{h.click('#actorTrigger');h.click('[data-category=skills]');h.click('[data-action=skill]');};
(async()=>{for(const [i,form]of ['male_default','male_school','female_default','female_school'].entries())for(const reduced of [false,true]){let h;const cleanup=['timeout','restart','load','import'][i];try{h=await boot();await settle(h);let width=1000,height=600;Object.defineProperty(h.$('#stage'),'clientWidth',{get:()=>width});Object.defineProperty(h.$('#stage'),'clientHeight',{get:()=>height});h.$('#battleCanvas').getBoundingClientRect=()=>({left:0,top:0,width,height});if(reduced){h.click('#assetsBtn');h.click('[data-tab=project]');h.$('#reduceMotion').checked=true;h.$('#reduceMotion').dispatchEvent(new h.w.Event('change'));h.click('[data-close=assetDialog]');}h.click('#setupBtn');for(const n of h.w.document.querySelectorAll('#teamChoices input'))n.checked=n.value==='rover';h.change('[data-appearance=rover]',form);h.change('[data-mode=rover]','electro');h.change('#difficultySelect','easy');h.click('#startBtn');await settle(h);await h.frame(40);let before=snap(h),state=JSON.stringify(before),actor=before.state.allies[0];h.click('#saveBtn');for(let n=0;n<3;n++)await h.tick();const project=h.w.BattleLabDiagnostics.getProject();project.battle=before;
choose(h);h.click('#cancelBtn');await h.frame(250);A.equal(JSON.stringify(snap(h)),state);A.equal(layout(h).effects.length,0,'cancel created tether');h.click('#actorTrigger');choose(h);let options=[...h.w.document.querySelectorAll('[data-target]')];A.ok(options.length>1);let target=options.at(-1).dataset.target;options.at(-1).click();await h.frame(250);h.click('#confirmBtn');h.click('#confirmBtn');await h.frame(reduced?10:180);let l=layout(h);A.equal(l.effects.length,1);let e=l.effects[0],a=l.bounds.find(b=>b.id===actor.id);A.equal(e.actor,actor.id);A.equal(e.target,target);A.equal(e.from.x,Math.round(a.castX));A.equal(e.from.y,Math.round(a.castY));A.ok(e.points.every(p=>Number.isInteger(p.x)&&Number.isInteger(p.y)));A.equal(snap(h).state.allies[0].ap,actor.ap-2);A.equal(snap(h).state.log.filter(e=>e.event==='action'&&e.actor===actor.id&&e.skill==='skill').length,1);
width=800;height=500;await h.frame(reduced?1:30);l=layout(h);A.equal(l.effects.length,1);e=l.effects[0];a=l.bounds.find(b=>b.id===actor.id);A.equal(e.from.x,Math.round(a.castX));A.equal(e.from.y,Math.round(a.castY));A.equal(e.target,target);
if(cleanup==='restart')h.click('#restartBtn');else if(cleanup==='load'){h.click('#resumeBtn');for(let n=0;n<8;n++)await h.tick();A.equal(JSON.stringify(snap(h)),state);}else if(cleanup==='import'){h.click('#assetsBtn');h.click('[data-tab=project]');await h.import('#importProject','before.json',JSON.stringify(project));A.equal(JSON.stringify(snap(h)),state);}await h.frame(cleanup==='timeout'?800:40);A.equal(layout(h).effects.length,0,cleanup+' left stale tether');A.equal(h.errors.length,0);results.push({form,reducedMotion:reduced,cleanup,target,pass:true});}catch(e){results.push({form,reducedMotion:reduced,cleanup,pass:false,error:e.stack});}finally{h?.close();}}
const out={evidence:'Independent real UI event pipeline and frame-effect records, with simulated canvas/media/clock/storage. Not visual browser acceptance.',hashes,unchanged:files.every(f=>hash(f)===hashes[f]),passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results};fs.writeFileSync(path.join(OUT,'tether_e_independent_results.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));process.exitCode=out.failed||!out.unchanged?1:0;})();
